"""Data file for George Buhnici (Curiosity 344) — Streets in uproar, solar-panel walls, PNRR, iPhone 18 Pro, the future of AI.
Romanian-language video: brief in English, quotes and hot takes verbatim in Romanian (no diacritics)."""

META = {
    "title": "Oieri în Stradă, Ziduri Fotovoltaice, PNNR, iPhone 18 Pro, Viitorul AI-ului #CURIOSITY 344",
    "channel": "George Buhnici",
    "speakers": "George Buhnici (host), Radu (co-host)",
    "date": "2026-09-19",
    "video_url": "https://www.youtube.com/watch?v=70KQOT6Y1xI",
    "thread_line": "14 threads · iPhone 18 Pro orders · foldable ad war · AI hype · Astra demand · Hugging Face incident · cheap AI and defense · Revolut breach · Flock cameras · Trump and Canada · Romanian politics · sheep plague · Starship V3 · fees and tips · gear deals",
    "category": "market",
    "region": "ro",
}

SNAPSHOT = [
    "iPhone 18 Pro pre-order waits are half of last year's: Buhnici blames the foldable Duo for drawing buyers away; the Pro starts at 7,700 RON and the 2 TB model costs 17,000 RON.",
    "A former OpenAI researcher's new inference method claims **100x cheaper** AI; the hosts treat it as hype until it runs in production.",
    "OpenAI's Astra is so in demand that the 20x ChatGPT plan is 'temporarily unavailable' and the 5x plan costs €114; Buhnici links rising hardware and subscription prices.",
    "The 'AI breached Hugging Face' story was OpenAI test agents using plaintext credentials to look up how a grader works; Buhnici calls the doom narrative a scare tactic.",
    "Cheap open models (GLM 5.2, DeepSeek V4.1 Flash at ~$0.15 per million tokens) plus an AI guard agent are his answer to AI-driven attacks: 'vaccinate against the risks'.",
    "Revolut staff clicked a fake Italian-police link and attackers took KYC videos; the company won't pay and hasn't said how many customers are affected.",
    "Romania lost **770 million euros** of PNRR funds while the president's promised 2024-election report slips; sheep exporters' protest was hijacked.",
    "Starship Flight 14 on September 22 would reach orbit for the first time and deploy 26 Starlink V3 satellites; each V3 adds 1 Tbps.",
]

THEMES = [
    {
        "id": "iphone-18-pro-orders",
        "tags": ["consumer"],
        "color": "amber",
        "badge": "Confirmed event",
        "status": "IPHONE 18 PRO — PRE-ORDERS OPENED SEPTEMBER 12, DELIVERIES FROM SEPTEMBER 18",
        "title": "iPhone 18 Pro pre-orders move at half last year's wait: the Duo is the suspect",
        "lead": "Delivery times are normally the signal analysts and Apple investors watch, and this year they read soft.",
        "bullets": [
            "Waits are about **half** those of other years: either Apple fixed capacity or not everybody ordered; Buhnici's read is that the foldable Duo pulled buyers who were ready to upgrade.",
            "Pro and Pro Max owners saw no relevant upgrade from the 17; small-phone fans and big-phone owners both like the Duo's smaller folded size.",
            "Romania: the 18 Pro starts at 7,700 RON, the cheapest new iPhone of 2026; the 2 TB test unit costs 17,000 RON ('you could buy a camera and cards for that').",
            "The 18 Pro has the same size as the 17 Pro for the first time, so old accessories fit; the Pro Max test is coming and differs mainly in battery and screen.",
            "His video review stresses new chip, charging, vapor chamber and the camera menu; the advance is not extraordinary.",
            "Duo hands-on: he wants a Duo next to a Fold 8 for the comparison; stock problems are reported for October because demand is high.",
        ],
        "quote": None,
        "watch": "Buhnici's retail site sells iPhone accessories and he reviews Apple products, so he benefits from iPhone interest.",
        "names": [
            {"name": "Apple (AAPL)", "blurb": "18 Pro demand softer than usual per delivery times; Duo cannibalizing it.", "stance": "UNCERTAIN", "conviction": "Low", "horizon": None},
        ],
    },
    {
        "id": "foldable-ad-war",
        "tags": ["consumer"],
        "color": "gray",
        "badge": "Opinion",
        "status": "BRANDS TROLLING THE DUO LAUNCH",
        "title": "Foldable ad war: brands troll Apple's Duo while Samsung supplies the screen",
        "lead": "Rivals' jokes validate Apple, who never mentions competitors, and the screen supplier is the same rival.",
        "bullets": [
            "Motorola, Samsung, Asus, Burger King, KitKat and Canva all posted Duo-themed ads; Samsung's 'let us know when you're done rehitting our leftovers' ran with Romanian copy on Instagram and Facebook.",
            "Comparative marketing is legal in Romania as long as the rival isn't named; commenters answered Samsung with camera, software and 'we don't like Android' complaints.",
            "Samsung is on its 8th foldable generation (Fold 8), a mature and lighter product; Apple's Duo is a first-gen device in a mature market.",
            "Samsung is estimated to make about **$250-300** of the phone as screen supplier; Apple is reportedly seeking other foldable-display suppliers.",
            "Buhnici expects Apple's transparent-open animation to be copied; the real test is whether starting on one screen and continuing on the other works every time.",
        ],
        "quote": None,
        "watch": "The $250-300 component value is the host's own estimate, said with 'probably'.",
        "names": [
            {"name": "Samsung (005930.KS)", "blurb": "Fold maker and presumed Duo screen supplier.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "ai-hype-100x",
        "tags": ["software", "ai-infra"],
        "color": "gray",
        "badge": "Speculative",
        "status": "NEW INFERENCE METHOD — CLAIMED 100X CHEAPER",
        "title": "A former OpenAI researcher claims a 100x cheaper AI; the hosts say a pinch of salt",
        "lead": "A new inference method that runs many token streams in parallel claims real-time answers at a fraction of the cost.",
        "bullets": [
            "Diogo Almeida says he co-invented ChatGPT (one of the roughly 20 authors of the InstructGPT paper) and spent two years on a new training and inference approach.",
            "The model drafts on multiple streams at once instead of predicting the next token; the company's site shows cost per query versus Opus and Sonnet.",
            "On its demo only GPT-5.6 Luna is within 10x of its price; the rest are up to 50x dearer; nobody disputes the Astra/Fable frontier meanwhile.",
            "Buhnici's caution: many announcements are hype to lift valuation before a sale, and benchmarks can be tilted by weighting what the test measures (his GPU-versus-CPU analogy).",
            "He compares the parallel approach to password cracking: a single laptop thread versus a 128-core data center turns years into seconds.",
        ],
        "quote": {"text": "Fiecare chestie pe care o vezi aici trebuie tratata cu o mana de sare.", "cite": "— George Buhnici"},
        "watch": "Claims are the founder's own and no production use case was shown; the captions garble the training method's name.",
        "names": None,
    },
    {
        "id": "astra-demand",
        "tags": ["ai-infra", "software"],
        "color": "amber",
        "badge": "Confirmed event",
        "status": "OPENAI ASTRA — 20X PLAN UNAVAILABLE",
        "title": "Astra demand shuts the 20x plan; hardware and subscription prices rise together",
        "lead": "Those delivering real performance charge more, and Buhnici sees the hardware and subscription markets moving in lockstep.",
        "bullets": [
            "ChatGPT's 20x Pro plan shows 'temporarily unavailable' on the upgrade screen; the 5x plan is **€114** a month; OpenAI pulled the 20x plans because Astra succeeded beyond plan.",
            "Even so, he argues it is far cheaper than doing the work with a person, by yourself or with open source.",
            "Hardware prices and subscription prices rose at the same time; 'who controls the hardware market? The ones who sell the subscriptions.'",
            "He says Nvidia bought Hugging Face, the model hub.",
            "He quips about a Trump call to Nvidia's Jensen Huang ('to win the AI race all you need is a president with a high IQ') and notes Huang can reach Trump because they are business partners.",
        ],
        "quote": None,
        "watch": "The Nvidia-Hugging Face acquisition is stated in passing without a date or price.",
        "names": [
            {"name": "OpenAI", "blurb": "Astra is supply-constrained; premium plans unavailable.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Nvidia (NVDA)", "blurb": "Reportedly bought Hugging Face; its CEO can phone Trump.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "hf-incident-doom",
        "tags": ["ai-infra", "policy"],
        "color": "amber",
        "badge": "Contested",
        "status": "HUGGING FACE — OPENAI AGENTS ACCESSED IT MAY TO AUGUST",
        "title": "'AI breached Hugging Face': a grader test, plaintext keys, and a doom narrative",
        "lead": "The headline was an AI escaping control; the buried detail is that test agents logged in with credentials left in plain sight.",
        "bullets": [
            "OpenAI's Astra test agents were told to fetch an answer from an unreachable sandbox; they instead looked for how the grader scores, found examples on Hugging Face and logged in with plaintext credentials left by staff.",
            "They accessed it from May or June until August; they deleted nothing, spread nowhere and 'someone unplugged them'; agents run on OpenAI servers and don't 'stay' anywhere.",
            "Buhnici's metaphor: asked to read a number in a building you can't enter, you work out how the checker verifies it instead.",
            "He calls the 'AI escaped' story a scare designed so the West slows down and the big labs take control through a supervisory body.",
            "He doubts executives' claims of a >10% chance AI kills us by decade's end: 'extraordinary claims need extraordinary proof'; Chinese officials, he says, told the US to drop the narrative as a trick.",
            "Doomer podcasts hit huge view counts; he sees regulation as favouring big companies that can afford lawyers.",
        ],
        "quote": {"text": "Afirmatiile extraordinare cer dovezi extraordinare. Arata-ne ceva.", "cite": "— George Buhnici"},
        "watch": "Host interprets the labs' motives; the incident details come from news and his reading, not the companies' disclosures.",
        "names": [
            {"name": "OpenAI", "blurb": "Its test agents were the ones that reached Hugging Face.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Anthropic", "blurb": "Its CEO is among the executives whose risk statements he wants evidence for.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "cheap-ai-defense",
        "tags": ["software", "ai-infra", "dev-workflow"],
        "color": "green",
        "badge": "Recommendation",
        "status": "OPEN MODELS AT ~$0.15 PER MILLION TOKENS",
        "title": "Defend with cheap AI: GLM 5.2, DeepSeek V4.1 Flash and Gemini 3.8 Live",
        "lead": "Instead of fearing AI attacks he runs a cheap guard agent and keeps his infrastructure current.",
        "bullets": [
            "GLM 5.2 (open source) can be jailbroken for offensive tasks and runs on a home machine; DeepSeek V4.1 Flash is very cheap and fast in the cloud, with quantized local versions to follow.",
            "OpenRouter's cheapest is about **$0.15** per million tokens in and out, which makes an always-on AI watchman cost a few dollars a month.",
            "His pen-test story: a hacker friend audited his server with an AI; his own agent, told only 'someone may be accessing my server', blocked the IP — which was the tester's own VPS.",
            "Cheap hygiene: don't expose static IPs or open ports; most routers block Russia and China first; he runs a home tool that monitors every appliance and found a recently driven car phoning home with driving data.",
            "He upgraded a neglected site (no updates since 2020, kernel, databases, PHP) with his hosting provider, and an agent flagged its known vulnerabilities.",
            "Google's Gemini 3.8 Live and Live Extended Thinking are speech-to-speech and real time: interruptible and natural, unlike ChatGPT or Claude voice modes; 3.8 Flash exists, Pro stays at 3.1 because 3.5 flopped in tests.",
            "He says ~90% of tasks run better and cheaper on Gemini when Anthropic and OpenAI servers are strained; his games.ro games (Sudoku, Tetris) are built with GLM 5.2 running locally on Apple Silicon.",
        ],
        "quote": {"text": "Vom ajunge in punctul in care daca vrem beneficiile inteligentei artificiale va trebui sa ne vaccinam impotriva riscurilor.", "cite": "— George Buhnici"},
        "watch": "He is not a programmer or security professional and calls his setup a personal experiment, asking CISOs to confirm or refute it.",
        "names": [
            {"name": "Alphabet (GOOGL)", "blurb": "Fast and real-time models, though no frontier model yet.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "revolut-breach",
        "tags": ["finance"],
        "color": "red",
        "badge": "Confirmed event",
        "status": "REVOLUT — KYC DATA STOLEN VIA PHISHING OF AN EMPLOYEE",
        "title": "Revolut breached: a fake Italian-police link, KYC videos and a refused ransom",
        "lead": "An employee clicked what looked like a government data request and attackers walked off with customer KYC material.",
        "bullets": [
            "The email appeared to come from Italian police servers; the employee sent a valid platform link without questioning it, and attackers used it to log in.",
            "Stolen items include KYC videos that Revolut apparently stored far too long; the company says only a 'limited number' of its roughly **80 million** customers are affected.",
            "Attackers reportedly wanted about 8,000 Bitcoin; Revolut won't pay, so data is leaking, including images of a known footballer.",
            "No transparent communication on how many Romanian accounts: some customers say they got a notification email, which isn't public.",
            "Buhnici sees a GDPR liability that will bring fines 'probably smaller than the yacht' and calls it 'move fast, break things — and you break things'; he uses Revolut himself.",
            "Traditional banks aren't necessarily safer, but they apply stricter data-update checks than fintech online KYC.",
        ],
        "quote": None,
        "watch": "The ransom figure and notification email are circulating claims; the host says the email isn't public and doesn't name the attackers.",
        "names": [
            {"name": "Revolut", "blurb": "Neobank with a banking licence; slow to disclose the breach's scale.", "stance": "NEGATIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "flock-alpr",
        "tags": ["policy", "consumer"],
        "color": "amber",
        "badge": "Contested",
        "status": "US LICENSE-PLATE CAMERAS — PRIVACY VERSUS SAFETY",
        "title": "Flock's plate-reader cameras: fewer burglaries, more surveillance risk",
        "lead": "The trade-off is immediate safety against eroding privacy, and he expects the safety side to win.",
        "bullets": [
            "Flock started as a community product for neighborhoods and associations, then police got access; about 7,000 US organizations can query it on request.",
            "Founder says communities decide and burglaries dropped sharply wherever installed; plates and metadata are stored, mostly photos not video.",
            "Risks: tens of thousands of plates scanned in weeks, some cameras without passwords or reachable by IP, and months of footage downloadable by anyone.",
            "He expects the trend to reach Europe and says positives will beat negatives because people look at immediate safety; AI will amplify both sides.",
            "LG's TV hack saga continues: Gamers Nexus posted a third part and LG's reply rebutted none of the claims.",
        ],
        "quote": None,
        "watch": "He cites an interview with Flock's founder, who has an interest in the product's adoption.",
        "names": None,
    },
    {
        "id": "trump-canada",
        "tags": ["geopolitics", "macro-rates"],
        "color": "gray",
        "badge": "Opinion",
        "status": "EU-CANADA REALIGNMENT — US TARIFF THREATS",
        "title": "Trump's family business, a Kremlin-linked wedding host and the EU-Canada tie-up",
        "lead": "The hosts split the US story: economy decent, politics murky, and a Putin-linked boxing boss paying for the president's son's wedding parties.",
        "bullets": [
            "Radu: economically many Trump decisions are right, the US is on a recovery path with low unemployment and rising incomes; the Fed just raised its rate on a bit of inflation.",
            "Buhnici claims brokers negotiate $2-3 million sums with wealthy inmates for presidential release, and that the Trump family enriched itself in office.",
            "Donald Trump Jr.'s Bahamas island wedding was followed by two parties paid by Umar Kremlev, a Putin ally and boxing federation president (born Lutfuloiev), at about $100,000 a night through a Dubai entity; Trump Jr. said only ~50 close friends attended.",
            "Kremlev's federation received tens of millions from Gazprom; Trump Jr. has said much real-estate investor money comes from Russia.",
            "Occam's razor exercise: are Trump's decisions mostly favorable to Russia and harmful to US democracy? He offers no proof, only the question.",
            "Mark Carney's Davos speech on middle powers; Canada was to address the European Parliament as the EU creates an associate status; Trump threatened tougher tariffs on countries forming the alliance. Canada's hydropower already feeds the US north.",
        ],
        "quote": None,
        "watch": "Hosts say they have no concrete evidence of Russian control and frame the Russia link as a thought experiment.",
        "names": None,
    },
    {
        "id": "ro-pnrr-politics",
        "tags": ["policy", "macro-rates", "romania"],
        "color": "red",
        "badge": "Structural critique",
        "status": "PNRR — 770M EUR LOST",
        "title": "Romania loses 770 million euros of PNRR money while politics churns",
        "lead": "A real loss went unprotested while attention was pulled to protests and a long-promised election report.",
        "bullets": [
            "Romania lost **770M euros** of PNRR funds; the political class acknowledged it publicly but no one took to the streets.",
            "Buhnici's list of what matters: administrative-territorial reform (too many bankrupt town halls), justice reform, deficit reduction and tax collection ('ANAF has the tools').",
            "President Nicusor Dan missed all six self-set dates to release the report on the 2024 election; his trust is down to about a quarter from 50% at his record-turnout win.",
            "Host speculates the tension suits those in power; polls reportedly put Calin Georgescu 8% ahead of Dan, so a rerun would likely pit Georgescu against 'anyone else'.",
            "He says the national-security laws and service heads Dan promised to change are untouched and asks why General Pahontu vanished from the news: 'the single party still controls this country'.",
            "A pensions story: reports that the pensions of ~2.5 million people shrank while the staff who ran the calculations got higher pay; the pension house president ended a reporter's call curtly.",
            "A Bacau commune (Margineni) used European-funded solar panels as a retaining wall against a landslide; Buhnici says that is misuse of funds, and a board would actually cost more than the panels.",
        ],
        "quote": {"text": "Partidul unic inca mai controleaza aceasta tara.", "cite": "— George Buhnici"},
        "watch": "Host labels most of this as speculation with low confidence and invites readers to disagree.",
        "names": None,
    },
    {
        "id": "ro-sheep-plague",
        "tags": ["policy", "health", "romania"],
        "color": "amber",
        "badge": "Contested",
        "status": "PPR OUTBREAK — LIVE SHEEP EXPORTS",
        "title": "The sheep farmers' protest and the plague that blocks live exports",
        "lead": "A hijacked protest hides a hard question: how to export animals that should be vaccinated and counted.",
        "bullets": [
            "Protest violence involved party members the farmers say they didn't know, some in monk costumes, with arrests including a self-styled 'Spartan for life' who threatened gendarmes on TikTok and was caught while driving for Uber.",
            "Cause: peste des petits ruminants (PPR) is present in Romania, which blocks live exports to the Middle East; vaccination requires counting every animal, and flocks aren't all counted or tagged.",
            "Farmers earn most from exports of live sheep, not from local meat and cheese; past export-ship disasters killed animals.",
            "Agriculture minister Florin Barbu says he would eat meat from a sick, unvaccinated sheep if tested before slaughter, and that exports could continue by a political decision; Buhnici says abattoir checks are sampling and show a logic gap.",
            "PPR isn't dangerous to humans but spreads to goats, deer and other ruminants; trucks are open and some vanish overnight.",
            "Shepherds average about 3,500-5,000 RON a month (Agrointeligenta), around €2,000 with milk and cheese in kind; he recommends Alex Dima's documentary on the Transylvanian transhumance route.",
        ],
        "quote": None,
        "watch": "The host speculates that farmers resist vaccination because flocks would be counted; hosts also cite an AI chat for the human-safety fact.",
        "names": None,
    },
    {
        "id": "starship-v3",
        "tags": ["space"],
        "color": "green",
        "badge": "Upcoming event",
        "status": "STARSHIP FLIGHT 14 — SEPTEMBER 22, 75-MINUTE WINDOW",
        "title": "Starship Flight 14 aims for orbit with 26 Starlink V3 satellites",
        "lead": "A successful orbital insertion turns Starlink into a launch-cadence story, not a technology one.",
        "bullets": [
            "Flight 14, after 13, targets the first orbital insertion and deploys **26 Starlink V3** satellites; the window is only 75 minutes.",
            "Each V3 weighs about a ton and a half, delivers 1 Tbps, and a single launch adds ~3% to network capacity, so ~30 launches double it.",
            "Falcon 9 flew its 80th Starlink mission of the year on September 5; SpaceX says Starlink from Florida now goes only on Starship.",
            "NASA's Nancy Grace Roman telescope burned only 18 kg of its 200 kg of fuel to reach its orbit, accurate to 99%, stretching life from about 10 to 22 years.",
            "A US general let slip that offensive weapons sit on a US satellite, which would breach key space treaties; he points to Tim Marshall's 'The Future of Geography'.",
        ],
        "quote": None,
        "watch": None,
        "names": [
            {"name": "SpaceX (SPCX)", "blurb": "Starship Flight 14 and Starlink V3 launch cadence.", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": None},
        ],
    },
    {
        "id": "fees-tips",
        "tags": ["consumer", "finance"],
        "color": "red",
        "badge": "Structural critique",
        "status": "HIDDEN FEES — RYANAIR 69-CENT CARD CHARGE",
        "title": "The price you see isn't the price you pay: Ryanair fees and US tipping defaults",
        "lead": "Checkout screens now add fees and tips where the only alternative is to cancel the purchase.",
        "bullets": [
            "Ryanair added a **69 cent** card-processing fee after 'buy', with only a cancel button; fares for the same Italian route moved from 21 to 24 to ~15.99 within hours.",
            "In the US tips start at 15% and rotating POS screens put 20-25% under the finger; an automatic 20% gratuity applies to parties over six.",
            "Berlin's IFA trip showed no tipping culture; he prefers cash tips and dislikes advance tips on delivery apps, where couriers seem less willing to climb stairs.",
        ],
        "quote": None,
        "watch": None,
        "names": None,
    },
    {
        "id": "gear-deals",
        "tags": ["consumer"],
        "color": "gray",
        "badge": "Recommendation",
        "status": "SONY XM4C — €250; XM5 DEALS NEAR €206",
        "title": "Sony's XM4C is a pricey refresh; XM5 deals make the choice",
        "lead": "At €250 the foldable XM4C looks worse than XM5 on sale, which may be Sony clearing stock.",
        "bullets": [
            "XM4C: €250, Bluetooth 6.0, LDAC, AAC, folding cups; multipoint doesn't work over LDAC; XM4 itself is still sold.",
            "XM5 sells around €206-210 incl. VAT on Amazon Prime Business, which is often cheaper than normal Prime; WF-1000XM5 ~€172; Prime Big Deal Days run October 6-7.",
            "Sony sells XM4, XM5 and XM6; XM6 is priced high on purpose to push the others; Black Friday could see XM4C at €179-199.",
            "Google's Googlebook line (Aluminium OS, from $999, 8 GB RAM) launches September 21; Apple lets Claude and ChatGPT extensions plug into Siri.",
            "Apple TV arrived in Romania at roughly half the US price; it has top resolution and bitrate, and a new iPhone buyer gets a trial of about three months.",
        ],
        "quote": None,
        "watch": "Several prices were read aloud from live pages and differ between speakers.",
        "names": [
            {"name": "Sony (SONY)", "blurb": "XM4C, XM5, XM6 headphone lineup; pricing segmented on purpose.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F6E1", "tag": "Security", "title": "Install the September 2026 Pixel security patch and update C200/C220 cameras now."},
    {"icon": "\U0001F4B3", "tag": "Fintech", "title": "Treat any email mentioning Revolut data requests as suspect and expect leaked KYC data to be abused."},
    {"icon": "\U0001F9E0", "tag": "AI costs", "title": "Move non-frontier work to Gemini or cheap open models (GLM 5.2, DeepSeek V4.1 Flash) before paying for Astra or Fable."},
    {"icon": "\U0001F6E0", "tag": "Infrastructure", "title": "Update old servers and put a cheap AI agent on watch for odd access."},
    {"icon": "\U0001F4F1", "tag": "Consumer", "title": "Skip the 18 Pro if you own a 17 and wait for Duo hands-on in October."},
    {"icon": "\U0001F9FE", "tag": "Consumer", "title": "Check the full checkout total before paying; a mandatory fee can appear after you click buy."},
]

HOT_TAKES = [
    {"take": "Afirmatiile extraordinare cer dovezi extraordinare. Arata-ne ceva.", "cite": "— George Buhnici", "why": "Challenges AI-lab doom claims."},
    {"take": "Toata povestea asta cu AI-ul care a scapat de sub control este o sperietoare care este facuta ca in Occident sa incetinim un pic chestia asta.", "cite": "— George Buhnici", "why": "Calls the AI-escape narrative a manufactured scare."},
    {"take": "Cine controleaza piata de hardware? Cei care fac subscriptiile.", "cite": "— George Buhnici", "why": "Links hardware and subscription price rises."},
    {"take": "Partidul unic inca mai controleaza aceasta tara.", "cite": "— George Buhnici", "why": "Strong claim about Romanian services."},
    {"take": "Prețul pe care il vezi nu e pretul pe care il platesti in prea multe locuri.", "cite": "— George Buhnici", "why": "Fee-creep generalisation."},
]

CLAIMS = [
    {"who": "George Buhnici", "claim": "iPhone Duo stock will be constrained in October because demand is very high.", "metric": "iPhone Duo availability", "target": "supply constraints", "by": "2026-10", "condition": None, "entity": "Apple (AAPL)"},
    {"who": "George Buhnici", "claim": "Starship Flight 14 reaches orbit for the first time and deploys 26 Starlink V3 satellites.", "metric": "Starship Flight 14", "target": "orbital insertion, 26 satellites", "by": "2026-09-22", "condition": None, "entity": "SpaceX (SPCX)"},
    {"who": "George Buhnici", "claim": "Google's Googlebook line with Aluminium OS launches from $999.", "metric": "Googlebook launch", "target": "from $999", "by": "2026-09-21", "condition": None, "entity": "Alphabet (GOOGL)"},
    {"who": "Diogo Almeida (cited by George Buhnici)", "claim": "A new parallel-inference method delivers real-time AI at 100x lower cost.", "metric": "AI inference cost", "target": "100x cheaper", "by": None, "condition": None, "entity": None},
    {"who": "George Buhnici", "claim": "Amazon Prime Big Deal Days run October 6-7 with lower Sony prices.", "metric": "Prime Big Deal Days", "target": "Sony XM5 near €206", "by": "2026-10-06", "condition": None, "entity": "Sony (SONY)"},
    {"who": "George Buhnici", "claim": "NASA's Nancy Grace Roman telescope now has fuel for about 22 years instead of 10.", "metric": "telescope fuel life", "target": "22 years", "by": None, "condition": None, "entity": None},
]

RELATIONS = [
    {"from": "Nvidia (NVDA)", "rel": "acquires", "to": "Hugging Face", "note": "stated in passing by the host"},
    {"from": "Samsung (005930.KS)", "rel": "supplies", "to": "Apple (AAPL)", "note": "foldable display for the Duo, per the host"},
    {"from": "Samsung (005930.KS)", "rel": "competes_with", "to": "Apple (AAPL)", "note": "Fold 8 versus Duo and rival ad campaign"},
]

OTHER_NEWS = [
    {"icon": "\U0001F4DA", "title": "Sources referenced: a Windows security explainer channel, Gamers Nexus (LG TV hack), Agrointeligenta (shepherd pay), Tim Marshall's 'The Future of Geography', Alex Dima's transhumance documentary, Android and Windows security bulletins, Hosterion (hosting).", "tag": "Sources"},
    {"icon": "\U0001F6A8", "title": "Security notices: update Pixels to September 2026 patches (modem flaw lets attackers take over with no click, 200+ fixes); update C200/C220 cameras; Windows 11's re-enabled Memory Integrity can cost 5-10% game performance on older PCs.", "tag": "Security"},
    {"icon": "\U0001F4F5", "title": "TikTok now requires login to watch, like Instagram; many countries plan Australia-style age/ID rules.", "tag": "Platforms"},
    {"icon": "\U0001F3AC", "title": "AI-made series: an AI-generated cartoon with continuity gets millions of views per episode; Gossip Goblin is turning into a film; 'story always wins'.", "tag": "AI media"},
    {"icon": "\U0001F697", "title": "Cars: new Hyundai Tucson looks squarer; new Dacia Spring is built in Slovenia on the Twingo platform; his Mercedes CLA test was the most efficient EV he tested this year, about €45k base and up to 60k+ well equipped.", "tag": "Autos"},
    {"icon": "\U0001F4FA", "title": "Watch and read: Apple TV shows (Severance, Foundation, Silo, Pluribus, Ted Lasso), the five-line film Motor City, Battlestar Galactica; Tim Marshall's book.", "tag": "Recommendations"},
    {"icon": "\U0001F916", "title": "Member content and robotics: he saw the Cybercab up close and rode a Cybertruck with FSD; a robotaxi test had a safety driver required by regulation; in India people film daily chores to train cleaning robots for low pay.", "tag": "Robotics"},
]

GLOSSARY = [
    {"term": "PNRR", "def": "Romania's National Recovery and Resilience Plan, the EU recovery-fund programme."},
    {"term": "PPR (peste des petits ruminants)", "def": "A viral disease of sheep and goats that blocks live-animal exports and doesn't infect people."},
    {"term": "ALPR", "def": "Automatic license-plate reader, a camera that logs plates and can be queried by police."},
    {"term": "KYC", "def": "Know-your-customer identity checks, which for fintechs often involve selfie videos and ID scans."},
    {"term": "Memory Integrity", "def": "A Windows security feature that verifies code loaded into memory, at a cost in gaming performance."},
]
