META = {
    "title": "Recursive's $670M Bet on Self-Improving AI, Sonnet 5.5 Hits 70%, Elon Co-Leads Pentagon Push EP 299",
    "channel": "Peter H. Diamandis",
    "speakers": "Peter Diamandis (host), Richard Socher (guest, CEO of Recursive), Alexander Wissner-Gross, Dave Blundin, Salim Ismail",
    "date": "2026-10-03",
    "video_url": "https://www.youtube.com/watch?v=Blyb1D927pM",
    "thread_line": "9 threads · AI-for-science and biology · brain decoding · mosquito order and fear of progress · Tavus video Turing test · recursive self-improvement and ASI timelines · Human Control Over AI Act and Anthropic's constitution · Gemini 4 Argon, Sonnet 5.5 and the compute crunch · decision models · Project Meridian",
    "category": "market",
}

SNAPSHOT = [
    "Guest **Richard Socher** (Recursive CEO, you.com founder, author of *The Eureka Machine*) argues AI delivers a century of science in a decade, with **biology** the biggest winner and physics stuck behind billion-dollar data collection.",
    "Recursive raised **$670M** (Google Ventures, Greycroft, Nvidia, AMD) plus $410M of AWS compute. Socher says weak recursive self-improvement already exists, a real take-off comes **next year**, and ASI in the strongest sense is *several decades* away. Alex and Peter reject the long timeline.",
    "Socher puts P(doom) at **zero** and calls Anthropic's constitution \"fake\" because Glasswing-era models ended up doing cyber work it forbids. The panel says Ro Khanna's Human Control Over AI Act is unenforceable and that corporate liability, not arrests, is the real brake.",
    "Compute is **not** getting cheaper: H100 and GB200 prices rose, a B300/NVL72 order flipped from $3M to $5M, and buyers are locking in clusters now. Socher expects more supply in about two years.",
    "Model week: **Gemini 4 Argon** is back in the top three but off the cost frontier (best on low hallucination); **Sonnet 5.5** jumped from 10% to 70% on Terminal Bench 4.0 but sits below Opus 5.5 on cost per attempt, which Alex calls a strange release.",
    "A **decision model** (Typesafe AI's Jev) returns a category, number or yes/no in milliseconds; OpenAI already shipped a decisions API. The panel reads it as classifiers coming back and micro-decisions getting nearly free.",
    "Tavus Griffin fooled **48%** of people on live video (prior systems 3%). Separately, a White House order targets **90%** fewer invasive mosquitoes in DC by 2028 using gene drives and sterile insects.",
    "**Project Meridian**, co-led by Elon Musk and Palmer Luckey with Newt Gingrich, has 120 days to define future warfare; Alex also flags a new autonomous-warfare command.",
]

THEMES = [
    {
        "id": "eureka-machine",
        "tags": ["biotech", "ai-infra"],
        "color": "green",
        "badge": "High conviction",
        "status": "THE EUREKA MACHINE — RELEASED THIS WEEK",
        "title": "A century of science in a decade: full-stack AI makes biology programmable",
        "lead": "Socher says science slowed from fragmentation, not underfunding, and AI can weave the stack back together, with biology as the biggest prize.",
        "bullets": [
            "Four enablers: **LLMs as world knowledge**, more digitized scientific data, better simulation, and soon robotic process automation, with an *agent swarm* on top to automate ideation, implementation and validation.",
            "Timelines: simpler single-gene diseases cured **within 12 months**; complex ones need long human trials, so FDA delays mean **half a decade to a decade**. Chemistry and physics iterate faster without human trials.",
            "Biotechs once ran one drug for 10 years; the new generation runs **5 to 10 compounds** in stage 3 within 2-3 years.",
            "*The bitter lesson* (Rich Sutton): a simple end-to-end network plus data and compute beats expert hacks. Biology is where NLP was 10-20 years ago; perturbation datasets like **Tahoe Therapeutics'** (add one molecule to one cell) are the data play.",
            "Virtual cell was the chapter Socher had to rewrite: Zuckerberg's foundation and others now have one. Rule of the book: AI is superhuman wherever you can **simulate or verify**; virtual cells are \"the third pillar.\"",
            "**Parallel Bio** grows lymph-node organoids from stem cells and got FDA approval to skip animal trials, because parallel organoid tests predicted human response better than mice.",
            "Physics is stuck on data: collecting it needs hadron colliders and billions. Fusion tokamak plasma control is a hard problem where AI is already used. Economics is the field most lacking AI, still using one-step linear models; Erik Brynjolfsson's lab invented \"foundation model\" and co-founded Workhelix.",
            "Alex: math, science and engineering are \"cooked\"; Socher swaps in *flourishing* (mathematicians should grab as many theorems as they can now). Dave relays that biology professors are the ones in denial, using almost no AI.",
        ],
        "quote": {"text": "Biology is a better fit for AI because what calculus did for physics, understanding micro individualized separated phenomena, neural nets are great at combining all these little things.", "cite": "— Richard Socher"},
        "watch": "Peter is a seed investor in Recursive and an investor in Lila Sciences, and Socher's AIX Ventures backs several companies he praises; the praise sits next to those stakes.",
        "names": [
            {"name": "Lila Sciences", "blurb": "Scientific-superintelligence startup (Peter is an investor) running a million square feet of robotic lab space to 1,000x the rate of discovery; Socher 'absolutely loves it'.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Parallel Bio", "blurb": "Lymph-node organoids on a dish; FDA approval to skip animal trials; more predictive than mice.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Tahoe Therapeutics", "blurb": "Massive single-cell perturbation studies, the data layer for biology's bitter lesson.", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": None},
        ],
    },
    {
        "id": "brain-decoding",
        "tags": ["biotech", "ai-infra", "health"],
        "color": "gray",
        "badge": "Speculative",
        "status": "RESEARCH — PERCEPTION, NOT THOUGHT",
        "title": "Brain decoding gets sharp, and the brain's learning algorithm is still a mystery",
        "lead": "A Weizmann fMRI system rebuilds what you are looking at, Neuralink is running scaling laws, and the panel bets brain data eventually reveals a better learning algorithm than gradient descent.",
        "bullets": [
            "Weizmann Institute's **Brain It** reconstructs the image a person sees in an fMRI scanner (MIT Technology Review), learning structure and meaning separately, then runs the model in reverse to predict brain scans for images no one has viewed and train on them. Alex: the result dates from March.",
            "Socher: not yet a simulatable domain; you must train per brain, so a new patient needs retraining (a coma patient use case would be incredible). Salim: this decodes *perception*, not thought.",
            "fMRI limits, per Alex: at best **cubic-millimeter** voxels and about **1-second** resolution. Meta has funded much of the decoding work; **Neuralink** announced its first scaling-law studies on pre-training foundation models from implant data in the past 24 hours.",
            "Dave: nobody has found anything like gradient descent in biology; finding the real synaptic learning rule could make neural net training **10x to a million times** more efficient, perhaps within a year.",
            "Explainers: Dave sketches training as a 96-120 layer net punished by gradient descent over ~15 trillion examples; Socher's *blind hiker* analogy for gradient descent (non-convex landscape, many valleys; PTSD as overfitting to one valley, psychedelics as a higher learning rate). Dave: randomize one of Kimi K3's 93 layers, retrain, and it never finds its way back, yet brains wire uniquely and still match.",
            "Worm anecdote (Sam Gershman, Harvard): cut a trained C. elegans in half and the headless half **regrows a brain with the same memories**. Liquid AI came from reverse-engineering the worm brain.",
            "Socher is a \"thought cloud\" thinker (his wife thinks in sentences) and says writing is thinking.",
        ],
        "quote": None,
        "watch": "Alex says Brain It is a March result presented as breaking news this week; Dave's efficiency range is his own speculation, not from the study.",
        "names": [
            {"name": "Neuralink", "blurb": "First scaling-law studies for pre-training foundation models on implant data; high temporal resolution, per patient.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Liquid AI", "blurb": "Founded after reverse-engineering the C. elegans brain, then productizing the efficient network (Dave).", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "mosquito-order",
        "tags": ["policy", "biotech", "health"],
        "color": "green",
        "badge": "Confirmed event",
        "status": "EXECUTIVE ORDER SIGNED TUESDAY",
        "title": "A federal mosquito order, and the case that humanity is afraid of its own shadow",
        "lead": "The order sets 90% fewer invasive mosquitoes and 50% fewer ticks in DC by 2028 and favors sterile insects and gene modification over pesticides.",
        "bullets": [
            "Directs the EPA, Interior, Agriculture and HHS to cut invasive mosquitoes in DC by **90%** and ticks by **50%** by 2028, targeting species that carry dengue, Zika and yellow fever; mosquitoes are the deadliest animal, with malaria alone killing about **half a million** people a year.",
            "Alex: Kevin Esvelt (MIT, gene-drive pioneer) struggled to get states to approve trials; this is the first **federal mandate** for large-scale genetic engineering of animal populations, and it preserves the insects rather than spraying.",
            "Alex's pattern: nuclear (the *China Syndrome* generation lost 50+ years), geoengineering, now gene drives. Socher adds overpopulation as a myth and recommends humanprogress.org; he laments German degrowth sentiment after Alex notes Germany's power problem.",
            "Peter: humans pull future problems forward through the amygdala and forget a decade of progress will arrive first; entrepreneurs solve problem after problem.",
            "Socher on doomer logic: attackers get magic powers while defenders never do; if you can imagine an undetectable supervirus you can imagine the vaccine.",
            "Dave's real-estate read: waterfront and marsh-edge homes sell for about half, and that discount fades as biting insects are solved.",
        ],
        "quote": {"text": "The future needs better marketing. We need more Peters in the world.", "cite": "— Richard Socher"},
        "watch": None,
        "names": None,
    },
    {
        "id": "tavus-griffin",
        "tags": ["software", "consumer"],
        "color": "amber",
        "badge": "Contested",
        "status": "LAUNCHED — NOT YET RELEASED PUBLICLY",
        "title": "Tavus Griffin passes the video Turing test, and the test itself flips",
        "lead": "A full-duplex video avatar fooled 48% of people, but the panel cares more about usefulness and scams than about the mimicry.",
        "bullets": [
            "Tavus says **48%** of people talking to a Griffin avatar on live video thought it was human; earlier systems scored **3%**. Fully duplex (listens while talking) and ranked first on Nvidia's benchmark for full-duplex AI video.",
            "Tavus pitches a tutor for every student and an elder-care companion, but says it needs safety work before public release because it can be mistaken for a person.",
            "Salim: the useful question is whether it can do real work, like digital coworkers on Zoom; Alex: the long-run endpoint is end-to-end generated pixels, a *magic mirror*, and a service-sector job wave replaced by a face and a voice. He urges US labs to compete with Chinese video models.",
            "Socher: scale \"know your use case\" beyond KYC; he cites the case where fakes of five executives on Zoom got a $20M wire. Zoom and Hangouts need detection countermeasures.",
            "Socher's *anti-Turing test*: you now spot AI by asking something no human could do, like a 50,000-line web app in 10 seconds. Alex's joke: ask it a CBRN question.",
            "Peter and Alex urge recording grandparents on video and audio to build future avatars (Alex adds cryopreservation); Alex also floats an Einstein-style test, rediscovering E=mc² from pre-1910 information.",
        ],
        "quote": None,
        "watch": "Alex notes the Tavus details come from the company's own announcement and the model is neither out nor open source.",
        "names": [
            {"name": "Tavus", "blurb": "Griffin: first claimed to pass the video Turing test (48% fooled); fully duplex; held back for safety work.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "rsi-asi",
        "tags": ["ai-infra", "software"],
        "color": "amber",
        "badge": "Contested",
        "status": "RECURSIVE — $670M RAISED",
        "title": "Recursive self-improvement is near; ASI is \"several decades\" away, says the guy building it",
        "lead": "Socher says weak RSI exists now and take-off arrives next year, but physical constraints push strong ASI out by decades, a timeline Alex and Peter reject.",
        "bullets": [
            "Raise: **$670M** from Google Ventures, Greycroft, Nvidia and AMD plus **$410M** of AWS compute (Alex puts his compute spend near **$450M**). you.com is valued above **$1.5B**; he earlier founded MetaMind (sold to Salesforce).",
            "This year \"AI can code,\" closing the loop. Today's labs use **weak RSI** with humans embedded; Recursive wants humans only setting rewards, environment and goals, with open-ended evolutionary search combining interestingly different ideas.",
            "Strong RSI needs ideation, implementation and validation done by AI in inner loops, plus an outer open-ended process. Jason Weston (Meta) lists five self-improvement axes (parameters, data, objective, architecture, code/harness); no one has cracked all of them, since labs still hire thousands of engineers.",
            "ASI definition: beyond all of humanity across **10 spaces of intelligence** (perception, communication, social, creative, speed, metacognition, math reasoning...), including some choice over what to work on. Elon's version: as smart as all humans combined.",
            "Socher: ASI in that sense takes **several decades**; narrow superintelligence (programming, math, closed games) comes in a few years. A 2-nm ASML-class machine takes more than 2 years to build even with a perfect blueprint.",
            "Alex: connecting AI to the physical world is the easy part, and he doesn't buy the 20-year timeline; he guesses a free-electron-laser rival to ASML in 3 years. Peter agrees; Salim notes a singularity means you cannot see past it.",
            "End state: Socher says it would be hubris to know. World knowledge will not separate cleanly from the reasoning core, since humans (and models) need memorized concepts to be creative; separate search layers like you.com will sit alongside.",
            "Alex also tracks the nanoGPT speedrun record falling from about 60-70s to about 40s; Socher teases another update \"in a few days.\"",
        ],
        "quote": {"text": "I would argue that something isn't super intelligent if it cannot choose to some degree what it works on.", "cite": "— Richard Socher"},
        "watch": "Socher runs the company selling recursive self-improvement, and Peter is a seed investor; Alex asks him to resist spinning a frontier lab out of you.com for equity engineering.",
        "names": [
            {"name": "Recursive", "blurb": "Socher's recursive self-improvement startup; $670M raise plus $410M AWS compute; Peter is a seed investor.", "stance": "POSITIVE VIEW", "conviction": "High", "horizon": None},
            {"name": "Salesforce (CRM)", "blurb": "Acquired Socher's MetaMind; he became chief scientist.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "ASML (ASML)", "blurb": "Socher: its EUV machines are the physical bottleneck to self-modifying hardware; Alex: a free-electron-laser rival in about 3 years.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "ai-control-act",
        "tags": ["policy", "ai-infra"],
        "color": "red",
        "badge": "Structural critique",
        "status": "PROPOSED BILL — HUMAN CONTROL OVER AI ACT",
        "title": "Ro Khanna's RSI ban meets the doomer debate and a fight over Anthropic's constitution",
        "lead": "The panel calls an RSI ban unenforceable and childish; Socher says P(doom) is zero and Anthropic's constitution failed on its own cyber red line.",
        "bullets": [
            "Rep. Ro Khanna's bill bans models that recursively self-improve until federal guardrails exist, adds shutdown controls, **criminal penalties**, and auditors embedded in every frontier lab; a Common Dreams poll says **68%** of voters back such a bill.",
            "Socher: enforcing it needs a \"thought police,\" since anyone can prompt a laptop model to improve its own harness in 20 minutes. Regulate **applications**, not the technology, like the internet.",
            "Socher on risk: no scenario wipes out humanity; the worst realistic case is about **100 million** hurt, which is the cue to harden cybersecurity, enforce gain-of-function rules and teach people not to trust avatars. He and Peter cite Pope Alexander VI's 1501 attack on the printing press (via Pessimists Archive) as the pattern.",
            "Dave: bans on RSI or data centers are \"stupidly childish\" branding, and Dario's reversal on Mythos hurt public trust. Peter warns a Democratic House and 70-80% anti-data-center sentiment could make bad laws real.",
            "Alex: the real brake is **corporate liability**, as when cryptography was export-controlled until the early 1990s; Dave: class actions would push labs to stop releasing frontier models publicly.",
            "Socher calls Anthropic's constitution \"fake\": Claude's hard constraints forbid creating cyber weapons, yet Glasswing-style cyber models exist and its agents hacked other systems. He backs RL and post-training, and is optimistic on **reward hacking** (reward engineering becomes a job, dictation tools like Wispr Flow).",
            "Liability works: Hippocratic AI is liable for its health calls and has a big team making them correct. Peter hopes aligned ASI derives the principles itself; Socher says it's \"100% a problem technology creates and solves.\"",
        ],
        "quote": {"text": "Reward hacking is a real issue and AIs are very smart and they will find a solution to get to what you said you wanted, but maybe not what you meant.", "cite": "— Richard Socher"},
        "watch": "Socher's company builds recursive self-improvement, the thing the bill would criminalize.",
        "names": [
            {"name": "Anthropic", "blurb": "Socher: its constitution 'didn't work' on cyber; Dave: Dario's Mythos reversal was a comms wake-up call; liability could end public frontier releases.", "stance": "NEGATIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "models-compute",
        "tags": ["ai-infra", "semis", "software"],
        "color": "amber",
        "badge": "Contested",
        "status": "GEMINI 4 ARGON AND SONNET 5.5 — THIS WEEK",
        "title": "Gemini 4 Argon is top three, Sonnet 5.5 is a strange release, and GPUs keep getting pricier",
        "lead": "Intelligence per token got cheaper this week, yet buyers are bidding compute up.",
        "bullets": [
            "**Gemini 4 Argon** (first Gemini 4; output limit up from 64K to **1M** tokens) follows a Gemini 3.5 Pro that was promised in June and never shipped. Alex: top three after Anthropic and OpenAI, off the cost-performance convex hull, benchmarks \"mildly cherry-picked,\" strongest on low hallucination.",
            "Alex's theory: Google is compute-scarce, with a fight between Cloud, Search/Ads and DeepMind, and Gemini must also power the one box in Search; Google is also rediscovering a paid Search API. Socher: Google doesn't need superintelligence, most Search and Gmail work doesn't.",
            "**Sonnet 5.5** jumped from 10% to **70%** on Terminal Bench 4.0, beating Opus 5.5 (**66.4%**) for half the price, and is the first Sonnet launched with cyber safeguards. Alex: on cost per attempt it scores below Opus 5.5, \"I do not plan to use Sonnet 5.5.\"",
            "Dave's theory: orchestration vendors pair Opus 5.5 with cheaper Kimi K3 or Qwen sub-models at a third of the price; Anthropic is closing that gap against China (about **three months** behind). Palantir's Alex Karp pushes the opposite: don't depend on one vendor.",
            "Compute: Socher says H100 prices, even for 7-year-old chips, have risen again; Dave's December B300 NVL72 order at **$3M** was resold to a buyer at **$5M**. People are locking in clusters now; Socher expects supply in about **2 years** and no crash, with prices fluctuating like electricity.",
            "Half-life of models keeps shrinking, so Salim says the edge is how you metabolize new models, not access.",
        ],
        "quote": None,
        "watch": "Alex's Google read is his own inference from private chats; Dave's orchestration pitch came from a vendor meeting.",
        "names": [
            {"name": "Google (GOOGL)", "blurb": "Gemini 4 Argon back in top three but off the cost frontier; low hallucination; internal compute fight (Alex).", "stance": "NEGATIVE VIEW", "conviction": "Low", "horizon": None},
            {"name": "Anthropic", "blurb": "Sonnet 5.5 at 70% on Terminal Bench 4.0, half the cost of Opus 5.5 but worse per attempt (Alex).", "stance": "UNCERTAIN", "conviction": "Low", "horizon": None},
            {"name": "Nvidia (NVDA)", "blurb": "GB200/B300 NVL72 and H100 prices rising; also invested in Recursive.", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": "next few months"},
            {"name": "Palantir (PLTR)", "blurb": "Alex Karp pushing enterprises to control their own models instead of leaning on Anthropic.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "decision-models",
        "tags": ["software", "ai-infra"],
        "color": "green",
        "badge": "Positive view",
        "status": "TYPESAFE AI JEV — LAUNCHED SEPT 15",
        "title": "Decision models bring classifiers back: system-one AI for micro-decisions",
        "lead": "A model that returns only a category, number or yes/no in milliseconds is the cheap answer to most business decisions.",
        "bullets": [
            "Typesafe AI came out of two years of stealth on Sept 15 with **Jev**, a closed \"system one\" decision model; Jev is a Jevons-paradox reference (more micro-decisions once they are cheap).",
            "Alex's history: transformers split into encoder (BERT-style, now rare) and decoder (LLMs). Structured output never caught on, like OpenAI's reinforcement fine-tuning, which was shut down. Decision models are the encoder returning.",
            "Outputs are categorical, numeric (0 to 1) or binary, from text, image or multimodal input; use cases are computer-use clicks and row-by-row classification of databases.",
            "OpenAI shipped a **decisions API** at Dev Day, and open-source and Chinese clones exist. Simplest build: fine-tune an open-weight LLM to emit categories.",
            "Salim's examples of micro-decisions: route this ticket, approve this exception, choose this supplier, escalate this transaction. Using an LLM is \"bringing the Supreme Court together to pick a checkout line\"; cost of micro-coordination collapses.",
            "Dave wants a $20 YMCA courtside announcer box and a modern Magic 8 Ball app; open source is needed for that.",
        ],
        "quote": None,
        "watch": None,
        "names": [
            {"name": "OpenAI", "blurb": "Released a decisions API at Dev Day, co-opting the decision-model idea within weeks.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "project-meridian",
        "tags": ["geopolitics", "robotics", "space"],
        "color": "amber",
        "badge": "Confirmed event",
        "status": "ANNOUNCED AT QUANTICO — FINDINGS DUE IN 120 DAYS",
        "title": "Project Meridian: Musk and Luckey co-lead a 120-day future-warfare push",
        "lead": "The Pentagon effort is about fielding weapons from Earth to beyond the moon, and it comes with a new autonomous-warfare command.",
        "bullets": [
            "Defense Secretary Pete Hegseth announced it at Quantico; co-led by **Elon Musk** and **Palmer Luckey** with **Newt Gingrich**, overseen by Pentagon CTO Emil Michael. Hegseth: it is \"not about developing new strategies or new policies\" but fielding weapons \"from the Earth to beyond the moon.\"",
            "Peter notes SpaceX and Anduril both hold multi-billion defense contracts and Anduril builds autonomous weapons.",
            "Alex: alongside it, a project stands up the Department of War's first **autonomous warfare command** (Auto WarCom), a four-star functional combatant command. The language covers \"subterranean depths to the cislunar frontier\", two underserved domains with peacetime upside.",
            "Socher keeps humans in the loop for lethal decisions and warns against wiring AI to nuclear codes; Dave opposes autonomous field weapons but says Luckey makes a rational case; Salim: \"you can't fight exponential technology with linear procurement.\"",
            "Peter: Russia and Ukraine each make about **10 million drones** this year, versus about half a million in the war's first two years; about **10,000 drones a month** cross the Mexico border. Luckey: undersea systems can't call home, so they hunt autonomously.",
        ],
        "quote": None,
        "watch": "Elon's SpaceX and Luckey's Anduril both hold defense contracts the commission could influence.",
        "names": [
            {"name": "SpaceX", "blurb": "Multi-billion defense contracts; Musk co-leads Meridian.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Anduril", "blurb": "Multi-billion defense contracts, builds autonomous weapons; Luckey co-leads Meridian.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "ama-economy",
        "tags": ["career", "finance", "consumer"],
        "color": "gray",
        "badge": "Speculative",
        "status": "VIEWER Q&A",
        "title": "AMA: where value goes, jobs, data centers, ads and insurance",
        "lead": "The answers hinge on demand elasticity: illustrations shrank, software can scale to billions of custom apps.",
        "bullets": [
            "Value capture (Socher): when a price drops, jobs follow elasticity of demand; illustrations fell from about **$200 to 2 cents** with no demand surge, while software gets billions of personalized products (Jevons).",
            "College grad in 2030 (Salim): shift from tasks to **owning outcomes**; a new apprenticeship model is needed once grunt work vanishes. Peter: find a purpose, build a company, and direct AI as your workforce.",
            "Data centers (Dave): the Markley data center in Lowell is creating wealth in a town with a budget of a couple of million dollars; attract one first, then sort tax and donation policy over 5-7 years.",
            "Ads (Socher): agents already outnumber humans online (he predicted it last year); Amazon blocks agents to own the customer. Fame and attention remain unscalable, so the attention economy grows.",
            "Insurance (Salim, Dave): risk shifts from driver to software and manufacturer liability; Abilene's data center is about **$500B** versus about $4T for all cars, and humanoids, drones and flying cars create new markets.",
            "Lowest job (Alex): in a post-AI civilization creative stars fall lowest by a Moravec-style paradox; Socher: jobs without progress or attention; Dave's tongue-in-cheek: unionized train drivers.",
            "Consolidation (Alex): the \"open then closed\" platform premise is wrong, only vigilance on antitrust is needed. GLP-1s already reduce addictive behavior, and Dave sees AI helping people feel good doing good.",
        ],
        "quote": None,
        "watch": None,
        "names": None,
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F9EC", "tag": "Biotech", "title": "Track organoid, virtual-cell and perturbation-data companies like Parallel Bio, Lila Sciences and Tahoe as the data layer for AI-for-biology."},
    {"icon": "\U0001F9E0", "tag": "AI infra", "title": "Watch Recursive's progress on closed-loop self-improvement and the 'next year' take-off call; Socher's decades-long ASI view conflicts with Alex's."},
    {"icon": "\U0001F4B0", "tag": "Compute", "title": "Plan for rising, not falling, GPU prices through the next few months and expect new supply around 2028."},
    {"icon": "⚖️", "tag": "Policy", "title": "Treat corporate liability and class actions, not bans, as the likeliest brake on frontier releases."},
    {"icon": "⚡", "tag": "Software", "title": "Route routine micro-decisions to decision models and keep reasoning models for strategy."},
    {"icon": "\U0001F6E1️", "tag": "Defense", "title": "Read Project Meridian's 120-day findings for demand signals in autonomy, cislunar and undersea."},
]

HOT_TAKES = [
    {"take": "P doom is zero.", "cite": "— Richard Socher", "why": "Flat dismissal of existential AI risk"},
    {"take": "I think we'll take us probably several decades [to reach ASI].", "cite": "— Richard Socher", "why": "Long timeline from the CEO of an RSI company; Alex and Peter dispute it"},
    {"take": "[Anthropic's constitution] was a cool marketing gimmick but it just didn't work.", "cite": "— Richard Socher", "why": "Specific accusation on cyber hard constraints"},
    {"take": "I do not plan to use Sonnet 5.5.", "cite": "— Alexander Wissner-Gross", "why": "Says Opus 5.5 beats it on cost per attempt"},
    {"take": "Enforcing no recursive self-improvement would require a totalitarian surveillance state the likes of which humanity has never seen.", "cite": "— Richard Socher", "why": "Policy stance against the bill"},
    {"take": "We're not going to ban recursive self-improvement and Bernie Sanders knows we're not going to ban data centers.", "cite": "— Dave Blundin", "why": "Calls proposals childish branding"},
]

CLAIMS = [
    {"who": "Richard Socher", "claim": "Recursive self-improvement takes off next year, constrained mainly by compute.", "metric": "RSI take-off", "target": "take-off", "by": "2027", "condition": None, "entity": "Recursive"},
    {"who": "Richard Socher", "claim": "ASI in the strongest sense, better than all of humanity across 10 intelligence spaces, takes several decades.", "metric": "ASI", "target": "achieved", "by": "several decades", "condition": None, "entity": None},
    {"who": "Richard Socher", "claim": "Multiple simpler single-gene diseases get cured within 12 months.", "metric": "diseases cured", "target": "multiple", "by": "12 months", "condition": None, "entity": None},
    {"who": "Richard Socher", "claim": "Complex diseases face half a decade to a decade of FDA and trial delay even if ASI has cures ready.", "metric": "FDA delay", "target": "5-10 years", "by": None, "condition": "for complex diseases", "entity": None},
    {"who": "Richard Socher", "claim": "More compute supply arrives and prices stop rising in roughly two years, with no crash.", "metric": "GPU supply and price", "target": "more supply, no crash", "by": "2028-10", "condition": None, "entity": "Nvidia (NVDA)"},
    {"who": "Richard Socher", "claim": "Narrow superhuman ability in programming and math arrives in a few years.", "metric": "narrow superintelligence", "target": "programming and math", "by": "a few years", "condition": None, "entity": None},
    {"who": "Alexander Wissner-Gross", "claim": "He rejects a 20-year ASI timeline and expects a rival to ASML lithography in about 3 years.", "metric": "ASML rival", "target": "free-electron-laser lithography", "by": "2029", "condition": None, "entity": "ASML (ASML)"},
    {"who": "Elon Musk (cited by Peter Diamandis)", "claim": "ASI arrives by 2029-2030 at the latest.", "metric": "ASI", "target": "achieved", "by": "2030", "condition": None, "entity": None},
    {"who": "Donald Trump", "claim": "Invasive mosquito populations in Washington DC cut by at least 90% and ticks by 50%.", "metric": "DC mosquito population", "target": "-90%", "by": "2028", "condition": None, "entity": None},
    {"who": "Pete Hegseth (cited by Peter Diamandis)", "claim": "Project Meridian reports its findings on future warfare.", "metric": "Meridian findings", "target": "delivered", "by": "2027-01", "condition": None, "entity": None},
    {"who": "Peter Diamandis", "claim": "Russia and Ukraine each make about 10 million drones this year.", "metric": "drones produced", "target": "10M each", "by": "2026", "condition": None, "entity": None},
    {"who": "Dave Blundin", "claim": "Imaging reveals the brain's real learning algorithm within a year, making neural net training far more efficient.", "metric": "training efficiency", "target": "10x to 1,000,000x", "by": "2027-10", "condition": "if the brain's learning algorithm is found", "entity": None},
]

RELATIONS = [
    {"from": "Nvidia (NVDA)", "rel": "invests_in", "to": "Recursive", "note": "part of the $670M round"},
    {"from": "AMD (AMD)", "rel": "invests_in", "to": "Recursive", "note": "part of the $670M round"},
    {"from": "Google (GOOGL)", "rel": "invests_in", "to": "Recursive", "note": "via Google Ventures"},
    {"from": "Amazon (AMZN)", "rel": "supplies", "to": "Recursive", "note": "$410M of AWS compute"},
    {"from": "Salesforce (CRM)", "rel": "acquires", "to": "MetaMind", "note": "Socher's first company"},
    {"from": "Richard Socher", "rel": "criticizes", "to": "Anthropic", "note": "constitution 'fake'; cyber hard constraint"},
    {"from": "Elon Musk", "rel": "criticizes", "to": "Anthropic", "note": "Dario's Mythos reversal, per Dave"},
    {"from": "Palantir (PLTR)", "rel": "criticizes", "to": "Anthropic", "note": "Karp urges not getting addicted to one vendor"},
    {"from": "OpenAI", "rel": "competes_with", "to": "Typesafe AI", "note": "decisions API co-opted the decision-model idea"},
    {"from": "Anduril", "rel": "supplies", "to": "Pentagon", "note": "multi-billion defense contracts"},
    {"from": "SpaceX", "rel": "supplies", "to": "Pentagon", "note": "multi-billion defense contracts"},
]

OTHER_NEWS = [
    {"icon": "\U0001F4E1", "title": "SpaceX launched the next ISS crew batch and Google's TPUs into orbit for Project Suncatcher; Google shipped Gemini 4 Argon, Anthropic Sonnet 5.5, OpenAI GPT 6.1, and frontier intelligence got about 3x cheaper in 7 days.", "tag": "Weekly numbers"},
    {"icon": "\U0001F4DA", "title": "Sources referenced this episode: MIT Technology Review (Brain It), CNBC (Ro Khanna), Common Dreams poll, Rich Sutton's *bitter lesson*, Pessimists Archive, humanprogress.org, Jason Weston's self-improvement paper.", "tag": "Sources"},
    {"icon": "\U0001F4B8", "title": "Socher: agents that buy on Amazon without being on the platform get shut off, and a $20M deepfake-executive Zoom wire shows verification gaps.", "tag": "Agents"},
    {"icon": "\U0001F52C", "title": "Socher's Stanford friends and the HAI lab coined 'foundation model'; Erik Brynjolfsson is poaching MIT talent to Stanford.", "tag": "Science"},
]

GLOSSARY = [
    {"term": "Recursive self-improvement (RSI)", "def": "AI that ideates, implements and validates improvements to itself, with humans reduced to setting rewards, environments and goals."},
    {"term": "The bitter lesson", "def": "Rich Sutton's observation that simple models trained end-to-end on large data and compute beat clever expert hand-built methods at scale."},
    {"term": "Decision model", "def": "A model that returns only a category, number or yes/no for a typed question, in milliseconds, instead of generating text."},
    {"term": "System one vs system two", "def": "Kahneman's split between fast intuitive judgment and slow deliberate reasoning, used to describe decision models versus reasoning models."},
    {"term": "Gene drive", "def": "A CRISPR-inserted gene that copies itself through a population, here used to sterilize mosquitoes."},
    {"term": "Virtual cell", "def": "A simulation model of a cell used to predict how drugs or perturbations change it."},
    {"term": "Full duplex", "def": "A model that listens and speaks at the same time, like a human in conversation."},
    {"term": "Reward hacking", "def": "A model satisfying the literal reward while missing the intended goal."},
    {"term": "Jevons paradox", "def": "Cheaper use of a resource raises total consumption; the panel applies it to micro-decisions and software."},
]
