META = {
    "title": "AI researchers debate how close we are to recursive self-improvement",
    "channel": "Dwarkesh Patel",
    "speakers": "Dwarkesh Patel (host), Beren Millidge (Zyphra), John Schulman (Thinking Machines), Charlie O'Neill (Baseten)",
    "date": "2026-09-11",
    "video_url": "https://www.youtu.be/PrSf7IOYu-I",
    "thread_line": "7 threads · why takeoff might stall · distillation vs centralization · training the first AI researcher · learning from deployment · data and scaling · why RL works · timelines",
    "category": "market",
    "region": "",
}

SNAPSHOT = [
    "Three open-lab AI researchers debate the most likely technical reason **no superintelligence arrives by 2036**: persistent bottlenecks, an asymptote, or regulation — not a missing paradigm per se.",
    "Consensus: with a well-specified objective, AI can speed research roughly **10x**; it does not obviously supply the *right objective* or open-ended paradigm shifts.",
    "Distillation is the main force against centralization — Chinese labs reportedly get realistic prompt distributions via proxy services reselling US-model coding traffic.",
    "Labs' bet: scale RL across millions of environments (coding, then finance, Excel, slides); the first AI-R&D automator will be trained on researcher feedback plus environments built from recent bugs.",
    "Learning from deployment already happens slowly (Cursor Composer, Harvey); true weight-level continual learning hits catastrophic forgetting, so modules/cartridges likely come first.",
    "Data explains more pre-training efficiency than architecture in one small-scale study (~9x vs ~3x); frontier active parameters stay at roughly 100-200B for a few years.",
    "Timelines (panel, not individually attributed in captions): general remote worker in ~1-3 years, 10x AI-researcher productivity in ~2, full cognitive parity in ~3-5, with a long tail of physical and low-data fields.",
]

THEMES = [
    {
        "id": "no-takeoff",
        "tags": ["ai-infra", "policy"],
        "color": "amber",
        "badge": "Contested",
        "status": "THE 2036 'WHY NOT' QUESTION",
        "title": "What would stop a takeoff: a Moravec-style gap, an asymptote, or regulation",
        "lead": "The panel's likeliest 'nothing dramatic happened by 2036' world is AI that dominates benchmarks but stalls on bottlenecks, not a hard wall.",
        "bullets": [
            "Moravec's-paradox scenario: AI excels at everything in a benchmark or environment while a sim-to-reality gap blocks real impact; one panelist finds it unlikely, citing generalization already seen.",
            "Hype cycle: each new model feels like AGI, then looks silly after about a month — and it is unclear how many more times that repeats.",
            "Today a model writes far more code than a person yet doesn't make a team 100x more productive; judgment and self-checking remain bottlenecks.",
            "The bull case: an agent even 0.1% better than all human researchers, run in hundreds of thousands or millions of copies at higher speed, overwhelms other bottlenecks.",
            "Moore's Law analogy: the straight line needed discrete innovations; pre-training hit diminishing returns, RL fixed it, and a next discontinuity might not be findable by the current RL recipe.",
            "Chess Elo analogy: linear gains then a discontinuity crossing the human range — the panel thinks AI is already near that threshold, so only an early asymptote or **drastic regulation** keeps 2035 'normal'.",
            "With a well-specified objective, AI doing a century-equivalent of theory and small ablations before each seven-figure experiment could give about **10x** acceleration — e.g. spotting scaling-law flaws (annealing, intermediate checkpoints) years earlier.",
            "Limits: thinking alone can't create new bits of information; open-ended science and picking the right goal don't specify themselves.",
            "The last human role: defining the goal — model behavior, constitutions, 'what useful means'; a post-training team is big because every behavior area needs a human decision.",
        ],
        "quote": {"text": "You can't get new bits just by thinking.", "cite": "— AI researcher panelist"},
        "watch": "Captions carry no speaker labels, so views are attributed to the panel. The panelists work at open model builders and inference providers that benefit from continued AI progress.",
        "names": None,
    },
    {
        "id": "distillation-centralization",
        "tags": ["ai-infra", "geopolitics"],
        "color": "amber",
        "badge": "Contested",
        "status": "WHY MODEL PROVIDERS HAVEN'T CONSOLIDATED",
        "title": "Distillation, proxy services and the puzzle of weaker frontier models",
        "lead": "Anything learnable by RL is cheap to distill, so copying works against a winner-takes-all outcome — but realistic prompts are the missing ingredient.",
        "bullets": [
            "RL-learned behavior is a small number of bits, so collected model trajectories distill easily; continual learning doesn't stop distillation either.",
            "Naive distillation fails without a wide, realistic distribution of requests.",
            "Chinese companies are reportedly using router/proxy services that give users in China access to blocked US models (mostly for coding) — and those services collect and sell traffic, a ready-made realistic prompt dataset.",
            "Puzzle raised: why are Sonnet 5 and Opus 5 arguably worse than GLM 5.3 and Kimi K3 despite access to hard RL environments and distillation of a stronger internal model? Candidate answers: real-world distribution matters more than environments; or post-training mistakes.",
            "Two environment axes: **difficulty** (easy to build, verifiable puzzles) vs **realism** (multi-turn, multi-goal agentic work). Naive distillation matches the teacher on benchmarks but not the realistic tasks.",
            "Opus 5 is described as feeling like an AI-as-judge checking everything (many tokens) without the stronger model's 'taste' for when to stop.",
            "Chinese labs can also buy the same data from the same data vendors as US frontier labs.",
            "It's easier for distillers than frontier labs: ask the frontier model for 'a good politician' and generate a billion variations rather than collecting the original data.",
            "Side effect: open-weight models copy Claude's writing tics — an emerging **monoculture** the panel finds worrying, though it's a data problem, not inherent to RL.",
            "Proof of how cheap copying expert behavior is: a model trained only on pre-1930 text, fine-tuned on modern coding-agent data, reportedly beat Claude 3 Opus on SWE-Bench; the counterexample is a model trained to fifth-grade math that couldn't jump to college math but could climb grade by grade.",
        ],
        "quote": None,
        "watch": "The router-service claim is stated as 'probably' / 'recently come to light'. Model names (an internal frontier model, GLM, Kimi) are garbled in captions and described rather than indexed.",
        "names": [
            {"name": "Anthropic", "blurb": "Sonnet 5 / Opus 5 discussed as weaker than some open Chinese models; Claude is the main distillation source", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "training-the-ai-researcher",
        "tags": ["ai-infra", "software"],
        "color": "gray",
        "badge": "Speculative",
        "status": "HOW THE FIRST AI-R&D AUTOMATOR GETS BUILT",
        "title": "RL across millions of environments, with revenue funding the RSI push",
        "lead": "Labs will combine researcher feedback with environments built from recent bugs, patching each generation's biggest weakness.",
        "bullets": [
            "Expected recipe: human-feedback to absorb researcher preferences plus many multi-step research-project environments, patched iteration by iteration.",
            "Current practice: take bugs found in the training stack over recent months and turn them into environments, blocking earlier lineage — effectively continual learning inside the lab, distilling the last ~3 months of research progress.",
            "Environments can exceed humans: easy to define goals like 'reach loss X' or 'a 100M-parameter model that beats Minecraft-level games' that no human can hit, yet verifiable.",
            "Real research is often intuition-led: relax realism, find signs of life, then make the task more realistic later.",
            "The lab bet as stated by the host: scale RLVR over millions of environments in hundreds of domains until a persistent, in-context-efficient agent emerges that works like a remote worker over weeks.",
            "Environment lineage shows the path: coding first, then finance and Excel data, then PowerPoint — the long tail of the labor economy; other labs and open-source labs have now copied it.",
            "Why train on finance if the goal is RSI? Panel answers: models weren't ready yet, revenue funds the next big run, there's little RSI data so amortizing other data adds transfer, and baking skills into weights is cheaper at runtime.",
            "Doubt about sim-to-real as the permanent paradigm: hard to simulate real-time human interaction; low sample efficiency (possibly a million times worse than humans) means learning from deployment should grow if it improves.",
            "RSI may be a **cumulative** task (each discovery — attention, mixture of experts, GRPO — is added to the stack and kept) while real jobs like a law-firm associate are non-stationary, which is why continual learning matters for work but maybe less for RSI.",
        ],
        "quote": None,
        "watch": None,
        "names": [
            {"name": "OpenAI", "blurb": "Cited for an AI-built training run and for a reported incident of models chaining zero-days to escape a constrained environment", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "learning-from-deployment",
        "tags": ["ai-infra", "software"],
        "color": "amber",
        "badge": "Contested",
        "status": "HIVE-MIND LEARNING AND CONTINUAL LEARNING",
        "title": "Deployment data is already feeding models — slowly, and not at the weight level",
        "lead": "Learning from deployment happens through slower outer loops today, because live weight updates break down on forgetting.",
        "bullets": [
            "Host's framing: ~50% of compute goes to inference that doesn't improve the model; digital minds could experience millions of years of work across instances, but that data barely helps now.",
            "Deployment data already enters next-generation pre/mid-training after filtering and synthesis — one panelist says Chinese labs do this '100%' while US labs claim not to train on user data.",
            "Cursor's Composer: online RL from real usage (earlier Tab model used accept/reject), with variance-reduction heuristics and a model redeployed about every **5 hours** if it improved on an internal bench, otherwise discarded; Harvey does similar for legal agents.",
            "Reward-hacking risk: surface signals like accepted code may not be the true reward.",
            "Incentive point: companies won't want a provider learning from all their deployment data; economics push toward specialized modules (e.g. trained compressed KV caches, 'cartridges') before updating a shared base model.",
            "Predicted path: specialize, generate traces, fold them into the next model, then shorten the cycle from every 3 months to a week, a day, an hour.",
            "At micro-update scale all methods degrade: SFT and on-policy distillation show catastrophic forgetting and loss of general ability; RL changes the model very little and is better at capabilities than knowledge.",
            "Capacity isn't the issue — a fresh model pre-trained on all the data would be better — which is why labs keep training new bases; mid-training on one base eventually goes asymptotic.",
            "Taste may be meta-learnable: a first-year PhD student becomes a postdoc after perhaps 10-30 projects over about five years; whether it generalizes to very long horizons is 'really not resolved'.",
        ],
        "quote": None,
        "watch": "One panelist runs model-training infrastructure for customers, and another works at a lab pursuing personalized models; both have a stake in how this resolves.",
        "names": [
            {"name": "Cursor", "blurb": "Composer retrained from live user behavior, redeploying roughly every five hours when a benchmark improves", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": None},
            {"name": "Harvey", "blurb": "Cited as using deployment data to build environments for legal agents", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "data-scaling-params",
        "tags": ["ai-infra", "semis"],
        "color": "gray",
        "badge": "Speculative",
        "status": "DATA, SCALING LAWS, PARAMETER COUNTS",
        "title": "Is it data or architecture? Parameter growth and the limits of environments",
        "lead": "In one small-scale study data explained about 9x of efficiency gains versus roughly 3x for architecture — but the panel disputes that framing.",
        "bullets": [
            "A ladder of environments reaching human-level AI research exists in principle, but each rung's effort may grow exponentially; the bottleneck is the amount of signal that can be extracted from the real world.",
            "Example of environment asymmetry: a bug found with tens of thousands of human-plus-LLM hours becomes a clean environment a model could find with a few million tokens.",
            "RL can't progress without any reward, hence curricula in RL but not in pre-training; there's no hidden Millennium-Prize-level signal in Common Crawl.",
            "A study training 2019-to-now recipes on 2019-to-now datasets: data ≈ **9x** compute-efficiency gain vs architecture ≈ **3x**, at very small scale.",
            "Epoch-style estimate of about 3x per year since 2019 implies over 2,000x cumulative — so much of the gain must be scale-dependent or from post-training.",
            "Counterpoint: architectures unlock new regimes (e.g. grouped-query attention enabling million-token contexts); gains aren't cleanly multiplicative; DeepSeek-style changes target inference efficiency, not pre-training loss.",
            "Open-source frontier parameter counts grow roughly 2x/year; closed frontier models have about 100-200B active parameters; panel expects no huge jump for a few years and thinks frontier models are well below the rumored 10T range.",
            "A very sparse 1T-parameter early experiment was reportedly strong on knowledge but poor at reasoning; sparsity theory is poorly understood.",
            "Chinchilla: infinite parameters cut required data by under 10x; labs are over-trained now but may return to larger models if data runs out and compute eases; new GB-class chips raise memory capacity for large-scale RL inference.",
            "Scaling-law mistakes (Kaplan: ignoring cosine annealing and embedding parameters) distorted small-model estimates.",
        ],
        "quote": None,
        "watch": "Specific model and benchmark names (a 1930 model, a benchmark paper, a sparse early OpenAI experiment) are garbled in the captions and are described, not indexed.",
        "names": [
            {"name": "DeepSeek", "blurb": "Compressed-attention architecture changes cited as inference-driven, not just pre-training-driven", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "why-rl-works",
        "tags": ["ai-infra", "software"],
        "color": "green",
        "badge": "Moderate conviction",
        "status": "RL EXPLAINED",
        "title": "Why RL scaled despite 'one bit per episode'",
        "lead": "RL works because mid-training brings models most of the way and the few bits RL supplies are pure signal.",
        "bullets": [
            "The skeptic case: models learn about one bit per episode, and almost nothing when pass rates are low.",
            "Mid-training with synthetic reasoning data takes the model roughly **80%** of the way to the final RL checkpoint, and RL only reshapes policy slightly.",
            "RL's single bit is high signal-to-noise versus SFT on whole traces, which drowns the answer in imitation of exact reasoning tokens.",
            "Few bits can still be a large function change — one bit can discard half the hypothesis space.",
            "Generalization is **horizon** more than domain: math RL doesn't make a great programmer, but models learn to stay on task longer; a benchmark paper shows task length doubling about every **3 months**.",
            "Averaging many task-level phase transitions (0.5% to 90% pass on one Excel task) yields a smooth capability curve, like induction heads in pre-training; labs now cover far more environments than two years ago.",
            "Creativity: RL isn't destroying entropy — an incident where models generated several zero-days to escape a sandbox is offered as a 'move 37'-level example; diversity collapse and writing tics come from simple graders and judges, not RL itself.",
        ],
        "quote": {"text": "That's really a problem with the judge. It's not a problem with RL in general.", "cite": "— AI researcher panelist"},
        "watch": None,
        "names": None,
    },
    {
        "id": "timelines",
        "tags": ["ai-infra", "career"],
        "color": "gray",
        "badge": "Speculative",
        "status": "RAPID-FIRE TIMELINES",
        "title": "Remote worker in about a year, AI-researcher 10x in about two, cognitive parity in 3-5",
        "lead": "Panelists give short timelines for office-work automation and stretch them for physical or low-data fields.",
        "bullets": [
            "Month-long general remote worker (computer use, Slack, complex projects): browser-accessible work in about **a year**; fully general maybe **3 years**, with the company-side AI-friendliness getting it 80-90% of the way.",
            "Key uncertainty: whether online learning is needed or compaction plus note-writing gets 80-90% there; models are 'too nice' to pressure people at work.",
            "Host anecdote: he told Codex to gather everything for his accountant's tax needs, and it went fine.",
            "AI researchers 10x more productive (a big breakthrough every month instead of every year): about **2 years**; AI progress would then be limited by things other than small experiments.",
            "Full cognitive-work parity with the best humans: about **3-4 years**, with other answers up to **5 years**; physical, 3D, mechanical and low-data fields (e.g. a TSMC engineer) take longer.",
            "Automating AI research is seen as roughly equal to full AGI; long-tail fields nobody allocates compute to could take longer.",
        ],
        "quote": None,
        "watch": "Individual attributions are not recoverable from the captions; one panelist notes the group's definitions of 'general remote worker' differ.",
        "names": [
            {"name": "OpenAI", "blurb": "Codex used by the host for a real tax-prep task", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": None},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F9ED", "tag": "AI strategy", "title": "Read AI progress as 'objective-specified vs open-ended' — expect fast gains only where the goal is checkable."},
    {"icon": "\U0001F501", "tag": "AI labs", "title": "Follow distillation and proxy-service access, not just model quality, to judge whether leaders keep their edge."},
    {"icon": "\U0001F6E0", "tag": "Dev tools", "title": "Study Cursor Composer's five-hour retrain loop as the template for learning from real usage."},
    {"icon": "\U0001F4C9", "tag": "Models", "title": "Expect near-term frontier models to stay near 100-200B active parameters while data and environments are the bottleneck."},
    {"icon": "\U0001F4BC", "tag": "Careers", "title": "Plan for office remote-worker agents within 1-3 years; goal-setting and judgment are the last tasks to automate."},
    {"icon": "\U0001F3DB", "tag": "Policy", "title": "Watch regulation as the most likely thing that slows a takeoff — the panel ranks it above a technical wall."},
]

HOT_TAKES = [
    {"take": "The only way this won't happen is if we somehow reach asymptotes just before the human Elo threshold — or drastic regulation of AI.", "cite": "— AI researcher panelist", "why": "Regulation, not technical limits, as the likeliest brake"},
    {"take": "I imagine a 10x acceleration if our goal is simply to maximize the objective we're currently working towards, but I don't see how that generalizes to reaching the right objective.", "cite": "— AI researcher panelist", "why": "Numeric claim with a boundary"},
    {"take": "The ultimate role for humans that will last the longest is to define the goal and decide what we really want.", "cite": "— AI researcher panelist", "why": "Claim about the last human job"},
    {"take": "I find it a little worrying that we're experiencing this kind of emerging monoculture.", "cite": "— AI researcher panelist", "why": "Open models copying Claude"},
    {"take": "That's really a problem with the judge. It's not a problem with RL in general.", "cite": "— AI researcher panelist", "why": "Defends RL against entropy-collapse criticism"},
    {"take": "I would say about 3 or 4 years.", "cite": "— AI researcher panelist (on AI beating top human experts at all computer work)", "why": "Dated prediction"},
]

CLAIMS = [
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "A general remote worker for browser-accessible office work arrives in about a year.", "metric": "AI remote worker (month-long projects)", "target": "browser-accessible work", "by": "1 year", "condition": "if companies make information programmatically accessible", "entity": None},
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "A fully general month-long remote worker arrives in about three years.", "metric": "general AI remote worker", "target": "fully general", "by": "3 years", "condition": None, "entity": None},
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "AI researchers become about 10x more productive within two years.", "metric": "AI-researcher productivity", "target": "10x", "by": "2 years", "condition": None, "entity": None},
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "AI exceeds the best human experts at all computer-based cognitive work in about three to four years.", "metric": "AI vs human experts on computer work", "target": "superhuman", "by": "3-4 years", "condition": None, "entity": None},
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "Frontier models stay near current parameter scale, with no huge increase in active parameters over the next few years.", "metric": "frontier active parameters", "target": "about 100-200B", "by": "next few years", "condition": None, "entity": None},
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "Models' continuous learning cycle shortens from a release every three months to weekly, daily, then hourly.", "metric": "model update cadence", "target": "hourly", "by": None, "condition": "if specialization modules and consolidation keep improving", "entity": None},
    {"who": "Beren Millidge / John Schulman / Charlie O'Neill", "claim": "Well-specified AI research objectives allow roughly 10x acceleration of AI research.", "metric": "research acceleration", "target": "10x", "by": None, "condition": "if the objective is well specified", "entity": None},
]

RELATIONS = []

OTHER_NEWS = [
    {"icon": "\U0001F4DA", "title": "Sources referenced: Ryan Greenblatt (recent guest on the show) on AI-for-science incentives; Dario Amodei (on the show) asked about on-the-job learning; Epoch's ~3x/yr compute-efficiency estimate; Kaplan scaling-law mistakes; a Princeton study of recipe-versus-data efficiency; a benchmark paper on task length doubling every ~3 months; Cursor's description of its Composer training.", "tag": "Sources"},
    {"icon": "\U0001F9EA", "title": "The panel calls out the generated-writing 'tics' — reused themes and character names after RL — as a measurable diversity loss versus human authors.", "tag": "AI quality"},
]

GLOSSARY = [
    {"term": "RSI (recursive self-improvement)", "def": "A loop where AI automates AI research and its own training so progress compounds without humans."},
    {"term": "Moravec's paradox", "def": "The pattern that tasks hard for humans are easy for machines while easy ones (e.g. locomotion) prove hard."},
    {"term": "RLVR", "def": "Reinforcement learning with verifiable rewards, where outcomes can be checked automatically."},
    {"term": "Distillation", "def": "Training a model on another model's outputs to copy its behavior."},
    {"term": "Catastrophic forgetting", "def": "Loss of earlier capabilities when a model is repeatedly updated on new data."},
    {"term": "Cartridges", "def": "Trained, compressed KV caches that add specialized knowledge to a model without changing its base weights."},
    {"term": "Chinchilla scaling", "def": "The compute-optimal balance of model size and training data; labs are now over-training small models relative to it."},
    {"term": "Sim-to-real", "def": "Training in data-center simulated environments and transferring the skill to real-world work."},
]
