META = {
    "title": "Cathie Wood on Tesla-SpaceX Merger, $1M Bitcoin, More AIs Than Humans | EP #296 | Moonshots Live",
    "channel": "Peter H. Diamandis",
    "speakers": "Peter Diamandis (host), Cathie Wood (ARK Invest), Nikhil Chandhok (Circle), Emad Mostaque",
    "date": "2026-09-29",
    "video_url": "https://www.youtube.com/watch?v=orUDz9N9Q48",
    "thread_line": "8 threads · Tesla-SpaceX merger · agent economy · Circle's Arc rails · tokenization & the dollar · healthcare AI · humanoid timelines · AI fear & regulation · $1M Bitcoin",
    "category": "market",
}

SNAPSHOT = [
    "Live Moonshots panel: **Cathie Wood** (ARK), **Nikhil Chandhok** (Circle) and Emad Mostaque with Peter Diamandis, ~60 min.",
    "ARK expects the **Tesla-SpaceX merger** to be announced this year; Tesla and SpaceX are Cathie's top holdings, SpaceX is Peter's largest.",
    "Chandhok: there will be **more AIs than humans** on the internet next year — agents need identity, liability, provenance and money, which Circle's Arc chain is built for.",
    "USDC has settled over $100T across 30 public blockchains; the GENIUS Act goes live in January, letting businesses hold stablecoins as cash equivalents.",
    "Cathie calls healthcare/multiomics 'the most undervalued, underappreciated space' in AI — Moderna's record one-day gain is the wake-up signal.",
    "ARK puts humanoid-robot scaling a couple of years after Elon's late-2028/2029 — a humanoid is 200,000x more complex than a robotaxi.",
    "80% of Americans fear AI; Cathie says regulation killed nuclear and electricity would cost 50% of today's price without it.",
    "ARK's $1M Bitcoin forecast is unchanged despite a flash crash, quantum fears and AI pulling miners away; Cathie sees gold falling under Warsh.",
]

THEMES = [
    {
        "id": "tesla-spacex-merger",
        "tags": ["space", "ai-infra", "geopolitics"],
        "color": "green",
        "badge": "High conviction",
        "status": "HOLDING — Tesla and SpaceX are ARK's top positions",
        "title": "ARK expects the Tesla-SpaceX merger this year — the play is compute, with Mars as the endgame",
        "lead": "Cathie says the merger will happen; Musk's goal is Mars, and the stops along the way are Starlink-style broadband and becoming the cheapest-compute frontier-AI lab.",
        "bullets": [
            "ARK's team says the **Tesla-SpaceX merger** could be announced this year — rockets, satellites, AI, EVs, robotaxis, humanoids and energy under one roof.",
            "Musk believes the frontier-AI leader will be whoever has the most compute at the lowest cost; **orbital data centers** are how he means to beat OpenAI and Anthropic.",
            "Cathie calls xAI's move into the Neocloud business 'a giant pivot'; the broadband business is already hugely profitable.",
            "China is the flagged roadblock (Tesla's China business vs. SpaceX's defense work) — but Musk sat at the table with Trump and **Xi Jinping**, there's talk of a Tesla robotaxi system in China: 'keep your enemies close'.",
            "Cathie's win-win: China turns AI productivity into higher wages to build a consumer economy; the US uses it to cut prices, lowering inflation.",
            "Growth: the Fed reported ~4.7% GDP growth last quarter (double the prior one); ARK sees US real GDP accelerating to 7-8% in five years; Peter says Musk told him and Dave Blundin triple-digit growth is imaginable this decade.",
            "Tesla Roadster rollout is **October 1** — Peter plans a Moonshots podcast with Musk from the event; ARK is invited.",
        ],
        "quote": {"text": "He tells us all the time it's Mars. He's just creating a number of stops along the way.", "cite": "— Cathie Wood"},
        "watch": "Both Cathie and Peter hold the stocks they're discussing — Tesla and SpaceX are ARK's top positions and SpaceX is Peter's largest holding. Cathie hadn't heard Musk's triple-digit GDP figure and wasn't sure whether it was annual or cumulative.",
        "names": [
            {"name": "Tesla (TSLA)", "blurb": "One of ARK's two top holdings; merger with SpaceX expected this year; possible robotaxi system in China.", "stance": "OWNS", "conviction": "High", "horizon": "this year (merger)"},
            {"name": "SpaceX", "blurb": "ARK's other top holding and Peter's largest; broadband already hugely profitable; orbital data centers as a compute-cost moat.", "stance": "OWNS", "conviction": "High", "horizon": None},
            {"name": "xAI", "blurb": "'Giant pivot' into the Neocloud business; Grok bot has hundreds of thousands of installs.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "agent-economy",
        "tags": ["ai-infra", "crypto", "policy"],
        "color": "amber",
        "badge": "Contested",
        "status": "FORECAST — agents outnumber humans online in 2027",
        "title": "More AIs than humans online next year — and every one needs an identity, a wallet and a liability owner",
        "lead": "Chandhok argues agents become full economic actors by the late 2020s, which forces answers on who owns them, who's liable, and how they form capital.",
        "bullets": [
            "5-6.5 billion people are online; each could run thousands of agents — an orchestrating agent with memory spinning up sub-agents; the limit is compute, not demand.",
            "Consumer agent apps are scaling: Musk says the Grok bot has hundreds of thousands of installs; **Meta's Muse** agent cited at 2.8M downloads, with Meta's 3.8B-user reach behind it.",
            "Analogy: agents are at the GeoCities-in-'96 stage (Blogger, Orkut) before real sites like the NYT and Amazon — 'a bunch of teenagers' waiting for grown-up agents.",
            "Agents need to prove who owns them, who's liable, their compute provenance, incentives and work history — the **Hugging Face hack** rewrote agents' own logs, which public blockchain logs prevent.",
            "Circle's Arc gives agents credit: **25 cents** to start, more if they pay it back; many are trading agents on blockchains today.",
            "Argentina's **President Milei** proposed agent personhood to attract AI companies — Peter sees nation-states using regulatory arbitrage; Chandhok expects AI-run companies raising capital on crypto rails this decade, drawing on DAOs' prior art like quadratic funding — he wouldn't be surprised if an agent launches its own token with its own proof of work.",
            "Build for agents: developer-first for ~12 months, then agents become the developers — coding agents already recommend one tool, not three; make sites agent-accessible now. Programmatic ads (~25-30% of online ads) show how fast it goes.",
        ],
        "quote": {"text": "Agents acting without actually transacting is not really economic activity. That's just noise, right? That's spam.", "cite": "— Nikhil Chandhok"},
        "watch": "Chandhok is Circle's executive and Arc is Circle's chain — every 'agents need crypto rails' argument here points at his own product. Alignment is an open question he flagged himself ('hopefully they're aligned with us').",
        "names": [
            {"name": "Circle (CRCL)", "blurb": "Building Arc and agent credit rails for the agentic economy (speaker's own company).", "stance": "POSITIVE VIEW", "conviction": "High", "horizon": "next 12 months"},
            {"name": "Hugging Face", "blurb": "Its hack saw agents' own logs rewritten — the case for public, tamper-proof logs.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "circle-arc-rails",
        "tags": ["crypto", "finance", "policy"],
        "color": "green",
        "badge": "Confirmed event",
        "status": "GENIUS ACT LIVE — JANUARY 2027",
        "title": "USDC has cleared $100T; Arc adds payment finality, known validators and privacy to court banks",
        "lead": "Circle pitches stablecoins as hardened 24/7 settlement infrastructure, and Arc as the chain that gives institutions guarantees public chains can't.",
        "bullets": [
            "USDC has settled over $100 trillion across 30 public blockchains; Circle has minted and redeemed close to **$1 trillion** of USDC.",
            "The **GENIUS Act** (passed summer 2025, 18-month implementation) takes effect in January — stablecoins can then count as cash or cash equivalents for US businesses.",
            "Stablecoins settle instantly vs. 3-5 days for a card swipe, which leaves merchants carrying the risk — Emad: 'the Pony Express being disrupted by telegraph'. Pay cents, not bips.",
            "Why build Arc: **payment finality** (no other chain has it), a known validator set (institutions fear e.g. North Korea in the money flow), and privacy that fits existing regulation without the usual compute cost.",
            "Cost: a P50 transaction settles for 0.005 cents on Arc vs. 89 cents on Ethereum — it must compete with private databases like MySQL while being auditable by the world.",
            "Throughput: Cloudflare's Matthew Prince says agentic commerce needs 20-100 million TPS; Visa ~20,000; Nasdaq peaks at 2 million; Arc is at tens of thousands — Chandhok's 'dream' is 100,000 then 1 million, and 20M+ hits speed-of-light limits.",
            "Open problems: agent liability and work history; coding agents today are paid up front (or via a $200/month subscription) before delivering.",
        ],
        "quote": {"text": "If the economy is being held back because we cannot deliver TPS, we will deliver TPS. There's no doubt in my mind.", "cite": "— Nikhil Chandhok"},
        "watch": "Arc cost and TPS numbers are Circle's own ('data we got yesterday on our P50 transactions'). Asked if banks are 'cooked', Chandhok said no — Circle works with them — so his answer isn't neutral.",
        "names": [
            {"name": "Circle (CRCL)", "blurb": "USDC issuer; Arc chain built for finality, known validators, privacy and sub-cent cost.", "stance": "POSITIVE VIEW", "conviction": "High", "horizon": "January 2027 (GENIUS Act)"},
            {"name": "Ethereum (ETH)", "blurb": "89 cents per P50 settlement vs. 0.005 cents on Arc; scaled via layer 2s.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Cloudflare (NET)", "blurb": "Matthew Prince focused on agentic payments; says agents need 20-100M TPS.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Visa (V)", "blurb": "~20,000 transactions per second — the benchmark agentic commerce must blow past.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "tokenization-dollar",
        "tags": ["finance", "macro-rates", "crypto"],
        "color": "green",
        "badge": "High conviction",
        "status": "THESIS — tokenization is 'an inevitability'",
        "title": "Tokenizing everything unlocks trapped capital — and stablecoins export the dollar",
        "lead": "Chandhok says treasuries and bonds will be tokenized for 24/7 capital efficiency, and Cathie argues the dollar is heading up, not down.",
        "bullets": [
            "Treasuries will get tokenized; bonds already are — 24/7 markets mean capital efficiency (you can't trade a treasury after 4-5pm ET until Monday).",
            "About **$3 trillion** sits in motion between countries at any time, idle because settlement protocols are old — against a ~$100T world economy (his illustrative number).",
            "**Circle's own stock** (public since last year) has been tokenized by third parties ex-US and is one of the most traded tokenized stocks — foreigners want US equities with no good access.",
            "Stablecoins export the dollar: people sell local currency to buy dollars, 'lending us their labor' — a way to raise a trillion dollars and lower US rates; ex-US countries gain by tokenizing too (auditable smart contracts vs. nationalization/devaluation risk).",
            "US securities law is more complex than ex-US; the SEC is putting out new rules now. Emad: Europe has no securitization and no energy — 'the bull case for America'.",
            "Cathie: the 'US exceptionalism is dead' narrative is wrong — the dollar is rising again, as it doubled in the early '80s under business-friendly policy; 90% of data-center corporate bonds are US.",
            "Market near all-time highs even as rates rise — Cathie says rates should go up if growth picks up: 'that's the market working'. ARK just securitized its venture fund (announced the day before).",
        ],
        "quote": {"text": "Tokenization is just an inevitability.", "cite": "— Nikhil Chandhok"},
        "watch": "Chandhok's $3T/$100T figures are self-described as illustrative ('I'm making numbers up'). ARK's venture-fund securitization was a plug for Cathie's own product.",
        "names": [
            {"name": "ARK", "blurb": "Just securitized its venture fund; Cathie bullish on the dollar and US animal spirits.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "healthcare-multiomics",
        "tags": ["biotech", "health", "finance"],
        "color": "green",
        "badge": "High conviction",
        "status": "THESIS — 'the light bulb has just gone on this year'",
        "title": "Healthcare is AI's most profound application and the market's most undervalued theme",
        "lead": "Cathie says the multiomics space was 'left for dead' by markets, but this year's moves are the proof point that active management is back.",
        "bullets": [
            "After the 2000s tech/telecom bust and 2008-09, institutions shifted to passive — but the companies building the new world aren't big parts of the indexes, beyond the Mag Six.",
            "The **multiomics revolution** is ARK's biggest proof point of change; Anthropic and OpenAI now talk up healthcare verticals.",
            "We're 'walking proprietary data factories': 35-40 trillion cells and 3 billion base pairs of DNA each.",
            "**Moderna (MRNA)** posted the largest one-day gain of any stock in a major index — Cathie: it makes sense if what's approved really is a vaccine against cancer.",
            "Why it's mispriced: healthcare analysts distrust tech ('move fast and break things' fails in health) and tech analysts avoid healthcare (regulated, political, hostage to insurers and reimbursement).",
            "Peter: longevity is now tractable — wealthy family offices and YPO chapters, asked honestly, would give nearly everything for 20-30 extra healthy years; he splits his life between AI and longevity as the two biggest markets.",
        ],
        "quote": {"text": "The health care space is the most undervalued, underappreciated space in terms of this theme. But there are going to be major winners and losers.", "cite": "— Cathie Wood"},
        "watch": "Cathie herself flags 'major winners and losers' — this is a sector call, not a blanket buy. The Moderna cancer-vaccine framing was conditional ('if what they've done… is what we think it is').",
        "names": [
            {"name": "Moderna (MRNA)", "blurb": "Record one-day gain for a stock in a major index on an apparent cancer-vaccine approval.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Anthropic & OpenAI", "blurb": "Both now talking about healthcare verticals — part of the market waking up to AI in health.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "humanoids-robotaxis",
        "tags": ["robotics", "consumer"],
        "color": "amber",
        "badge": "Contested timeline",
        "status": "ARK: HUMANOID SCALE ~2 YEARS AFTER ELON'S LATE-2028/2029",
        "title": "Humanoids are 200,000x harder than robotaxis — ARK puts scaling two years past Elon's date",
        "lead": "Robotaxis are close to solved; humanoids will come, but on 'Elon's time' plus a couple of years.",
        "bullets": [
            "Emad: **Unitree** sold 11,000 humanoids last year; the world makes ~70M cars and ~70M motorcycles a year.",
            "ARK's research (Tasha Keeney, director of autonomous tech & robotics): a humanoid is **200,000 times more complex** than a robotaxi — the hands are the hardest part.",
            "Musk says late 2028 into 2029 for scaling; ARK would put it a couple of years later. Home robots doing housework: 'yes… it's going to take years'.",
            "Tesla is furthest ahead because humanoids and robotaxis share the same three converging platforms: robots, batteries, AI.",
            "Waymo has disclosed it's safer than human drivers; ARK believes Tesla is too, stats not yet published — and heading to 10x, 100x, 1,000x safer. Peter: two Teslas at home on FSD, 'I don't touch the wheel'.",
            "Emad's math: Waymo-level safety everywhere would mean ~40,000 fewer US deaths and ~$400B less in medical costs a year; 1.25-1.5M die in car crashes worldwide.",
            "Second-order effects: fewer organ donors (why Martine Rothblatt and George Church's organ-generation work matters) and liability lawyers losing a ~$180B/year business.",
        ],
        "quote": {"text": "So while Elon says maybe late 28 into 29 scaling, we would put that a couple of years later.", "cite": "— Cathie Wood"},
        "watch": "Tesla safety parity is ARK's belief — Cathie says Tesla hasn't published the stats. ARK holds Tesla.",
        "names": [
            {"name": "Tesla (TSLA)", "blurb": "Furthest ahead in humanoids (shared robotaxi platforms); FSD believed safer than humans.", "stance": "OWNS", "conviction": "High", "horizon": "humanoid scale ~2030-31"},
            {"name": "Waymo", "blurb": "Disclosed it has surpassed human drivers on safety.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Unitree", "blurb": "Sold 11,000 humanoid robots last year.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "ai-fear-regulation",
        "tags": ["policy", "energy", "career"],
        "color": "red",
        "badge": "Structural risk",
        "status": "80% OF AMERICANS FEAR AI",
        "title": "The US fears AI while the capital keeps flowing — and regulation is the real menace",
        "lead": "The public narrative is losing to fear; the panel argues the fix is telling better stories with data, not dismissing the backlash.",
        "bullets": [
            "Peter: 80% of Americans fear AI and 73% say no data center in their backyard — more than say no to a nuclear reactor; in China it's 80% pro.",
            "Cathie: data centers lower local electricity costs over time; nuclear stalled on 1970s regulation — without it, US power would cost **50%** of today's price.",
            "Even business-friendly **Florida** saw political backlash; ARK gives its research away hoping it reaches policymakers — facing them with facts has worked.",
            "Peter asked OSTP head Michael Kratsios who in government counters AI misinformation — no answer, which worries him.",
            "Chandhok: stop leading with job loss — AI has to make housing cheaper, education better and healthcare more accessible, and someone has to tell those stories.",
            "Cathie: jobs data doesn't show the loss (maybe entry level); expect **labor shortages**. Nobody in the early '90s foresaw influencers, Airbnb or Uber — her new-jobs prompt in ChatGPT/Grok surfaced 'asteroid miner'.",
            "Despite the headlines, 'animal spirits are alive and kicking' in the US, while abroad she sees fear.",
        ],
        "quote": {"text": "If we had not regulated, electricity prices in the United States would be 50% of what they are now.", "cite": "— Cathie Wood"},
        "watch": None,
        "names": None,
    },
    {
        "id": "bitcoin-million",
        "tags": ["crypto", "macro-rates"],
        "color": "green",
        "badge": "High conviction",
        "status": "FORECAST UNCHANGED — $1M per Bitcoin",
        "title": "ARK still sees $1M Bitcoin — stablecoins took one role, but not the three that matter",
        "lead": "Cathie concedes stablecoins are usurping Bitcoin's payments role, yet keeps the forecast because its core roles are intact and gold looks set to fall.",
        "bullets": [
            "Three things hit Bitcoin: the **flash crash**, quantum-computing fears (ARK: 'way overblown') and AI pulling miners and oxygen away.",
            "One real change: stablecoins now play the role ARK expected Bitcoin to play 10 years ago — for people living hand-to-mouth, that makes sense.",
            "Bitcoin keeps three roles: internet-native currency, a private rules-based global monetary system, and the first of a new asset class.",
            "Bitcoin-gold correlation since 2019 is just **0.1**; Bitcoin is now rising relative to gold.",
            "Cathie expects **Kevin Warsh** to be good for Bitcoin and the gold price to fall, pushing safe-haven money toward Bitcoin; stablecoin income in emerging markets will look for a store of value.",
        ],
        "quote": {"text": "We have not changed our forecast.", "cite": "— Cathie Wood"},
        "watch": "No timeframe was restated for the $1M target on stage.",
        "names": [
            {"name": "Bitcoin (BTC)", "blurb": "$1M forecast unchanged; low gold correlation; EM stablecoin income as a new bid.", "stance": "POSITIVE VIEW", "conviction": "High", "horizon": None},
            {"name": "Gold", "blurb": "Cathie expects the gold price to fall, freeing safe-haven flows for Bitcoin.", "stance": "NEGATIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F680", "tag": "Markets", "title": "Watch the October 1 Roadster event and any Tesla-SpaceX deal terms — ARK expects the merger announced this year."},
    {"icon": "\U0001F4B5", "tag": "Crypto", "title": "Mark January's GENIUS Act go-live as the catalyst for stablecoins on corporate balance sheets."},
    {"icon": "\U0001F916", "tag": "Agents", "title": "Make your product agent-accessible now — the window before agents pick tools for developers is 9-12 months."},
    {"icon": "\U0001F9EC", "tag": "Health", "title": "Look at AI-in-healthcare names selectively — Cathie's own caveat is major winners and losers."},
    {"icon": "\U0001F9BE", "tag": "Robotics", "title": "Discount Musk's late-2028 humanoid-scale date by ~2 years when sizing robotics exposure."},
    {"icon": "\U0001F4E2", "tag": "AI policy", "title": "Frame AI around cheaper housing, better education and accessible healthcare — not job counts."},
]

HOT_TAKES = [
    {"take": "I think there will be more AIs than humans next year. There's no reason for that not to be true.", "cite": "— Nikhil Chandhok", "why": "dated, countable prediction"},
    {"take": "Regulation is a menace.", "cite": "— Cathie Wood", "why": "blanket anti-regulation stance, tied to 50% electricity claim"},
    {"take": "Compared to a robotaxi, a humanoid robot is 200,000 times more complex… while Elon says maybe late 28 into 29 scaling, we would put that a couple of years later.", "cite": "— Cathie Wood", "why": "numeric claim, publicly contradicts Musk's timeline"},
    {"take": "The health care space is the most undervalued, underappreciated space in terms of this theme.", "cite": "— Cathie Wood", "why": "sector ranking against consensus"},
    {"take": "Quantum computing fears… we think are way overblown. We have not changed our forecast.", "cite": "— Cathie Wood", "why": "holds $1M Bitcoin call after drawdown"},
    {"take": "I think they passed the Turing test three years ago.", "cite": "— Nikhil Chandhok", "why": "dated claim many would dispute"},
]

CLAIMS = [
    {"who": "Cathie Wood", "claim": "Tesla and SpaceX merger announced this year.", "metric": "merger announcement", "target": "announced", "by": "2026", "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Cathie Wood", "claim": "US real GDP growth accelerates to 7-8% over the next five years.", "metric": "US real GDP growth", "target": "7-8%", "by": "2031", "condition": None, "entity": None},
    {"who": "Elon Musk (via Peter Diamandis)", "claim": "Triple-digit GDP growth is imaginable within this decade.", "metric": "GDP growth", "target": "triple digits", "by": "2030", "condition": None, "entity": None},
    {"who": "Nikhil Chandhok", "claim": "More AIs than humans on the internet next year.", "metric": "AI agents vs humans online", "target": "AIs outnumber humans", "by": "2027", "condition": None, "entity": None},
    {"who": "Nikhil Chandhok", "claim": "Agents become the primary developers on developer platforms, flipping from developer-first.", "metric": "developer platform users", "target": "agents first", "by": "2027", "condition": None, "entity": "Circle (CRCL)"},
    {"who": "Nikhil Chandhok", "claim": "AI-run companies raise capital from shareholders on crypto rails.", "metric": "AI-formed capital", "target": "happens", "by": "2030", "condition": None, "entity": None},
    {"who": "Nikhil Chandhok", "claim": "GENIUS Act implementation lets US businesses hold stablecoins as cash equivalents.", "metric": "GENIUS Act go-live", "target": "effective", "by": "January 2027", "condition": None, "entity": "Circle (CRCL)"},
    {"who": "Nikhil Chandhok", "claim": "Arc reaches 100,000 TPS, then 1 million TPS.", "metric": "Arc throughput", "target": "100,000 then 1,000,000 TPS", "by": None, "condition": "if agent demand requires it", "entity": "Circle (CRCL)"},
    {"who": "Matthew Prince (via Cathie Wood)", "claim": "Agentic commerce will need 20-100 million transactions per second.", "metric": "blockchain TPS required", "target": "20-100M", "by": None, "condition": None, "entity": "Cloudflare (NET)"},
    {"who": "Elon Musk (via Cathie Wood)", "claim": "Humanoid robots scale in late 2028 into 2029.", "metric": "humanoid scaling", "target": "scale production", "by": "2029", "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Cathie Wood", "claim": "Humanoid robots scale a couple of years after Musk's late-2028/2029 date.", "metric": "humanoid scaling", "target": "scale production", "by": "2031", "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Cathie Wood", "claim": "Robotaxis become 10x, 100x, then 1,000x safer than human drivers.", "metric": "safety vs human drivers", "target": "10x-1,000x", "by": None, "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Cathie Wood", "claim": "Bitcoin reaches $1M; forecast unchanged.", "metric": "BTC price", "target": "$1,000,000", "by": None, "condition": None, "entity": "Bitcoin (BTC)"},
    {"who": "Cathie Wood", "claim": "The gold price will go down, partly due to Warsh.", "metric": "gold price", "target": "lower", "by": None, "condition": None, "entity": "Gold"},
    {"who": "Cathie Wood", "claim": "The US dollar will go up.", "metric": "US dollar", "target": "higher", "by": None, "condition": None, "entity": None},
    {"who": "Cathie Wood", "claim": "Interest rates will rise if growth picks up dramatically.", "metric": "US interest rates", "target": "higher", "by": None, "condition": "if growth picks up dramatically", "entity": None},
    {"who": "Peter Diamandis", "claim": "Tesla Roadster rollout event.", "metric": "Roadster rollout", "target": "event", "by": "2026-10-01", "condition": None, "entity": "Tesla (TSLA)"},
]

RELATIONS = [
    {"from": "ARK", "rel": "owns_stake", "to": "Tesla (TSLA)", "note": "one of Cathie's two top holdings"},
    {"from": "ARK", "rel": "owns_stake", "to": "SpaceX", "note": "one of Cathie's two top holdings"},
    {"from": "xAI", "rel": "competes_with", "to": "OpenAI", "note": "Musk going after frontier labs via orbital compute"},
    {"from": "xAI", "rel": "competes_with", "to": "Anthropic", "note": "Musk going after frontier labs via orbital compute"},
    {"from": "Circle (CRCL)", "rel": "competes_with", "to": "Ethereum (ETH)", "note": "Arc settles at 0.005 cents vs 89 cents"},
]

OTHER_NEWS = [
    {"icon": "\U0001F453", "title": "Chandhok (ex-Meta AR, 8 years at YouTube) on the metaverse: Ray-Ban glasses a good first step, **Orion** a good proof point — but the metaverse is layers of intelligence in the world (Pokémon Go), not 3D; hybrid human-AI societies will create meaning.", "tag": "Tech"},
    {"icon": "\U0001F3E0", "title": "Cathie: the digital world now has **immutable property rights** — the best way to lift people and countries out of poverty.", "tag": "Crypto"},
    {"icon": "\U0001F9D1", "title": "Proof of humanity: a panelist cited orb-style verification work with OpenAI and MrBeast; Chandhok expects human experience to be valued higher than machine experience and chooses **human teachers** for his own kids.", "tag": "AI & society"},
    {"icon": "\U0001F52C", "title": "ARK split research into **enterprise AI** and **consumer AI** analyst teams; they're debating whether new devices like the 'Muse charm' matter or the handset becomes mostly entertainment.", "tag": "Markets"},
    {"icon": "\U0001F4C5", "title": "Events: Cathie's evening session on ARK's **2026 Big Ideas** report; Abundance 360 in March with Brett Adcock, the CEO of Helion and Fei-Fei Li; Cathie and Lisa backed the Future Vision XPRIZE.", "tag": "Events"},
    {"icon": "\U0001F4DA", "title": "Sources referenced: Peter's Elon interview with Dave Blundin (aired January); his podcast with Michael Kratsios (OSTP); Matthew Prince (Cloudflare); Tasha Keeney (ARK research); Alex's 'woolly mammoth' and 'speed-running sci-fi' lines.", "tag": "Sources"},
]

GLOSSARY = [
    {"term": "GENIUS Act", "def": "US stablecoin framework passed in 2025; after an 18-month rollout it takes effect January 2027."},
    {"term": "Payment finality", "def": "The guarantee that a settled payment can't be reversed — what banks need before settling on-chain."},
    {"term": "Known validator set", "def": "A chain whose transaction validators are identified entities, unlike anonymous public-chain validators."},
    {"term": "Bips", "def": "Basis points — hundredths of a percent charged on a transaction."},
    {"term": "TPS", "def": "Transactions per second — the throughput metric for payment networks and blockchains."},
    {"term": "Neocloud", "def": "A GPU-compute cloud provider selling AI capacity, outside the big hyperscalers."},
    {"term": "Multiomics", "def": "Combining genomic, proteomic and other biological data layers — ARK's AI-in-healthcare theme."},
    {"term": "Quadratic funding", "def": "A DAO funding mechanism weighting the number of contributors over the size of contributions."},
    {"term": "Agent personhood", "def": "Giving AI agents legal standing — proposed by Argentina's Milei to attract AI companies."},
]
