META = {
    "title": "Bill Ackman's Inflation Warning: Cathie Wood's Response | In The Know",
    "channel": "ARK Invest",
    "speakers": "Cathie Wood (ARK Invest CEO/CIO)",
    "date": "2026-10-02",
    "video_url": "https://www.youtube.com/watch?v=4Rir6HADnT8",
    "thread_line": "7 threads · Ackman rebuttal · inflation rolling over · tech deflation and 7-8% GDP · strong dollar · gold/oil/bitcoin · rolling recession over · credit and AI policy",
    "category": "market",
}

SNAPSHOT = [
    "Cathie Wood answers **Bill Ackman's** warning that rising interest costs will feed inflation: this is the 1980s replay, not the 1970s.",
    "Her call: much stronger real GDP growth, much lower inflation — maybe deflation — and rates rising on real growth rather than inflation.",
    "Inflation evidence: headline PCE down to 3.4%, Truflation core falling, Fed diffusion index reversing, money velocity flattening.",
    "Tech deflation engine: AI inference costs fall 99.99% a year; OpenAI's run rate went from $20B to $70B anyway — the Jevons paradox in action.",
    "Macro calls: dollar to all-time highs, oil to $30-35, gold keeps falling under Fed Chair Kevin Warsh, Bitcoin-to-gold has turned.",
    "The economy came through a \"rolling recession\"; manufacturing is out, housing is still stuck with mortgages above 7%.",
    "Credit: no systemic stress in bank CDS, but hyperscaler CDS are deteriorating as cash fortresses tap debt markets.",
]

THEMES = [
    {
        "id": "ackman-rebuttal",
        "tags": ["macro-rates"],
        "color": "green",
        "badge": "High conviction",
        "status": "RESPONSE TO BILL ACKMAN — RATES UP ON REAL GROWTH",
        "title": "Ackman's inflation spiral is a 1970s argument; Wood sees the 1980s instead",
        "lead": "Rising rates reflect a stronger real economy, not runaway inflation — the same setup that preceded the 1980s productivity boom.",
        "bullets": [
            "Ackman's tweet: rising interest costs keep feeding inflation in a **vicious cycle** — an argument Wood says was everywhere in the late 1970s.",
            "Her template is the 1980s: productivity lifts real growth while inflation falls, helped then by the PC and software revolution.",
            "Today's disinflation drivers: five platforms — AI, robotics, energy storage, blockchain and multiomic sequencing; deflation possible \"especially if oil prices crack.\"",
            "Rates since 1790 (built with Nick Grous's 2019 research): the 10-year went from below 1% in COVID to above 5% now — about the historical midpoint.",
            "The real anomaly was the 1970s-90s spike: closing the gold window in 1971 after Vietnam and Great Society \"guns and butter\" spending; then the Fed overcorrected and \"spoon fed\" markets after 08-09 and COVID.",
            "Five-year Treasury: the recent rise is mostly real yield; implied inflation sits steady a bit above 2% and she expects it to break down.",
            "Bond market confusion: 40 years of decelerating nominal GDP and falling rates are now reversing — bad for bondholders, good news for growth.",
        ],
        "quote": {"text": "We think we're back into a situation where the market is working and this Fed I think is going to be very good for all of us.", "cite": "— Cathie Wood"},
        "watch": "Wood paraphrases Ackman's tweet only briefly; his full argument isn't shown.",
        "names": None,
    },
    {
        "id": "inflation-rolling-over",
        "tags": ["macro-rates"],
        "color": "green",
        "badge": "High conviction",
        "status": "WATCHING WHAT FED CHAIR WARSH WATCHES",
        "title": "The inflation gauges Warsh watches are already rolling over",
        "lead": "Headline PCE still looks high, but private measures, the diffusion index and money velocity all point lower.",
        "bullets": [
            "Headline PCE revised down from 3.7% to 3.4% year over year; core is a bit lower, but Warsh says he's fixated on headline — \"a long way from 2%.\"",
            "Truflation (a private measure Warsh also watches): headline up to ~2.7%, largely oil, while core keeps falling toward pre-COVID averages.",
            "Fed **diffusion index** (share of categories rising 0.3% or more): the six-month line is reversing and should pull the annual one down.",
            "Money growth ~5.7%, but a four-year view shows low-single-digit M growth not accommodating federal outlays, which are rising mostly on defense.",
            "Velocity keeps falling; its closest match is labor participation, which peaked in the late 90s — boomers retiring and immigrants leaving keep it flat.",
            "Yield curve couldn't regain 200-300bp steepness even with COVID stimulus; it reached ~75bp and is now in the 40s — Treasuries \"sniffing out deflationary undercurrents\" (TIPS don't show it yet).",
        ],
        "quote": None,
        "watch": "Headline PCE at 3.4% is still well above the 2% target, and the Fed had been talking hawkish until this report.",
        "names": None,
    },
    {
        "id": "tech-deflation-gdp",
        "tags": ["ai-infra", "macro-rates"],
        "color": "green",
        "badge": "High conviction",
        "status": "FORECAST — 7-8% REAL GDP GROWTH, FIVE YEARS TO 2030",
        "title": "AI cost collapse: 99.99% a year cheaper, revenue exploding anyway",
        "lead": "Falling prices plus exploding volume is \"good deflation\" — the microcosm Wood expects across the whole economy.",
        "bullets": [
            "Wright's law in genome sequencing: every cumulative doubling cuts cost by 40%.",
            "AI inference at fixed performance is getting cheaper by 99.99% per year — far steeper than sequencing.",
            "**Jevons paradox**: OpenAI's annualized run rate went from $20B at end of last year to $70B, past Anthropic's reported $65B for July (\"probably neck and neck\").",
            "Brett Winton's convergence chart: 15 technologies across five platforms; AI now links to blockchain through agentic payments, agentic commerce, Grok bot, Muse and OpenAI's bots.",
            "Global real GDP grew ~0.6% a year in 1500-1600 (maybe refined to 0.5%); the industrial revolution took it to 3% — a fivefold jump.",
            "ARK's forecast: 7.3% (7-8%) real GDP growth for the five years ending 2030, vs. the IMF's 3% (now ~2.5%); update in Big Ideas, out in January.",
            "Productivity growth should reach 5-6%+, replaying the PC, software and wireless upswing of the 80s-90s; corporate profitability could hit all-time highs.",
        ],
        "quote": {"text": "This is a technology revolution and we think it's bigger than the industrial revolution.", "cite": "— Cathie Wood"},
        "watch": "ARK's funds are concentrated in the innovation platforms this forecast depends on.",
        "names": [
            {"name": "OpenAI", "blurb": "Run rate from $20B to $70B despite collapsing inference prices.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Anthropic", "blurb": "$65B run rate reported for July; likely higher now, neck and neck with OpenAI.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "xAI", "blurb": "Named (as SpaceX AI) among the companies riding AI volume growth.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "strong-dollar",
        "tags": ["macro-rates", "geopolitics"],
        "color": "green",
        "badge": "High conviction",
        "status": "CALL — DOLLAR BACK TO ALL-TIME HIGHS",
        "title": "American exceptionalism isn't done: the dollar heads back to its highs",
        "lead": "Business-friendly policy and the US-led AI capex boom raise US returns on capital, pulling the dollar up as in the early 1980s.",
        "bullets": [
            "Early-80s analog: tax cuts and deregulation lifted US return on invested capital and the dollar soared.",
            "Bloomberg: 90% of global data center financing (by fixed-income metrics) is in the United States.",
            "Effective corporate tax rate ~8%, lowest in the world, via 100% first-year depreciation on new factories and data centers — refunds get reinvested.",
            "DXY (six currencies) sits near the high end of its range; the Fed's real trade-weighted dollar (26 countries) is near all-time highs.",
            "**Kalshi** DXY market: DXY started near 98 and is now just above 100; bettors always priced above 100, starting at 103-105.",
            "A strong dollar is \"a powerful anti-inflationary force\" since most commodities are priced in dollars.",
        ],
        "quote": None,
        "watch": "ARK partners with Kalshi and plans more economic markets with it.",
        "names": [
            {"name": "Kalshi", "blurb": "Prediction market ARK is partnering with; its DXY market called the dollar's rebound.", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": None},
        ],
    },
    {
        "id": "gold-oil-bitcoin",
        "tags": ["energy", "crypto", "macro-rates"],
        "color": "green",
        "badge": "High conviction",
        "status": "CALLS — OIL $30-35 · GOLD DOWN · BTC/GOLD TURNED",
        "title": "Gold peaked with Warsh, oil goes to $30-35, Bitcoin breaks from gold",
        "lead": "Disciplined money and technology shrink the two assets that thrived on monetary accommodation — while Bitcoin decouples.",
        "bullets": [
            "Gold shows 15-20 years of bad monetary policy; Wood suspects **Volcker and Greenspan** quietly used the gold price as a policy indicator.",
            "Gold peaked the day or day after Trump appointed Kevin Warsh Fed chair and has fallen since; she expects more declines as he imposes a price-rule discipline.",
            "Oil has \"levitated\" for 20-25 years on easy money; 57% of oil goes to transportation, which is shifting to electric (China and Europe first, US following).",
            "Oil to the $30-35 range, as in past crises — this time driven by a technology shift instead.",
            "S&P-to-oil is still near a high even with oil at $90-100; S&P-to-gold signaled the 1966-1982 bear market and she expects it to reach all-time highs.",
            "Bitcoin-to-gold has turned up; correlation since 2019 is 0.1 and recently negative, despite the \"digital gold\" label.",
            "Metals-to-gold hasn't turned, held down by weak China data.",
        ],
        "quote": None,
        "watch": "ARK holds Bitcoin exposure in its funds.",
        "names": [
            {"name": "Gold", "blurb": "Peaked when Warsh was named Fed chair; expected to keep falling.", "stance": "NEGATIVE VIEW", "conviction": "High", "horizon": None},
            {"name": "Oil", "blurb": "Demand peaking as transport electrifies; target $30-35.", "stance": "NEGATIVE VIEW", "conviction": "High", "horizon": None},
            {"name": "Bitcoin (BTC)", "blurb": "Bitcoin-to-gold has turned up; near-zero to negative correlation with gold.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "rolling-recession",
        "tags": ["macro-rates", "consumer", "policy"],
        "color": "amber",
        "badge": "Mixed",
        "status": "EMPLOYMENT FRIDAY — MANUFACTURING OUT, HOUSING STUCK",
        "title": "Through the rolling recession: factories recover, housing and autos don't",
        "lead": "Inverted curves no longer guarantee recession; the economy rotated through sector slumps without a full one.",
        "bullets": [
            "Industrial-revolution curves were inverted >60% of the time by ~100bp; post-1913 inversions meant recession, but after the Fed's 22-24-fold hike in 16 months only housing, manufacturing, small business and lower-income consumers slumped.",
            "Payrolls much weaker than expected, household employment +400k+, flat year over year; unemployment 4.2%, but 9.9% for 16-24 year olds.",
            "Sentiment terrible (Michigan, now Conference Board); diesel ~$6.50; hourly earnings +0.1% (3% YoY), likely tech-job mix shift — she expects a labor shortage later.",
            "Housing: existing sales \"still in a recession,\" mortgages above 7%, new-home inventory near all-time highs, builders cutting prices; savings rate low.",
            "Manufacturing is out of recession; non-defense capex ex-aircraft is booming after a long base since the tech-telecom bust.",
            "Trade deficit widening (imports +2.8%, exports -2.2%) — the flip side is a capital surplus and more foreign direct investment.",
            "Autos: China builds 30-35M a year but consumption fell from ~30M to ~19M; US sales below 16M in September — Uber/Lyft affordability means secular peak.",
        ],
        "quote": {"text": "Go out, start your own company with AI, no employees, solve a problem, keep interviewing, and you'll go to the head of the class.", "cite": "— Cathie Wood, to new graduates"},
        "watch": None,
        "names": [
            {"name": "Uber (UBER)", "blurb": "Ride-hailing affordability cited as a reason US auto sales have peaked.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Lyft (LYFT)", "blurb": "Cited alongside Uber for the auto-sales peak.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "debt-credit-ai-policy",
        "tags": ["finance", "policy", "ai-infra"],
        "color": "amber",
        "badge": "Contested",
        "status": "WATCH — HYPERSCALER CDS WIDENING",
        "title": "Debt fears overdone, but hyperscaler credit is starting to crack",
        "lead": "Government debt and systemic credit look less dire than headlines say; the new stress point is AI capex financed with debt.",
        "bullets": [
            "Deficit in the mid-5s % of GDP; she agrees with **Scott Bessent** it reaches 3% by the end of this term, as under Reagan and then Clinton.",
            "$40T of government debt exceeds GDP, but debt-to-equity (balance sheet vs. balance sheet) is nearer historic lows; she still wants spending cut, defense excepted.",
            "Bank CDS very low — no systemic risk even with private credit \"in a difficult moment\"; high-yield spreads low with a small uptick.",
            "Hyperscalers, long \"cash fortresses,\" now tap debt markets; their CDS are deteriorating, high-yield names more than investment grade — neoclouds a big part, Oracle possibly too.",
            "AI equities have decoupled from Kalshi odds of Republicans keeping Congress — losing it would only mean gridlock.",
            "AI policy: Trump scrapped Biden's AI executive order; after the Hugging Face incident and recent hacks, the line is self-regulate, with LLM companies liable if something goes badly wrong.",
        ],
        "quote": {"text": "Government spending is taxation, period, either now or in the future or through inflation.", "cite": "— Cathie Wood"},
        "watch": "She isn't sure whether Oracle was actually downgraded.",
        "names": [
            {"name": "Oracle (ORCL)", "blurb": "Possibly among the names pushing hyperscaler credit spreads wider.", "stance": "UNCERTAIN", "conviction": "Low", "horizon": None},
            {"name": "Hugging Face", "blurb": "A security incident there sparked this week's AI-regulation debate.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F4C9", "tag": "Macro", "title": "Split every rate move into real yield vs. breakeven before reading it as an inflation scare."},
    {"icon": "\U0001F9ED", "tag": "Fed", "title": "Track the PCE diffusion index and Truflation core — Wood's leading read on where Warsh moves next."},
    {"icon": "\U0001F6E2️", "tag": "Commodities", "title": "Stress-test commodity and energy exposure against her $30-35 oil and falling-gold scenario."},
    {"icon": "\U0001F4B3", "tag": "Credit", "title": "Watch hyperscaler and neocloud CDS as the first crack in debt-financed AI capex."},
    {"icon": "\U0001F393", "tag": "Careers", "title": "New grads facing 9.9% youth unemployment: build an AI-native solo venture while you keep interviewing."},
]

HOT_TAKES = [
    {"take": "We would not be surprised to see deflation, especially if oil prices crack the way we expect them to.", "cite": "— Cathie Wood", "why": "Deflation call with PCE at 3.4%."},
    {"take": "We do believe that the oil price could drop into the 30 to $35 range.", "cite": "— Cathie Wood", "why": "Numeric oil target."},
    {"take": "What we did expect for the five years ended in 2030: 7.3%... most people think that's crazy.", "cite": "— Cathie Wood", "why": "Real GDP call vs IMF 2.5-3%."},
    {"take": "A lot of the narratives out there would suggest that the dollar is done and American exceptionalism is done. We disagree.", "cite": "— Cathie Wood", "why": "Contrarian dollar call to all-time highs."},
    {"take": "The gold price peaked the day or the day after President Trump appointed Kevin Warsh to be Fed chairman, and we would not be surprised to see it continue to decline.", "cite": "— Cathie Wood", "why": "Bearish gold call."},
    {"take": "I think auto sales have peaked secularly just like we think oil prices have peaked secularly.", "cite": "— Cathie Wood", "why": "Secular peak calls."},
]

CLAIMS = [
    {"who": "Cathie Wood", "claim": "Global real GDP growth averages 7-8% for the five years ending 2030.", "metric": "global real GDP growth", "target": "7.3%", "by": "2030", "condition": None, "entity": None},
    {"who": "Cathie Wood", "claim": "Oil falls into the $30-35 range as transportation electrifies.", "metric": "oil price", "target": "$30-35", "by": None, "condition": None, "entity": "Oil"},
    {"who": "Cathie Wood", "claim": "Gold continues to decline as Warsh disciplines monetary policy.", "metric": "gold price", "target": "lower", "by": None, "condition": None, "entity": "Gold"},
    {"who": "Cathie Wood", "claim": "The Fed's real trade-weighted dollar returns to all-time highs.", "metric": "real trade-weighted dollar", "target": "all-time high", "by": None, "condition": None, "entity": None},
    {"who": "Cathie Wood", "claim": "Inflation falls far below expectations, possibly into deflation.", "metric": "inflation", "target": "deflation possible", "by": None, "condition": "especially if oil prices crack", "entity": None},
    {"who": "Cathie Wood", "claim": "Productivity growth accelerates into the 5-6%+ range.", "metric": "US productivity growth", "target": "5-6%+", "by": None, "condition": None, "entity": None},
    {"who": "Cathie Wood / Scott Bessent", "claim": "The federal deficit falls from the mid-5s to 3% of GDP by the end of this presidential term.", "metric": "federal deficit / GDP", "target": "3%", "by": "2029-01", "condition": None, "entity": None},
    {"who": "Cathie Wood", "claim": "The S&P-to-gold ratio rises to all-time highs.", "metric": "S&P 500 / gold ratio", "target": "all-time high", "by": None, "condition": None, "entity": "Gold"},
    {"who": "Cathie Wood", "claim": "Corporate profitability reaches all-time highs on AI productivity gains.", "metric": "domestic profitability", "target": "all-time high", "by": None, "condition": None, "entity": None},
    {"who": "ARK Invest", "claim": "Big Ideas publishes with an updated global GDP chart.", "metric": "Big Ideas report", "target": "published", "by": "2027-01", "condition": None, "entity": None},
]

RELATIONS = [
    {"from": "ARK", "rel": "partners_with", "to": "Kalshi", "note": "contributing ideas for new prediction markets"},
    {"from": "OpenAI", "rel": "competes_with", "to": "Anthropic", "note": "neck and neck on revenue run rate"},
]

OTHER_NEWS = [
    {"icon": "\U0001F4DA", "title": "Sources cited: Bill Ackman's tweet, Bloomberg (data center financing), Fed data (real trade-weighted dollar), the IMF growth forecast, Kalshi markets, and ARK's own Nick Grous and Brett Winton.", "tag": "Sources"},
]

GLOSSARY = [
    {"term": "PCE inflation", "def": "The Fed's preferred price index; headline includes food and energy, core excludes them."},
    {"term": "Truflation", "def": "A private, high-frequency inflation index Wood says Warsh also watches."},
    {"term": "Diffusion index", "def": "Share of inflation categories rising 0.3% or more, a breadth read on price pressure."},
    {"term": "Velocity of money", "def": "How often money turns over in the economy; falling velocity mutes inflation from money growth."},
    {"term": "Wright's law", "def": "Costs fall by a fixed percentage for every cumulative doubling of units produced."},
    {"term": "Jevons paradox", "def": "Cheaper resources drive so much more usage that total spending rises."},
    {"term": "Real vs. breakeven yield", "def": "A Treasury yield split into inflation-adjusted return and market-implied inflation (from TIPS)."},
    {"term": "Gold window", "def": "Dollar-to-gold convertibility for foreign governments, closed in 1971."},
    {"term": "DXY", "def": "Dollar index against six major currencies; the Fed's broader real trade-weighted index uses 26."},
    {"term": "Rolling recession", "def": "Sectors contract in turn (housing, manufacturing, small business) without a whole-economy recession."},
    {"term": "Credit default swap (CDS)", "def": "Insurance against a borrower's default; rising CDS prices mean credit deteriorating."},
]
