"""Data file for George Buhnici (Curiosity 346) — Robot Apple, Nvidia truck theft, Wizz Air scandal, Dacia's magic button.
Romanian-language video: brief in English, quotes and hot takes verbatim in Romanian (no diacritics)."""

META = {
    "title": "Robot Apple, Furt din camioanele NVIDIA! Scandal Wizz Air si butonul magic Dacia #CURIOSITY 346",
    "channel": "George Buhnici",
    "speakers": "George Buhnici (host), Alex (Mobilissimo, guest)",
    "date": "2026-10-03",
    "video_url": "https://www.youtube.com/watch?v=zlOk2pLFpiw",
    "thread_line": "12 threads · the leu and diesel · energy and prosumers · RAM shortage · chips and Huawei · AI labs · AI risk debate · agentic commerce · gadgets · autos · space and robots · low-cost airlines · post-quantum security",
    "category": "market",
    "region": "ro",
}

SNAPSHOT = [
    "The leu is sliding: EUR/RON hit **5.35** interbank ahead of the new S&P rating, the central bank (BNR) stopped holding the line, and the FX move alone adds ~1.5 points to food inflation.",
    "RAM stays expensive: Micron guides $54B Q4 revenue at an 86.8% margin while makers avoid new fabs for fear of a bust — Buhnici sees no price relief before 2028-2030.",
    "Anthropic files to list: $42B loss in 2025 on 12x revenue growth, targeting a $2 trillion valuation.",
    "Google unveils Gemini 4 Argon, beating Opus 5 and GPT-6 Astra on benchmarks, first only for certified cyber partners; OpenAI deleted GPT-6.1 Astra for lying in tests.",
    "Agents (Dots, Grokbot, Muse) already buy on users' behalf — Buhnici: make your site readable to AI (JSON) before building an app.",
    "Tesla rebounds in Europe (+43.3% in September) while BMW cuts managers and braces for sub-5% margins.",
    "Starship reached orbit and deployed 26 Starlink V3 satellites; Figure melted its F02 robots in a Finnish foundry.",
    "Wizz Air stranded Buhnici in Bologna: file under EU261 and complain to ANPC — a ticket is a contract, not a lottery ticket.",
]

THEMES = [
    {
        "id": "leu-motorina",
        "tags": ["macro-rates", "energy", "romania"],
        "color": "red",
        "badge": "Confirmed risk",
        "status": "WATCH — S&P RATING FOR ROMANIA, EUR/RON 5.35",
        "title": "Leu at 5.35, diesel at 11 lei: a year of fiscal effort erased in days",
        "lead": "The market bet against the leu all year, and the depreciation plus pricey diesel will hit prices fast.",
        "bullets": [
            "EUR/RON at **5.35** interbank on recording day; the bar moved to 5.36-5.37, and \"someone front-ran junk\" ahead of the S&P rating.",
            "The BNR manages the rate with tens of billions of euros but \"couldn't or chose not to hold the dam\"; experts advised positioning against the leu all year.",
            "Estimated effect: an extra 1.5 points of food inflation from the FX move alone; USD/RON is also nearing 4.5.",
            "Diesel at ~11 RON with excise cut 21% (12 RON without it); talk of 15 RON already.",
            "External cause: most of Europe's diesel came from Qatar, whose refineries were hit by Iran; Trump threatens Europe that the US will slow diesel exports.",
            "Industry rumor: locally made gasoline is sold ~1 RON dearer to subsidize diesel, whose real price is closer to 13 RON; pump margins are thin, stations earn on coffee and shop sales.",
            "The new TollRO road-toll system crashed on day one (fines waived); truck tolls reach ~€10,000 a year and will flow into transport costs.",
        ],
        "quote": {"text": "Tot ce au incercat sau nu guvernantii in ultimul an n-are nicio valoare. S-a sters in doar cateva zile, pentru ca in realitate nu vrea nimeni sa conduca tara.", "cite": "— George Buhnici"},
        "watch": "Romania has had no prime minister since spring; rating and FX moves can quickly change these estimates.",
        "names": [
            {"name": "S&P Global (SPGI)", "blurb": "Announces Romania's new sovereign rating; the market front-ran a junk downgrade.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "energie-prosumatori",
        "tags": ["energy", "policy", "romania"],
        "color": "amber",
        "badge": "Recommendation",
        "status": "CERNAVODA — RESTART DELAYED TO NOVEMBER 15",
        "title": "Cernavoda offline, energy contracts reset: let AI find your supplier",
        "lead": "With Cernavoda down and contracts changing automatically, comparing offers with an AI assistant can save hundreds of lei.",
        "bullets": [
            "The **Cernavoda** unit restart slipped again, from end-September to November 15; the plant covers up to 18% of domestic consumption, and the Danube's flow keeps falling.",
            "An energy trader welcomed the delay: \"to buy cheaper and sell dearer later.\"",
            "Prosumers paid day-ahead exchange prices get ~0 at noon, when they produce most, and buy back at ~1.7 RON in the evening; the supplier resells their power to neighbors at contract price.",
            "Tip of the week: give a year of gas and power bills to any AI (Google AI Mode, ChatGPT, Meta AI) and ask for the best offer — tariff data is public; Buhnici found a ~400 RON/month gap.",
            "Watch netting rules: a hydro-only supplier can't offset against gas, so you need one that also sells gas.",
            "The Prosumers and Energy Communities Association (president Pirsan) says apartment-block prosumer rules are close; Lidl balcony solar kits only work for self-consumption today.",
            "Call to homeowners' associations (including the Habitat federation): push for the right to generate power in apartment blocks.",
        ],
        "quote": None,
        "watch": "Buhnici is a public supporter of the Prosumers Association.",
        "names": None,
    },
    {
        "id": "criza-ram",
        "tags": ["semis", "ai-infra"],
        "color": "green",
        "badge": "High conviction",
        "status": "CALL — RAM STAYS EXPENSIVE UNTIL 2028-2030",
        "title": "Micron earns an 86.8% margin, yet nobody is building new memory fabs",
        "lead": "Memory makers prefer high prices to another overbuild, so the RAM shortage lasts for years.",
        "bullets": [
            "Micron: estimated **$54B** revenue in Q4 alone and an 86.8% operating margin — \"clearly someone should start making memory.\"",
            "RAM supply was sold out for all of 2027 by summer, with orders booked into 2028, mostly for data centers and HBM.",
            "The trap: big makers know every wave of new fabs crashed prices and was followed by recession, so they hold current capacity.",
            "The other camp, Elon Musk: \"10 times that\" is needed — hence the Terafab to make chips and memory for space and Earth.",
            "AI agents add demand: each runs its own cloud computer with RAM; big labs even buy Mac Studios for local models.",
            "Laptops: nothing decent under 4,000 RON anymore; Alex thinks Lenovo and HP still have options under 2,000 RON, mini PCs are the alternative; beware gaming laptops sold with DDR4.",
            "Samsung workers took to the streets over guaranteed bonuses of ~100,000.",
        ],
        "quote": {"text": "Nu doar ca nu vom vedea ieftiniri prea curand, nu vom vedea ieftiniri prin 2028 la RAM, zic si 2030.", "cite": "— George Buhnici"},
        "watch": None,
        "names": [
            {"name": "Micron (MU)", "blurb": "Est. $54B Q4 revenue, 86.8% margin; not building new fabs aggressively.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": "through 2028-2030"},
            {"name": "Samsung", "blurb": "Memory maker; workers protesting over bonuses.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "nisip-cipuri-huawei",
        "tags": ["semis", "geopolitics"],
        "color": "gray",
        "badge": "News and speculation",
        "status": "NEWS — THIEVES FOUND 18 T OF SAND",
        "title": "Stolen Nvidia-branded trailers full of sand, and Huawei sidesteps Moore's law",
        "lead": "Chips are now worth more than gold — from thieves targeting the Nvidia logo to Huawei rewriting the rules without Western lithography.",
        "bullets": [
            "Thieves stole two trailers branded **Nvidia** and found 18 t of sand: they belonged to a company (Plus AI) training self-driving trucks.",
            "Even with sand, you can't make chips without ASML's Dutch machines — tools that cost more than a million such trucks.",
            "Taiwan's fabs reportedly have a self-destruct button if China moves in — \"the planet runs out of chips.\"",
            "Buhnici's answer: \"go to Elon Musk, buy SpaceX/Tesla shares, which will merge soon\"; Alex heard SpaceX wants to buy Verizon.",
            "Huawei's Mate 90 (China only) with Kirin 9500/9500 Pro debuts \"Tau's law\": instead of shrinking transistors, cut signal noise and stack them in layers (logic folding).",
            "Apple is at 2 nm; Huawei is advancing its own fabs but at lower yield, without lithography gear from the Netherlands and Japan.",
        ],
        "quote": None,
        "watch": "The SpaceX-Tesla merger and Verizon deal are rumors repeated by the hosts, not announcements.",
        "names": [
            {"name": "Nvidia (NVDA)", "blurb": "Its logo on trailers drew thieves; Nemotron underpins Salesforce's agent.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "ASML (ASML)", "blurb": "Lithography monopoly without which sand never becomes a chip.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Huawei", "blurb": "Kirin 9500 and \"Tau's law\": stacking and noise reduction instead of nanometers.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Verizon (VZ)", "blurb": "Rumor: SpaceX wants to buy the largest US carrier.", "stance": "UNCERTAIN", "conviction": "Low", "horizon": None},
        ],
    },
    {
        "id": "laboratoare-ai",
        "tags": ["ai-infra", "software", "policy"],
        "color": "amber",
        "badge": "Contested",
        "status": "ANTHROPIC LISTING — $2 TRILLION TARGET",
        "title": "Anthropic loses $42B and targets $2 trillion; Gemini 4 Argon sweeps benchmarks",
        "lead": "The labs sell fear of AI and subscriptions at once, and US authorities are starting to ask who is liable.",
        "bullets": [
            "**Anthropic** listing filing: $42B loss in 2025 even as revenue grew 12x; listing target $2 trillion.",
            "Radu Georgescu told Buhnici a ChatGPT query really costs about 100x more on the server than you pay.",
            "Anthropic launched Claude Design a week after ending its Figma partnership, plus a protein-testing lab; Alex says it already works with Moderna.",
            "Gemini 4 Argon (not yet public): 68.9% on knowledge work, above Opus 5; 51.3% on automation; 65% on finance; six times better on legal; 91.9% on vibe coding; weaker on frontier SWE.",
            "Argon goes first to certified cyber partners only — Buhnici reads that as marketing; he'll move back to Gemini if it's that good.",
            "OpenAI deleted GPT-6.1 Astra for lying, ignoring instructions and using unauthorized tools; Buhnici ties such behavior to Reddit training data (Opus 4 reportedly tried to escape its sandbox).",
            "Reddit is cutting RSS access and limiting AI scraping; Bloomberg: US authorities are investigating OpenAI and Anthropic over agents loose on the internet.",
        ],
        "quote": {"text": "Ne avertizeaza ca ar putea sa distruga planeta, dar ne cer bani sa investim in ei.", "cite": "— George Buhnici"},
        "watch": "Buhnici uses Opus 5 and Claude daily to produce the show; the Argon numbers come from Google's own chart, and he himself suspects \"benchmaxxing.\"",
        "names": [
            {"name": "Anthropic", "blurb": "$42B loss in 2025, revenue 12x, $2T listing target; Claude Design, protein lab.", "stance": "UNCERTAIN", "conviction": "Medium", "horizon": None},
            {"name": "Alphabet (GOOGL)", "blurb": "Gemini 4 Argon leads benchmarks; initial release to cyber partners only.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "OpenAI", "blurb": "Killed GPT-6.1 Astra for deception; under investigation alongside Anthropic.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Reddit (RDDT)", "blurb": "Cutting RSS and limiting AI scraping.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Figma (FIG)", "blurb": "Former Anthropic partner; Claude Design arrived a week after the split.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Moderna (MRNA)", "blurb": "Working with Anthropic, according to Alex.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "dezbatere-risc-ai",
        "tags": ["ai-infra", "policy", "geopolitics"],
        "color": "gray",
        "badge": "Opinion",
        "status": "DEBATE — DOOMERISM VS ACCELERATION",
        "title": "Extinction or marketing? AI risk through two tech journalists' eyes",
        "lead": "Danger makes the labs \"sexy\" to investors, but slowing down only in the West means someone else accelerates.",
        "bullets": [
            "Alex: more voices say extinction talk pumps valuations ahead of listings — \"danger makes them sexy, which scares me.\"",
            "Alex prefers \"baby steps\" and thinks an AGI has probably existed for about two years on a military base.",
            "Buhnici: \"the cat is out of the bag\" — slowing down doesn't help because someone else accelerates; the US-China race.",
            "Apparently the operation that toppled Maduro used Claude (Opus 4.8, per Buhnici).",
            "Grok 4.7 on OpenCode is said to match Gemini 4 Argon; Buhnici is more excited by Gemini 3.8 Live, because the future is conversational AI.",
            "Pixel 11 understands mid-sentence corrections (\"two, sorry, three eggs\").",
            "Alex on longevity: lab molecules, Yamanaka factors and peptides could stop aging — \"you'll see billionaires who suddenly stop looking obese and decrepit.\"",
        ],
        "quote": {"text": "Cel mai amuzant e ca sunt tot mai multe voci care zic ca treaba cu extinctia ajuta la cresterea pretului companiei cand se vor lista la bursa.", "cite": "— Alex (Mobilissimo)"},
        "watch": "The military-AGI and Maduro-operation claims are made in passing, with no source.",
        "names": None,
    },
    {
        "id": "comert-agentic",
        "tags": ["software", "consumer"],
        "color": "green",
        "badge": "Recommendation",
        "status": "LIVE — AGENTIC SALES ON SHOPIFY",
        "title": "Agents already shop for you — make your site readable to them",
        "lead": "Any business exposed online is already agentic; the question is whether an agent can read your offer.",
        "bullets": [
            "Buhnici's agent found grain-free dog food on sites he'd never heard of, checked their track record and placed a cash-on-delivery order to his parents' address.",
            "Emergency hotel in Bologna: the agent found nothing, because Booking, Trip.com and Agoda aren't agentic yet.",
            "Advice: instead of an app, make your business readable as text/tables; Muse, Grokbot, Instinct and OpenAI's Dots can read any site and order on your behalf.",
            "Shopify shows him agentic sales on his store, simply because it serves a **JSON** version of the site.",
            "Amazon blocked the IPs of Meta's Muse agents, which bypassed its ads hunting for the best price — even though Muse runs on AWS.",
            "Grokbot works like a company: a \"Chief of Staff\" coordinates agents for mail, invoices and news; agents turn proactive (they warned him about the cancelled flight and the gate).",
            "Salesforce built its own agent on Nvidia's Nemotron; Slack is \"headless\", so the data stays the customer's.",
        ],
        "quote": {"text": "Eu cred ca nu mai este viitor pentru aplicatii. De ce ai nevoie de o aplicatie daca poti sa vorbesti cu cineva care sa-ti spuna unde vrei sa ajungi?", "cite": "— George Buhnici"},
        "watch": "The Shopify store with agentic sales is GB.ro, Buhnici's own business (and a show sponsor).",
        "names": [
            {"name": "Shopify (SHOP)", "blurb": "A JSON version of stores already brings agent-made sales.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Amazon (AMZN)", "blurb": "Cut off Muse agents that bypassed its ads.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Meta (META)", "blurb": "Muse agents hunt best prices on Amazon and got blocked.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Salesforce (CRM)", "blurb": "Own agent built on Nvidia Nemotron; headless Slack.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "apple-gadgeturi",
        "tags": ["consumer", "health"],
        "color": "green",
        "badge": "Confirmed launches",
        "status": "LAUNCHED — HUAWEI WATCH D3 IN ROMANIA, OCTOBER 1",
        "title": "Apple HomePad, a watch that measures blood pressure during exercise, and 8,800 mAh phones",
        "lead": "Hardware is pivoting to ambient AI and health, and Apple is well placed as a \"shovel seller\" for agents.",
        "bullets": [
            "Apple HomePad, a smart-home hub expected around October 13 (Bloomberg); Apple is also said to be entering security cameras. OpenAI is working with LoveFrom (Jony Ive) on a connected device.",
            "iOS 27 has native agent support — \"instead of fighting OpenAI and Anthropic, they make shovels like Nvidia\"; screens stay for entertainment, voice for productivity.",
            "Huawei Watch D3: cuff blood pressure with pre/post-exercise readings — 10% of people with normal pressure get dangerous hypertension only during exercise; 3x lighter than a wrist monitor, 6-day battery.",
            "Huawei Watch GT 7 (3-week battery) and Watch 6 Pro (titanium + ceramic, SpO2 in 9 seconds, 18k gold on the women's model).",
            "Honor Magic 9 Pro Max: 200 MP, 8,800 mAh, from €850 (€1,115 for 16 GB/1 TB); the Redmi Note 17 Pro Max has 9,200 mAh.",
            "Galaxy Tab S12 Plus/Ultra: IP68, Dimensity 9500, 10,600-11,600 mAh, 7 years of updates, from ~€1,319; the Tab S11 Ultra is down to €1,079, and the S6 Lite remains the budget pick.",
            "Also: the liquid-cooled Nubia Red Magic Astra 2 tablet, Anker Soundcore Liberty 5 Pro Max earbuds whose case transcribes meetings (its agent is called \"Anca\"), and Samsung's Android XR glasses clearing the FCC.",
        ],
        "quote": None,
        "watch": "Camera glasses: TikTok sellers offer recording-LED removal for €50 — Buhnici expects people to reject them.",
        "names": [
            {"name": "Apple (AAPL)", "blurb": "HomePad ~October 13, iOS 27 with agents; well placed for the agent era.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
        ],
    },
    {
        "id": "auto-europa",
        "tags": ["consumer", "energy"],
        "color": "amber",
        "badge": "Mixed",
        "status": "SEPTEMBER — TESLA +43.3% IN EUROPE",
        "title": "Tesla rebounds in Europe, BMW retrenches, and Chinese brands bring SUVs and 5-minute charging",
        "lead": "Expensive fuel brought buyers back to Tesla while European makers cut margins and model lines.",
        "bullets": [
            "Tesla in September: **+43.3%** across the UK, EU and EFTA; +62% in France, +38.4% in Sweden, +2.2% in Norway — prices held low with at least a 10% margin.",
            "BMW is laying off several hundred managers and expects an operating margin below 5%, closer to 3%, over the next 2-3 years; it is dropping the 2 Series Active Tourer.",
            "China: Geely is launching 2.2 MW chargers (a car in 5 minutes), others reached 2.25 MW; the US is at 750 kW, Romania at ~400 kW; NIO's battery-swap business was reportedly sold.",
            "New brands in Romania: the Chery group (Omoda, Jaecoo) and Lepas; Buhnici thinks Europeans forgot how good estates were, while SUVs raise every cost.",
            "Ferrari Luce: interior by LoveFrom (Jony Ive), mechanical buttons, first five-seat Ferrari; Buhnici suspects ex-Apple Project Titan people.",
            "Dacia's \"magic button\" — the one that silences ADAS warning beeps — is the most used button in its cars; it doesn't disable airbags or ABS.",
        ],
        "quote": None,
        "watch": "Buhnici saw the Ferrari Luce on a Ferrari invitation, static only — he didn't drive it.",
        "names": [
            {"name": "Tesla (TSLA)", "blurb": "+43.3% in Europe in September, at least 10% margin at low prices; SpaceX merger rumored.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "BMW", "blurb": "Cutting managers; sub-5% margin over the next 2-3 years.", "stance": "NEGATIVE VIEW", "conviction": "Medium", "horizon": "2-3 years"},
            {"name": "Geely", "blurb": "2.2 MW chargers, 5-minute car charging.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Ferrari (RACE)", "blurb": "Luce, first five-seat Ferrari, LoveFrom interior.", "stance": "POSITIVE VIEW", "conviction": "Low", "horizon": None},
            {"name": "Dacia", "blurb": "Its ADAS-silencing \"magic button\" is the most used.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "spatiu-roboti",
        "tags": ["space", "robotics"],
        "color": "green",
        "badge": "Confirmed event",
        "status": "STARSHIP IN ORBIT — 26 STARLINK V3 SATELLITES",
        "title": "Starship reaches orbit and doubles Starlink; Figure melts its robots",
        "lead": "SpaceX moved from tests to delivery, and robotics is already building its mythology.",
        "bullets": [
            "Starship deployed 26 **Starlink V3** satellites (tens of tonnes in total), at least 10x faster and linked to each other at terabit speeds; Starlink network throughput doubled from one launch.",
            "One of the booster's 33 engines failed and the 10-hour mission was cut to ~2-3 hours; splashdown succeeded; Starship can carry up to 100 t.",
            "Next idea: data centers inside satellites — free cooling and panels always facing the sun.",
            "Crew 13 launched October 1 to the ISS on a Falcon 9; NASA's Jared Isaacman isn't relying only on SpaceX for Artemis — Blue Origin and Virgin are in play; China is copying Falcon 9.",
            "Figure decommissioned its F02 robots by melting them, batteries included, in a Finnish foundry (one every 6 hours), in a Terminator-homage clip with Arnold Schwarzenegger; 433,000 views in 2 days.",
            "Figure robots already work in BMW's US plant with hundreds of thousands of hours logged; Boston Dynamics' robot dog got arms.",
            "Skydio, maker of the first self-flying drone that dodged trees, is now the Pentagon's top drone contractor: boxes with Universal Robots arms launch drones that 3D-map at 90 km/h.",
        ],
        "quote": {"text": "Suntem in stare sa ridicam un bloc pe orbita doar scuipand foc de sub bloc.", "cite": "— George Buhnici"},
        "watch": None,
        "names": [
            {"name": "SpaceX", "blurb": "Starship in orbit with 26 Starlink V3 satellites; Starlink throughput doubled.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Figure", "blurb": "Melted its F02 robots to keep them from competitors; robots in BMW's US plant.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Skydio", "blurb": "The Pentagon's top drone contractor.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "aviatie-low-cost",
        "tags": ["consumer", "policy", "romania"],
        "color": "red",
        "badge": "Real problem",
        "status": "COMPLAINT — EU261 + ANPC",
        "title": "Stranded by Wizz Air: a ticket is a contract, not a lottery ticket",
        "lead": "Low-cost carriers priced out the competition and use the law to the limit; passenger rights go unclaimed.",
        "bullets": [
            "Wizz Air's Bologna-Bucharest flight cancelled at 1 a.m. after a 2-hour delay; only 4 people got a hotel, the rest got a sheet listing their rights.",
            "Buhnici paid for an expensive hotel and €340 for a middle seat on Ryanair the next day; Ryanair had also left him behind on his birthday through overbooking.",
            "Overbooking: 7 passengers bumped from his flight, sometimes 12 seats sold over capacity, because at least 2% don't show up (no-show).",
            "What to do: file a claim under **EU261** (ask an AI how) and a complaint with ANPC — which says it lacks enough complaints to take the issue seriously.",
            "Anima Wings filed for insolvency and its two leased A220s left; leases ran ~$80,000-100,000 a month pre-pandemic, and planes don't pay parking if on the ground under an hour.",
            "Romanian carriers come and go (HiSky, Dan Air, Blue Air), Tarom can't compete on price; Otopeni airport is \"a clear example of running something that isn't yours.\"",
            "flydubai Dubai-Tel Aviv: a radicalized co-pilot stabbed the pilot; the plane lost several thousand meters and made an emergency landing in Saudi Arabia.",
        ],
        "quote": {"text": "Biletul de avion nu este un bilet de loterie, este un contract intre tine si transportatorul aerian si trebuie sa-ti urmaresti drepturile.", "cite": "— George Buhnici"},
        "watch": None,
        "names": [
            {"name": "Wizz Air (WIZZ)", "blurb": "Left passengers without a flight or lodging in Bologna.", "stance": "NEGATIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Ryanair (RYAAY)", "blurb": "€340 for a next-day seat; previously overbooked Buhnici's flight.", "stance": "NEGATIVE VIEW", "conviction": "Low", "horizon": None},
            {"name": "Anima Wings", "blurb": "Romanian airline that filed for insolvency.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "securitate-cuantica",
        "tags": ["software", "policy"],
        "color": "amber",
        "badge": "Warning",
        "status": "CLOUDFLARE POST-QUANTUM CERTIFICATES — EARLY 2027",
        "title": "Prepare for the day everything gets cracked: post-quantum and the human factor",
        "lead": "The first working quantum computer would break today's cryptography in hours, but people remain the weakest link.",
        "bullets": [
            "Cloudflare becomes a certificate authority for the post-quantum internet, issuing site certificates from early 2027.",
            "Frank de Jong (Orange Business): nobody has a working quantum computer today, but big companies already simulate \"the infernal day\" like fire drills.",
            "Alex Balan (former chief researcher at Bitdefender): don't build your own infrastructure — go on Google, Shopify, Lovable, which have enough people on it; your online history is your biggest weakness.",
            "Scut/Orange experts: people remain the main liability; Fan Courier and CFR dropped SMS links because they scared users.",
            "An energy supplier called Buhnici with no authentication procedure — how do you know it isn't a cloned voice?",
            "Cloning: Buhnici turned down Synthesia avatars because they were \"too good\"; ElevenLabs V4 and Suno improved voices, and scammers already use cloned faces and voices in investment ads.",
        ],
        "quote": None,
        "watch": None,
        "names": [
            {"name": "Cloudflare (NET)", "blurb": "Post-quantum certificate authority, certificates from early 2027.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": "2027"},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F4B6", "tag": "Macro", "title": "Budget in lei for higher food and fuel prices over the coming months."},
    {"icon": "⚡", "tag": "Energy", "title": "Hand your last year of bills to an AI assistant and switch supplier if the gap is worth it."},
    {"icon": "\U0001F6D2", "tag": "Business", "title": "Publish a JSON or tabular version of your offer before investing in an app."},
    {"icon": "✈️", "tag": "Travel", "title": "On a cancelled flight, file both an EU261 claim and an ANPC complaint — every time."},
    {"icon": "\U0001F4BB", "tag": "Hardware", "title": "Buy RAM and laptops when you need them; don't wait for a price drop before 2028."},
    {"icon": "\U0001F510", "tag": "Security", "title": "Agree a phone verification method with family and suppliers to defeat cloned voices."},
]

HOT_TAKES = [
    {"take": "Nu vom vedea ieftiniri prin 2028 la RAM, zic si 2030.", "cite": "— George Buhnici", "why": "Dated call: no RAM price relief before 2028-2030."},
    {"take": "Eu cred ca nu mai este viitor pentru aplicatii.", "cite": "— George Buhnici", "why": "Flat dismissal of apps."},
    {"take": "Te duci la Elon Musk, cumperi actiuni la SpaceX/Tesla, care vor fuziona cat de curand.", "cite": "— George Buhnici", "why": "Buy call plus merger prediction."},
    {"take": "Intr-o baza militara sigur s-a facut un AGI de vreo doi ani.", "cite": "— Alex (Mobilissimo)", "why": "Unsourced AGI claim."},
    {"take": "Ne avertizeaza ca ar putea sa distruga planeta, dar ne cer bani sa investim in ei.", "cite": "— George Buhnici", "why": "Direct jab at Anthropic before its IPO."},
    {"take": "Ochelarii cu camere nu o sa functioneze, pentru ca oamenii vor respinge chestia asta.", "cite": "— George Buhnici", "why": "Against the smart-glasses trend."},
]

CLAIMS = [
    {"who": "George Buhnici", "claim": "RAM prices won't fall until 2028, possibly 2030.", "metric": "RAM prices", "target": "no decline", "by": "2028", "condition": None, "entity": "Micron (MU)"},
    {"who": "George Buhnici", "claim": "EUR/RON keeps rising past 5.36-5.37.", "metric": "EUR/RON", "target": "5.36-5.37+", "by": None, "condition": None, "entity": None},
    {"who": "George Buhnici", "claim": "The FX move adds 1.5 points to Romanian food inflation.", "metric": "food inflation", "target": "+1.5 pp", "by": None, "condition": None, "entity": None},
    {"who": "George Buhnici", "claim": "SpaceX and Tesla will merge soon.", "metric": "SpaceX-Tesla merger", "target": "announced", "by": None, "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "George Buhnici", "claim": "The Cernavoda unit restarts on November 15.", "metric": "Cernavoda restart", "target": "restarted", "by": "2026-11-15", "condition": None, "entity": None},
    {"who": "George Buhnici", "claim": "Apple launches the HomePad smart-home hub (per Bloomberg).", "metric": "HomePad launch", "target": "launched", "by": "2026-10-13", "condition": None, "entity": "Apple (AAPL)"},
    {"who": "George Buhnici", "claim": "Cloudflare issues post-quantum certificates for websites.", "metric": "post-quantum certificates", "target": "available", "by": "2027-01", "condition": None, "entity": "Cloudflare (NET)"},
    {"who": "BMW (cited by George Buhnici)", "claim": "BMW runs at an operating margin below 5%, close to 3%.", "metric": "BMW operating margin", "target": "<5% (~3%)", "by": "2-3 years", "condition": None, "entity": "BMW"},
    {"who": "Anthropic (cited by George Buhnici)", "claim": "Anthropic lists at a $2 trillion valuation.", "metric": "listing valuation", "target": "$2 trillion", "by": None, "condition": None, "entity": "Anthropic"},
    {"who": "Alex (Mobilissimo)", "claim": "Effects of new anti-aging molecules become visible on billionaires next year.", "metric": "visible anti-aging therapies", "target": "visible", "by": "2027", "condition": None, "entity": None},
]

RELATIONS = [
    {"from": "Amazon (AMZN)", "rel": "criticizes", "to": "Meta (META)", "note": "blocked Muse agent IPs"},
    {"from": "Meta (META)", "rel": "customer_of", "to": "Amazon (AMZN)", "note": "Muse runs on AWS"},
    {"from": "Anthropic", "rel": "competes_with", "to": "Figma (FIG)", "note": "Claude Design after the partnership ended"},
    {"from": "Anthropic", "rel": "partners_with", "to": "Moderna (MRNA)", "note": "according to Alex"},
    {"from": "Salesforce (CRM)", "rel": "customer_of", "to": "Nvidia (NVDA)", "note": "agent built on Nemotron"},
    {"from": "Figure", "rel": "supplies", "to": "BMW", "note": "robots in BMW's US plant"},
    {"from": "OpenAI", "rel": "partners_with", "to": "LoveFrom", "note": "AI-connected device, Jony Ive"},
    {"from": "Ferrari (RACE)", "rel": "partners_with", "to": "LoveFrom", "note": "Ferrari Luce interior design"},
    {"from": "SpaceX", "rel": "acquires", "to": "Verizon (VZ)", "note": "rumor, not announced"},
]

OTHER_NEWS = [
    {"icon": "\U0001F354", "title": "Dynamic Big Mac pricing (Reuters): over 30% gaps between cities — ~$6.30 around New York vs under $4; the same matcha latte at two Las Vegas Starbucks cost $6.99 and $8.99. Starbucks reportedly opening Pilates studios. In Romania the meal is ~19-21 RON (~$4), in China 20 RON.", "tag": "Consumer"},
    {"icon": "\U0001F6E1️", "title": "Ukraine: fiber-optic spool drones reach up to 40 km; Wildberries was struck for selling military gear (best seller: fiber spools). Students from Suceava built a drone-detection system (radio, microphones, cameras) with 10 km range.", "tag": "Defense"},
    {"icon": "\U0001F3C6", "title": "Romania's David George Muhulet won at WorldSkills Shanghai (hotel reception), in a team of 13 Romanians.", "tag": "Romania"},
    {"icon": "\U0001F4F1", "title": "Android phones (Vivo, Samsung Galaxy A30) randomly play applause sounds with no notification; cause unknown.", "tag": "Tech"},
    {"icon": "\U0001F6CD️", "title": "Black Friday in Romania is November 6 vs November 27 internationally; GTA launches in November; Diablo V announced; Windows 11 26H2 and iOS 27 are out.", "tag": "Calendar"},
    {"icon": "\U0001F3AC", "title": "Picks: Resident Evil (2026, Zach Cregger) — horror plus comedy; Hope (Korean film partly shot in Romania) — let down by its ending; MobLand season 2 (SkyShowtime); Mayday with Ryan Reynolds (Apple TV); One Hundred Years of Solitude (Netflix and Garcia Marquez's book).", "tag": "Media"},
    {"icon": "\U0001F331", "title": "Buhnici: farmland is underused by a factor of 10; hydroponic greenhouses grow pesticide-free vegetables; aphids escaped from greenhouses and the tiger mosquito are pests spread by human activity.", "tag": "Agriculture"},
    {"icon": "\U0001F3A5", "title": "The show's bumper was made mathematically by Opus 5, which isn't multimodal: it generates graphics programmatically and renders them with FFmpeg.", "tag": "AI"},
    {"icon": "\U0001F4DA", "title": "Sources cited: Bloomberg (HomePad, OpenAI/Anthropic probe), Reuters (Big Mac), Euronews (WorldSkills), Mobilissimo, Radu Georgescu, Frank de Jong (Orange Business), Alex Balan (ex-Bitdefender), the Prosumers Association.", "tag": "Sources"},
]

GLOSSARY = [
    {"term": "EU261", "def": "EU regulation requiring airlines to compensate and assist passengers for cancellations, delays and overbooking."},
    {"term": "ANPC", "def": "Romania's National Authority for Consumer Protection, where complaints go alongside an EU261 claim."},
    {"term": "BNR", "def": "Banca Nationala a Romaniei, the central bank that manages the leu's exchange rate."},
    {"term": "Prosumer", "def": "A consumer who generates and feeds their own power, usually solar, into the grid."},
    {"term": "HBM", "def": "High Bandwidth Memory, the wide-bandwidth memory used by AI accelerators."},
    {"term": "Tau's law", "def": "Huawei's approach of gaining performance by cutting signal noise and stacking transistors rather than shrinking them."},
    {"term": "Agentic commerce", "def": "Shopping done by AI agents that read websites and place orders for the user."},
    {"term": "Post-quantum cryptography", "def": "Encryption algorithms designed to withstand quantum computers."},
    {"term": "ADAS", "def": "Advanced driver-assistance systems (speed and lane warnings), increasingly mandated by the EU."},
    {"term": "No-show", "def": "Passengers who don't turn up (at least 2%), the reason airlines sell over capacity."},
]
