# -*- coding: utf-8 -*-
"""Grow your WEALTH - weekend post, published 2026-10-10 (Fri Oct 9 closes).
Romanian text source (members post, no video transcript): brief in English, quotes verbatim Romanian (no diacritics)."""

META = {
    "title": "Am vandut ASTS, am redirectionat banii si va explic calm de ce",
    "channel": "Grow your WEALTH - Valentin Dragu si Alex Marian",
    "speakers": "Valentin Dragu",
    "date": "2026-10-10",
    "video_url": "https://www.growyourwealth.ro/products/grow-your-wealth/categories/2160165880",
    "thread_line": "6 threads: the ASTS exit after Starlink's spectrum deal, Trump's SpaceX bonds and the space policy, a narrow rally under 5%+ yields, the CPI/PPI/earnings week, AI compute names, space/EV/fintech/nuclear and position sizing",
    "category": "market",
    "region": "ro",
}

SNAPSHOT = [
    "Valentin sold his entire **1,700-share ASTS** position in his IBKR account after Starlink's ~$8B 800 MHz spectrum deal; a further ~$8,000 realized loss, and the money went straight into 100 RKLB, 300 SPCX and 100 AVGO.",
    "Not panic, he says: he doesn't want to be positioned against SpaceX and Elon Musk. The GYW and GYW500 portfolios keep ASTS (-30%), with DCA planned below $45.",
    "Trump bought $1-5M of SpaceX 5.35% senior unsecured bonds on Aug 18, two days before signing the National Space Transportation Policy (1,000+ launches a year by 2030). Valentin files it as structural context, not a buy signal.",
    "Friday: S&P 500 +0.59% to 7,811.54, week +1.2%, but Nasdaq printed 41 new highs vs 209 new lows on below-average volume. A rally, not a broad return of risk appetite.",
    "Yields decide valuations: 10Y at **5.24%**, 30Y 5.60%. His map: 5.20-5.25% stabilization, 5.35% warning, 5.50% heavy pressure on growth; PIMCO's Ivascyn floated 6%.",
    "Week of Oct 12-16: bond market shut for Columbus Day, big-bank earnings Tuesday, CPI plus ASML Wednesday, PPI plus TSMC Thursday.",
    "Week in the portfolio: PLTR +10%+, IREN about -16%, ASTS about -13%, NBIS about -9%, RKLB about -8%. Levels given for all 14 names.",
    "Lesson he draws: 14 companies are not 14 independent risks; reassess sizing, don't buy every dip or sell every correction.",
]

THEMES = [
    {
        "id": "asts-exit",
        "tags": ["space", "consumer"],
        "color": "red",
        "badge": "Position exit",
        "status": "SOLD FRI OCT 9, IBKR ACCOUNT",
        "title": "Starlink's 800 MHz spectrum buy made him sell all 1,700 ASTS shares",
        "lead": "Volatility didn't change his view; competition did: the business itself is now impaired, he argues.",
        "bullets": [
            "Musk agreed to buy nationwide low-band 800 MHz spectrum from **Grain Management** for Starlink Mobile and direct-to-device service: ~$8B, pending regulatory approval, with much better in-building coverage if cleared.",
            "Industry reaction: T-Mobile about -13%, AT&T nearly -10%, Verizon nearly -9%; ASTS fell as low as $47.50 and closed at $50.97 (-10.47%) on ~54M shares.",
            "He sold the whole 1,700-share, ~$100,000 IBKR position: a further ~$8,000 loss on top of a tax-loss sell-and-rebuy 2-3 months earlier. Precedent: selling CLSK at a loss into AMD in April 2025.",
            "Proceeds went straight into 100 RKLB, 300 SPCX and 100 AVGO; he now sees $36k in AVGO, $50k in SPCX and $7k in RKLB as safer than $100k in a company whose market share 'a colossus' is attacking.",
            "GYW and GYW500 did **not** sell: they sit at -30% on ASTS and would DCA below $45. A right decision for one portfolio isn't automatically right for all.",
            "The bull case he keeps: telecom carriers threatened by Starlink Mobile may lean toward partnering with AST SpaceMobile, and Google, Apple or Meta likely won't route orbital signal through Musk's satellites. ASTS levels: support $47.50-48 then $45; resistance $53-55 then $57-59.",
            "He explicitly does not recommend members sell ASTS unless it's a deliberate decision with the money redeployed into other core positions.",
        ],
        "quote": {"text": "prioritatea mea este sa administrez cat mai bine cei 100.000 USD, nu sa am dreptate.", "cite": "— Valentin Dragu"},
        "watch": "Valentin runs the paid GYW community and now holds SPCX at 1,000 shares; the rotation was into the very competitor that hit ASTS.",
        "names": [
            {"name": "AST SpaceMobile (ASTS)", "blurb": "Sold out of his IBKR account on competition; GYW portfolios hold at -30%, DCA below $45.", "stance": "NEGATIVE VIEW", "conviction": "Medium", "horizon": None},
            {"name": "Grain Management", "blurb": "Seller of the ~$8B 800 MHz spectrum to SpaceX.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "T-Mobile (TMUS)", "blurb": "Fell ~13% on the Starlink spectrum news.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "AT&T (T)", "blurb": "Fell nearly 10% on the Starlink spectrum news.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Verizon (VZ)", "blurb": "Fell nearly 9% on the Starlink spectrum news.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "CleanSpark (CLSK)", "blurb": "His previous hard exit: sold at a loss into AMD in April 2025.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "trump-spacex-bonds",
        "tags": ["policy", "space"],
        "color": "amber",
        "badge": "Structural context",
        "status": "DISCLOSED IN OCTOBER, TRADES FROM AUGUST",
        "title": "Trump bought SpaceX bonds two days before signing the space policy",
        "lead": "He reads the sequence as context for SpaceX's tailwinds, not as a signal to chase space stocks.",
        "bullets": [
            "Aug 18: Trump bought $1-5M of SpaceX **senior unsecured** bonds, 5.35% coupon, maturing July 2031. Aug 20: he signed the National Space Transportation Policy targeting 1,000+ US launches and re-entries a year by 2030.",
            "The policy's two mechanisms: faster licensing from application to approval, and commercial access to publicly funded federal launch facilities. The biggest winner is the highest-cadence operator; SpaceX is a major NASA launch provider and US government contractor.",
            "Why debt, not equity? His two personal readings: pre-IPO SpaceX shares were too restricted, or a bond draws fewer questions because the holder doesn't benefit from a re-rating.",
            "The disclosure listed **517** securities trades in August, including $5-25M of Meta stock on Aug 21: direct equity, a much bigger order of magnitude.",
            "Weeks later, on Sept 29, Trump hosted Musk, Mark Zuckerberg and other AI leaders at the White House and argued against stricter AI safety rules; Valentin thinks that permissive stance supports valuations of heavy AI spenders.",
            "Lessons: retail learns this ~2 months late; regulation is a valuation factor; a policy with a 2030 horizon takes years to become cash flow. He warns that a 15% one-day jump in a small launch stock on such a headline traps people at the top.",
            "He watches three things: whether licensing actually speeds up launch cadence, whether federal-facility access turns into concrete contracts, and whether the AI deregulation tone becomes administrative decisions.",
        ],
        "quote": {"text": "Eu am trecut informatia asta la capitolul „context structural”, nu la capitolul „semnal de cumparare”", "cite": "— Valentin Dragu"},
        "watch": "His own caveat: no evidence the trade and the policy are causally linked, and public figures' portfolios are often run by third parties. He also just reached 1,000 SPCX shares and says Musk's ties to the presidency made him more bullish.",
        "names": None,
    },
    {
        "id": "macro-yields",
        "tags": ["macro-rates", "energy", "crypto"],
        "color": "amber",
        "badge": "Selective market",
        "status": "FRIDAY OCT 9 CLOSE",
        "title": "Indices up, breadth thin, and 5%+ Treasuries set the bar for growth",
        "lead": "The trend is positive, but participation is uneven and long yields stay the variable that decides valuations.",
        "bullets": [
            "Friday: S&P 500 7,811.54 (+0.59%), Nasdaq 27,366.17 (+0.64%), Dow 51,654.95 (+0.83%), Russell 2000 +0.46%. Week: S&P +1.2%, Nasdaq +0.6%, Dow +0.9%, Russell 2000 -0.9%.",
            "Breadth: NYSE advancers/decliners 1.65:1, Nasdaq 1.38:1, 10 of 11 sectors up (communication services lagged on telecoms). But Nasdaq had **41** new highs vs 209 new lows, and volume of 14.37B was below the 17.76B 20-day average.",
            "VIX fell to 14.84 from 15.41. A sub-15 VIX doesn't mean low single-stock risk: ASTS lost 10%+ in a calm market; concentrated growth portfolios run far hotter than the S&P 500.",
            "Treasuries: 2Y 4.79%, 10Y 5.24%, 30Y 5.60%. The 10Y ended below its 24-year highs on strong auction demand. Above 5%, investors get paid without single-stock risk, so long-duration growth names must offer more.",
            "AVGO and META already generate strong cash flow; NBIS, IREN, RKLB, ONDS and ASTS need heavy investment before meaningful profit, so they're far more rate-sensitive.",
            "UMich preliminary sentiment fell to 46.3 in October from 48.1 (consensus ~47.8); 12-month inflation expectations rose to 4.7% from 4.6%, long-term to 3.5% from 3.4%. Uncomfortable for the Fed, but he says the data does not support a stagflation call.",
            "Brent ranged ~$102.50-105 and closed $104.72 (+0.4%) after the administration signaled no new strikes on Iran before November's elections; DXY ~102.0-102.3, fourth straight weekly gain; Bitcoin ~$82,500-82,600, relevant to IREN and HOOD.",
        ],
        "quote": None,
        "watch": "PIMCO CIO Dan Ivascyn's 6% 10Y is presented as a risk scenario, not a forecast.",
        "names": None,
    },
    {
        "id": "week-ahead",
        "tags": ["macro-rates", "semis", "finance"],
        "color": "gray",
        "badge": "Catalyst calendar",
        "status": "OCT 12-16, 2026",
        "title": "CPI, PPI, big banks, ASML and TSMC: four scenarios for the week",
        "lead": "He lays out the calendar and the four ways it can break, without dramatizing.",
        "bullets": [
            "Mon Oct 12: stocks open, bond market closed for Columbus Day, which can distort liquidity and how yield-sensitive moves read.",
            "Tue Oct 13: JPMorgan Chase, Goldman Sachs, Citigroup and Wells Fargo report; he watches credit quality, deposit costs, loan demand and trading revenue, indirectly relevant to SOFI and HOOD.",
            "Wed Oct 14: September CPI at 15:30 Romania time, the week's key macro print; ASML and Bank of America report. Thu Oct 15: PPI at 15:30 and TSMC, whose demand and capacity outlook matters for AMD and AVGO. Fri Oct 16: import/export prices.",
            "Scenarios: cooler CPI/PPI with the 10Y below 5.20% means a broader growth recovery; in-line data means indices consolidate near highs; a hot surprise sends the 10Y back to 5.35-5.50%; weak ASML/TSMC order or margin signals is a separate semiconductor de-rating risk.",
            "Worst mix for the portfolio: hot inflation, rising yields and AI profitability estimates revised down together.",
        ],
        "quote": None,
        "watch": None,
        "names": [
            {"name": "JPMorgan (JPM)", "blurb": "Reports Oct 13; credit-quality read for SOFI and HOOD.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Goldman Sachs (GS)", "blurb": "Reports Oct 13; also upgraded PLTR to buy.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Citi (C)", "blurb": "Reports Oct 13.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Wells Fargo (WFC)", "blurb": "Reports Oct 13.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Bank of America (BAC)", "blurb": "Reports Oct 14.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "ASML", "blurb": "Reports Oct 14; order signals are a semis risk.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "TSMC (TSM)", "blurb": "Reports Oct 15; demand/capacity outlook matters for AMD and AVGO.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "ai-compute-book",
        "tags": ["ai-infra", "semis", "software"],
        "color": "green",
        "badge": "Holding / adding",
        "status": "AVGO, AMD, PLTR, META, NBIS, IREN",
        "title": "AI names: Broadcom topped up to $100k, Palantir broke out, capital intensity is the test",
        "lead": "Demand for AI isn't the question anymore; how much capital it takes to turn demand into profit is.",
        "bullets": [
            "**AVGO** $361.62 (+0.41%) after Thursday's -4.35%, on a lighter 16.5M shares. He added 100 shares to reach a $100,000 position. The new variable: Broadcom's ~$60B financing package for Anthropic's infrastructure build, mostly senior and junior debt. Support $357-360 then $350-352; resistance $366-370 then $376-381.",
            "**AMD** $607.98 (-2.05%), low $606 after Tuesday's $658.52 high. He'd avoid adding aggressively until price stabilizes. Support $600-605 then $590-595; resistance $620-625 then $635-645.",
            "**PLTR** $209.05 (+5.17%), week +10%+ from $185 to $210, on Goldman Sachs upgrading to buy ($230 target) and Barclays initiating at overweight ($265). Software-led AI with less data-center capex; the main risk is a very high valuation. Support $202-205; resistance $210 then $215-220.",
            "**META** $718.38 (-0.35%), consolidating; it banned TikTok and ByteDance ads in the US and six other markets. Edge: funding AI from a profitable business. Support $715-716 then $700-710; resistance $728-730 then $740-748.",
            "**NBIS** $221.08 (+0.62%) after Tuesday's $255.10. One green day doesn't end the correction; GPU utilization, contracted revenue, financing costs and cash generation decide. Support $217-220; resistance $225-230 then $237-243.",
            "**IREN** $35.21 (-1.40%), week about -15.7%, low $34.65. The market now prices data-center capex and AI revenue, not just Bitcoin. Support $34.50-35 then $32-33; resistance $36.50-38 then $40.",
        ],
        "quote": None,
        "watch": "Valentin owns every name in this card; levels are his own working zones, to be confirmed by price and volume.",
        "names": [
            {"name": "Broadcom (AVGO)", "blurb": "Added 100 shares to a $100k position; ~$60B Anthropic debt financing is the new variable.", "stance": "BUYING-ADDING", "conviction": "High", "horizon": "long term"},
            {"name": "AMD", "blurb": "Held; no aggressive adds until it stabilizes after the run.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Palantir (PLTR)", "blurb": "Held; broke out on Goldman and Barclays calls; valuation is the risk.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Meta (META)", "blurb": "Held; funds AI from profits; banned TikTok/ByteDance ads.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Nebius (NBIS)", "blurb": "Held; correction not confirmed over.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "IREN", "blurb": "Held; re-rating on data-center capex, -15.7% on the week.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Barclays (BCS)", "blurb": "Initiated PLTR at overweight, $265 target.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "space-ev-fintech-nuclear",
        "tags": ["space", "finance", "energy"],
        "color": "green",
        "badge": "Holding / adding",
        "status": "SPCX, TSLA, RKLB, SOFI, HOOD, ONDS, LEU",
        "title": "SpaceX hits his 1,000-share goal early; the rest of the book needs proof",
        "lead": "He is more bullish on SpaceX and Tesla than before, and warns that 14 names are not 14 independent risks.",
        "bullets": [
            "**SPCX** $162.56 (+1.24%): he reached the 1,000-share target he'd set for end-2026. Friday coincided with a reported lockup-expiry step, volume ~92.5M vs 71.9M Thursday; volume alone doesn't prove how much was sold. Support $160-161 then $155-158; resistance $166-168 then $172-176.",
            "**TSLA** $382.68 (+2.05%), high $388.53. Q3 report Oct 21: auto margins, cash flow, capex and autonomy progress. Support $375-378 then $368-370; resistance $388-390 then $400.",
            "**RKLB** $68.19 (-0.31%), week about -7.8%. Thesis: Neutron, Space Systems growth and satellite comms. Support $67 then $64-65; resistance $69-70 then $72-75.",
            "**SOFI** $15.81 (+1.28%): bank results should hint at loan demand and credit quality ahead of its Oct 27 report. **HOOD** $109.03 (+1.89%): Morgan Stanley raised its target from $150 to $160.",
            "**ONDS** $6.74 (-1.61%), week about -6.9%: revenue growth isn't enough if funding dilutes per-share value. **LEU** $142.40 (+0.22%): US nuclear-fuel supply-chain security supports the thesis, but industry growth doesn't guarantee near-term profit.",
            "Sizing lesson: if most holdings hang on the same variables (Treasury yields, liquidity, AI sentiment, risk appetite), the portfolio can correct hard while the S&P 500 sits at highs. Cash is flexibility, not a rigid rule.",
            "Closing point: retail learned of August's trades in October, by which time SPCX had run from $120 to $160 and META from $520 to $720.",
        ],
        "quote": {"text": "14 companii nu inseamna automat 14 surse independente de risc", "cite": "— Valentin Dragu"},
        "watch": "Valentin owns all of these; his SpaceX optimism leans partly on Musk's political ties, which he names himself.",
        "names": [
            {"name": "SpaceX (SPCX)", "blurb": "Bought 300 more, reaching 1,000 shares early; more bullish on Musk's ties to the presidency.", "stance": "BUYING-ADDING", "conviction": "High", "horizon": "medium to long term"},
            {"name": "Tesla (TSLA)", "blurb": "Held; more optimistic than before; Q3 report Oct 21.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Rocket Lab (RKLB)", "blurb": "Added 100 shares from the ASTS proceeds; Neutron thesis.", "stance": "BUYING-ADDING", "conviction": "Medium", "horizon": None},
            {"name": "SoFi (SOFI)", "blurb": "Held; earnings Oct 27.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Robinhood (HOOD)", "blurb": "Held; Morgan Stanley target $160.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Ondas (ONDS)", "blurb": "Held; dilution is the worry.", "stance": "OWNS", "conviction": "Low", "horizon": None},
            {"name": "Centrus Energy (LEU)", "blurb": "Held; nuclear-fuel supply-chain thesis.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Morgan Stanley (MS)", "blurb": "Raised HOOD target to $160.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F6F0", "tag": "Space", "title": "Re-test any direct-to-device satellite thesis against Starlink Mobile's 800 MHz spectrum before adding."},
    {"icon": "\U0001F4CF", "tag": "Sizing", "title": "Map which holdings share the same rate and AI-sentiment exposure, and size them as one risk."},
    {"icon": "\U0001F4C8", "tag": "Macro", "title": "Watch the 10Y against 5.20%, 5.35% and 5.50% through CPI (Oct 14) and PPI (Oct 15)."},
    {"icon": "\U0001F9FE", "tag": "Policy", "title": "File politician-disclosure headlines as context; skip the one-day 15% pops in small space names."},
    {"icon": "\U0001F50C", "tag": "Semis", "title": "Read ASML and TSMC guidance for order slowdowns before adding to AMD or AVGO."},
]

HOT_TAKES = [
    {"take": "Pur si simplu nu vreau sa am o pozitie impotriva SpaceX si a lui Elon Musk", "cite": "— Valentin Dragu", "why": "sold a $100k position at a loss on competitive grounds"},
    {"take": "Nu exista nicio situatie in care investitorul mic sa fie primul la masa. Niciuna. Cine va promite altceva, va minte.", "cite": "— Valentin Dragu", "why": "absolute dismissal of retail information edge"},
    {"take": "reglementarea nu e zgomot de fundal, este un factor de evaluare.", "cite": "— Valentin Dragu", "why": "policy as valuation input"},
    {"take": "Nu toata lumea cauta x10.", "cite": "— Valentin Dragu", "why": "calls the community's disdain for fixed income immature"},
    {"take": "Nu cumparati povesti. Cumparati companii.", "cite": "— Valentin Dragu", "why": "closing conviction"},
]

CLAIMS = [
    {"who": "Valentin Dragu", "claim": "GYW portfolios will DCA into ASTS if it falls below $45.", "metric": "ASTS share price", "target": "<$45", "by": None, "condition": "price below $45", "entity": "AST SpaceMobile (ASTS)"},
    {"who": "Valentin Dragu", "claim": "Cooler CPI/PPI with the 10Y below 5.20% would bring a broader recovery in growth stocks.", "metric": "US 10Y yield", "target": "<5.20%", "by": "2026-10-16", "condition": "CPI and PPI show inflation easing", "entity": None},
    {"who": "Valentin Dragu", "claim": "A hot inflation surprise sends the 10Y back toward 5.35-5.50%.", "metric": "US 10Y yield", "target": "5.35-5.50%", "by": "2026-10-16", "condition": "inflation surprises to the upside", "entity": None},
    {"who": "Valentin Dragu", "claim": "Above 5.50% on the 10Y, pressure on growth-stock valuations becomes considerably stronger.", "metric": "US 10Y yield", "target": "5.50%", "by": None, "condition": None, "entity": None},
    {"who": "Dan Ivascyn (cited by Valentin Dragu)", "claim": "The 10Y yield could reach 6% on inflation, deficits and bond-market pressure.", "metric": "US 10Y yield", "target": "6%", "by": None, "condition": None, "entity": None},
    {"who": "Goldman Sachs (cited by Valentin Dragu)", "claim": "Palantir upgraded to buy with a $230 price target.", "metric": "PLTR price target", "target": "$230", "by": None, "condition": None, "entity": "Palantir (PLTR)"},
    {"who": "Barclays (cited by Valentin Dragu)", "claim": "Palantir initiated at overweight with a $265 price target.", "metric": "PLTR price target", "target": "$265", "by": None, "condition": None, "entity": "Palantir (PLTR)"},
    {"who": "Morgan Stanley (cited by Valentin Dragu)", "claim": "Robinhood price target raised to $160 from $150.", "metric": "HOOD price target", "target": "$160", "by": None, "condition": None, "entity": "Robinhood (HOOD)"},
    {"who": "Trump administration (cited by Valentin Dragu)", "claim": "The National Space Transportation Policy targets more than 1,000 US launches and re-entries a year.", "metric": "annual US launches and re-entries", "target": "1,000+", "by": "2030", "condition": None, "entity": None},
    {"who": "Valentin Dragu", "claim": "Starlink's ~$8B 800 MHz spectrum purchase from Grain Management awaits regulatory approval.", "metric": "regulatory approval", "target": "approved", "by": None, "condition": None, "entity": "SpaceX (SPCX)"},
    {"who": "Valentin Dragu", "claim": "Big US banks start reporting: JPMorgan Chase, Goldman Sachs, Citigroup, Wells Fargo.", "metric": "earnings", "target": None, "by": "2026-10-13", "condition": None, "entity": None},
    {"who": "Valentin Dragu", "claim": "September CPI (15:30 Romania time) plus ASML and Bank of America earnings.", "metric": "CPI / earnings", "target": None, "by": "2026-10-14", "condition": None, "entity": "ASML"},
    {"who": "Valentin Dragu", "claim": "PPI (15:30 Romania time) and TSMC earnings; TSMC's outlook matters for AMD and AVGO.", "metric": "PPI / earnings", "target": None, "by": "2026-10-15", "condition": None, "entity": "TSMC (TSM)"},
    {"who": "Valentin Dragu", "claim": "Tesla's Q3 report: auto margins, cash flow, capex and autonomy progress.", "metric": "earnings", "target": None, "by": "2026-10-21", "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Valentin Dragu", "claim": "SoFi reports results; bank earnings first hint at loan demand and credit quality.", "metric": "earnings", "target": None, "by": "2026-10-27", "condition": None, "entity": "SoFi (SOFI)"},
]

RELATIONS = [
    {"from": "SpaceX (SPCX)", "rel": "competes_with", "to": "AST SpaceMobile (ASTS)", "note": "Starlink Mobile direct-to-device on new 800 MHz spectrum"},
    {"from": "SpaceX (SPCX)", "rel": "customer_of", "to": "Grain Management", "note": "~$8B nationwide 800 MHz spectrum purchase, pending approval"},
    {"from": "SpaceX (SPCX)", "rel": "supplies", "to": "NASA", "note": "major launch services provider"},
    {"from": "Donald Trump", "rel": "invests_in", "to": "SpaceX (SPCX)", "note": "$1-5M of 5.35% senior unsecured bonds due July 2031, bought Aug 18"},
    {"from": "Donald Trump", "rel": "invests_in", "to": "Meta (META)", "note": "$5-25M of stock bought Aug 21"},
    {"from": "Broadcom (AVGO)", "rel": "partners_with", "to": "Anthropic", "note": "~$60B financing package, mostly senior and junior debt, for Anthropic's infrastructure"},
    {"from": "Meta (META)", "rel": "competes_with", "to": "TikTok", "note": "banned TikTok and ByteDance ads in the US and six other markets"},
    {"from": "Goldman Sachs (GS)", "rel": "endorses", "to": "Palantir (PLTR)", "note": "upgrade to buy, $230 target"},
    {"from": "Barclays (BCS)", "rel": "endorses", "to": "Palantir (PLTR)", "note": "initiated overweight, $265 target"},
    {"from": "Morgan Stanley (MS)", "rel": "endorses", "to": "Robinhood (HOOD)", "note": "target raised to $160 from $150"},
]

OTHER_NEWS = [
    {"icon": "\U0001F4DA", "tag": "Sources", "title": "Sources referenced: Trump's August financial disclosure (517 transactions), PIMCO CIO Dan Ivascyn's 6% 10Y warning, the University of Michigan sentiment survey, and analyst notes from Goldman Sachs, Barclays and Morgan Stanley."},
]

GLOSSARY = [
    {"term": "Senior unsecured bond", "def": "Company debt with no collateral behind it, ranked ahead of junior debt and equity; the holder gets a fixed coupon, not upside."},
    {"term": "Tax-loss sell-and-rebuy", "def": "Selling a losing position to book the loss for tax purposes, then buying it back."},
    {"term": "DCA", "def": "Dollar-cost averaging: buying in fixed slices over time or at set price levels instead of all at once."},
    {"term": "Lockup expiry", "def": "The date when insiders and early holders are first allowed to sell shares after a listing."},
    {"term": "Advance/decline ratio", "def": "Rising stocks divided by falling stocks on an exchange; a breadth gauge."},
    {"term": "DXY", "def": "The US dollar index against a basket of major currencies."},
    {"term": "GYW / GYW500", "def": "Grow your WEALTH's community model portfolios, separate from Valentin's personal IBKR account."},
]
