# -*- coding: utf-8 -*-
"""Grow your WEALTH - morning post, published 2026-10-06 (Mon Oct 5 session).
Romanian text source (members post, no video transcript): brief in English, quotes verbatim Romanian (no diacritics)."""

META = {
    "title": "SPCX decoleaza, concentrare vs diversificare, ETF/dividende vs Growth",
    "channel": "Grow your WEALTH - Valentin Dragu si Alex Marian",
    "speakers": "Valentin Dragu",
    "date": "2026-10-06",
    "video_url": "https://www.growyourwealth.ro/products/grow-your-wealth",
    "thread_line": "6 threads: why concentration beats diversification early, growth over dividends in the first 5-10 years, a Nasdaq record against a 5.31% 10Y, Broadcom-Anthropic financing plus AMD and Tesla, SpaceX +7.6% into a lockup, and the rest of the book",
    "category": "market",
    "region": "ro",
}

SNAPSHOT = [
    "Two philosophy pieces for members: a concentrated 15-20 stock portfolio grows faster than a diversified one over 5-10 years, and growth beats ETF/dividend investing for someone in their first 5-10 years.",
    "The math he uses: $100k at 10% a year is ~$259k after ten years, at 15% ~$405k, at 20% ~$619k. **20%** is his stated target for his own and managed portfolios.",
    "Monday: Nasdaq +1.05% to a record 27,477.31, S&P 500 +0.66% to 7,773.95; Oct hike odds fell from ~70% to 24% after the 29k NFP. But the 10Y closed ~5.31%, highest since 2002.",
    "His warning for dividend investors: with Treasuries paying 5%, dividend stocks will correct hard; a 6-7% yield doesn't help if the stock drops 30-40%.",
    "SPCX +7.63% to $171.09 on Morgan Stanley's 'cheap and getting cheaper' call ($300 target). He'd already rotated 300 VST into 300 SPCX; he expects a pullback to $160-162 before the Oct 9 lockup expiry.",
    "Broadcom-Anthropic: BofA, Citi and Morgan Stanley are arranging ~$60B ($42B senior secured, partly Broadcom-guaranteed, plus ~$18B junior). Bull and bear case strengthen at once.",
    "Each holding gets one conversion test (Helios into orders, deliveries into margins, GPU capex into utilization); cash is kept for a 10-15% growth correction, not because he's bearish.",
]

THEMES = [
    {
        "id": "concentration",
        "tags": ["finance", "mindset"],
        "color": "green",
        "badge": "Core philosophy",
        "status": "MEMBER EDUCATION",
        "title": "Why 15-20 stocks can outgrow 100 over five to ten years",
        "lead": "Diversification shrinks the damage from a loser, and it shrinks the payoff from a winner by exactly the same mechanism.",
        "bullets": [
            "With 100 companies, one that 5x's barely moves the portfolio; with 15-20 names, a stock at 8-10% weight that doubles or triples changes the outcome.",
            "He cites his own wins with Tesla, Palantir, SoFi, AMD and Robinhood, and names SPCX, RKLB, ASTS and Ondas as the 'new pearls' he expects to repeat it.",
            "Concentration isn't a bet: ~15 companies spread over AI, semis, digital finance, space, energy, nuclear, robotics and autonomy, so the money doesn't hang on one industry.",
            "The cost: it amplifies mistakes as much as good calls, so every holding must be one the investor understands and follows constantly.",
            "When a mistake shows up, as CLSK did from 2024 to April 2025, cut it at the root and move the money into a position already proving its outlook.",
        ],
        "quote": {"text": "atunci cand gasim o companie extraordinara si avem dreptate, vrem ca acea decizie sa conteze", "cite": "— Valentin Dragu"},
        "watch": "Valentin sells the GYW membership built on this approach; the winners list and 9-year record are his own account of his results.",
        "names": [
            {"name": "SpaceX (SPCX)", "blurb": "One of the 'new pearls'; rotated 300 VST into 300 more SPCX, most of October's cash went here.", "stance": "BUYING-ADDING", "conviction": "High", "horizon": "5-10 years"},
            {"name": "Rocket Lab (RKLB)", "blurb": "Named a 'new pearl' for the next leg.", "stance": "POSITIVE VIEW", "conviction": "High", "horizon": "5-10 years"},
            {"name": "AST SpaceMobile (ASTS)", "blurb": "Named a 'new pearl' (three days before he sold his personal stake).", "stance": "POSITIVE VIEW", "conviction": "High", "horizon": "5-10 years"},
            {"name": "Ondas (ONDS)", "blurb": "Named a 'new pearl'.", "stance": "POSITIVE VIEW", "conviction": "Medium", "horizon": "5-10 years"},
            {"name": "Vistra (VST)", "blurb": "300 shares rotated out into SPCX.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "CleanSpark (CLSK)", "blurb": "His example of a mistake cut at the root (2024 to April 2025).", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "growth-vs-dividends",
        "tags": ["finance", "mindset"],
        "color": "green",
        "badge": "Core philosophy",
        "status": "FIRST 5-10 YEARS",
        "title": "Build capital first, then income: growth over dividends early",
        "lead": "Someone aged 30-45 with a salary doesn't need the portfolio to pay bills, so total return matters more than yield.",
        "bullets": [
            "The question isn't 'how much dividend do I get?' but 'how much does my money grow in total?'. A 4% yield plus 5% price gain is ~9%; a non-payer rising 15% wins.",
            "Compounding example: $100k at 10% (the S&P 500's annualized average) becomes ~$259k in ten years, at 15% ~$405k, at 20% ~$619k. Not promises, and never linear.",
            "Income math: $50k at 4% yield is ~$2,000 a year, ~$175 a month. Grow it to $500k-1M first, then shift toward stable payers, bonds, or option income.",
            "GYW portfolios already earn monthly income from selling covered calls and cash-secured puts, not dividends; he argues that pays more annualized while keeping growth upside.",
            "Lifecycle: build wealth, then protect it, then draw income. A 30% drop is $15k on $50k but $600k on $2M near retirement: same percentage, different consequence.",
            "Young investors can stomach 30-50% drawdowns (see 2022) because salary keeps funding buys at lower prices.",
            "Growth doesn't mean buying anything that rises: rising sales and profits, competitive products, a future industry, and a price future results can justify.",
        ],
        "quote": {"text": "Companii extraordinare, cumparate la preturi pe care rezultatele viitoare le pot justifica.", "cite": "— Valentin Dragu"},
        "watch": None,
        "names": None,
    },
    {
        "id": "nasdaq-vs-treasury",
        "tags": ["macro-rates", "energy"],
        "color": "amber",
        "badge": "Divergence",
        "status": "MONDAY OCT 5 SESSION",
        "title": "A Nasdaq record with the 10Y at 5.31%, its highest since 2002",
        "lead": "Stocks are rising despite yields, not because of them: AI earnings growth is outrunning a very high discount rate.",
        "bullets": [
            "Nasdaq +1.05% to a record 27,477.31, S&P 500 +0.66% to 7,773.95 (~0.3% off its high), Dow +0.18%, Russell 2000 +0.5%; 10 of 11 sectors green on light volume. Nvidia +2.1% to a record; Microsoft, Meta and Tesla joined.",
            "Catalysts: Friday's weak NFP cut October hike odds from ~70% to **24%**, and oil eased. ISM Services 54.9 vs 55 consensus (55.4 prior); S&P Global Services PMI 58.8 vs 56.5.",
            "The 10Y dipped from ~5.307% to 5.298% after ISM, then failed: ~5.31% close, 30Y near 5.68%. Long-end prices fiscal risk, supply, term premium, sticky inflation and energy; French debt worries add global risk premium.",
            "His thresholds: below 5.20% real relief; 5.20-5.30% manageable; 5.30-5.35% the critical zone now; above 5.35% clear multiple-compression risk.",
            "Oil: Brent ~$100.32, WTI $89.43 on more Middle East exports and G7 supply pledges. Hormuz stays closed (about a fifth of global supply normally transits), so $100 is relief, not victory. Euro at a 17-month low per Reuters; strong USD plus high 10Y tightens conditions globally.",
            "Bitcoin matters for HOOD and IREN, but the setup he wants is BTC up with the 10Y down; BTC alone makes their upside momentum-driven.",
            "Today (Oct 6): August trade deficit, consensus ~$102B vs $88.6B; Dallas Fed's Lorie Logan speaks in the evening. Wednesday's minutes of the Sept 15-16 FOMC are the week's real event.",
        ],
        "quote": {"text": "degeaba primesti chiar un dividend si de 6-7%, daca iti scade actiunea cu 30-40%", "cite": "— Valentin Dragu"},
        "watch": None,
        "names": [
            {"name": "Nvidia (NVDA)", "blurb": "+2.1% to a record.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Microsoft (MSFT)", "blurb": "Joined the mega-cap rally.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "McDonald's (MCD)", "blurb": "His example: a 5% dividend is less safe than a 5% Treasury.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "avgo-amd-tsla",
        "tags": ["ai-infra", "semis"],
        "color": "amber",
        "badge": "Holding, scrutinize",
        "status": "AVGO, AMD, TSLA",
        "title": "Broadcom's Anthropic financing strengthens the bull and bear case at once",
        "lead": "For AVGO the KPI is no longer AI revenue but AI revenue minus cost of capital, credit risk and concentration risk.",
        "bullets": [
            "Broadcom can finance up to $42B of Anthropic's infrastructure; Anthropic has ~$125.2B of commitments over five years and is expected to be AVGO's largest chip-design customer in 2027.",
            "New Monday: **Bank of America**, Citi and Morgan Stanley are preparing a ~$60B package: $42B senior secured debt partly guaranteed by Broadcom plus ~$18B junior. Bull: extraordinary demand visibility. Risk: increasingly vendor financing.",
            "AVGO levels: support $346-350 then $338-342; $360-365 must clear to restart momentum.",
            "AMD ~$631.75 (-0.3%) despite Stifel raising its target to $700 and BNP Paribas to $960 on Helios as a credible AI-infrastructure alternative; SOX +0.3%, Nvidia +2.1%. After 2026's run the market wants orders, not targets. Support $620-625 then $600; resistance $640-645.",
            "Tesla +~2.5%, back above $380 after Q3 deliveries of 486,532. Oct 21 earnings test margins, ASP, FCF and capex; Baird Buy/$475, JPMorgan Hold/$415, BNP Paribas Sell/$268 on AI capex near ~$25B in 2026.",
            "Musk suggested TSMC could join the Tesla/SpaceX Terafab project, cutting execution risk from relying only on Intel. TSLA: resistance $385 then $400-415; support $370-375 then $355-360.",
        ],
        "quote": None,
        "watch": "Valentin owns all three; he rotated into AVGO earlier and calls it the name he watches most closely.",
        "names": [
            {"name": "Broadcom (AVGO)", "blurb": "Among the best AI exposures and the one to scrutinize hardest; vendor-financing risk.", "stance": "OWNS", "conviction": "High", "horizon": None},
            {"name": "AMD", "blurb": "Held; wants Helios orders and revenue conversion; break above $645.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Tesla (TSLA)", "blurb": "Held; margins and FCF on Oct 21 are the test.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Anthropic", "blurb": "Broadcom's expected largest chip-design customer in 2027.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Stifel", "blurb": "AMD target raised to $700.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "BNP Paribas", "blurb": "AMD target $960; Tesla Sell/$268.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Baird", "blurb": "Tesla Buy/$475.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "TSMC (TSM)", "blurb": "Floated by Musk as a Terafab participant.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Intel (INTC)", "blurb": "Terafab partner whose sole-source risk TSMC would reduce.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "spacex-lockup",
        "tags": ["space"],
        "color": "green",
        "badge": "Leader, don't chase",
        "status": "SPCX +7.63% TO $171.09",
        "title": "SpaceX re-rated by Morgan Stanley, with a lockup expiry three days out",
        "lead": "Fundamentals improved; market mechanics may add supply on Friday, so he isn't chasing.",
        "bullets": [
            "SPCX +7.63% to $171.09 (high $172.47), the session's mega-cap leader. Morgan Stanley calls it 'cheap and getting cheaper' versus growth, Overweight, $300 target.",
            "The market is starting to price SpaceX as an integrated Space + Connectivity + AI platform, not just launch plus Starlink.",
            "Operations: Falcon 9 flew the SDA Tranche 1 Transport Layer A mission; the next major catalyst is Starship Flight 15.",
            "Risk: Oct 9 lockup expiry on up to ~328.4M Class A shares, per the SEC-filing calendar. Support $158-160; resistance $172-175 then $180. He expects a profit-taking dip toward $160-162.",
            "Rocket Lab rides space sentiment and an Electron backlog after the Synspective contract: support $68-70, resistance $75-76 then $80.",
            "ASTS needs its own proof: an SPCX rally doesn't produce ASTS revenue. The chain is satellites, deployment, coverage, carrier activation, revenue. Support $58-61, resistance $65-68.",
        ],
        "quote": None,
        "watch": "Valentin concentrated most of October's new money into SPCX.",
        "names": [
            {"name": "Morgan Stanley (MS)", "blurb": "SPCX Overweight, $300 target; also arranging Anthropic financing.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
            {"name": "Synspective", "blurb": "Contract feeding Rocket Lab's Electron backlog.", "stance": "CASUAL MENTION", "conviction": "None", "horizon": None},
        ],
    },
    {
        "id": "rest-of-book",
        "tags": ["software", "finance", "energy"],
        "color": "amber",
        "badge": "Holding",
        "status": "META, PLTR, NBIS, SOFI, HOOD, ONDS, LEU, IREN",
        "title": "Every holding gets one conversion test, and cash waits for a correction",
        "lead": "At a 5.31% 10Y, current revenue, cash flow and ROIC beat future promises.",
        "bullets": [
            "**Meta**: funds AI capex from a very profitable ad engine; self-funded growth is worth more than debt-funded at 5.31%. Support $715-720 then $700; resistance $740-750.",
            "**Palantir** $189.40 (+0.34%): trailing revenue +78.9%, but ~161x trailing and nearly 100x forward earnings, 'one of the most expensive stocks in the market', so very 10Y-sensitive. Support $185-188, resistance $193-195, then $200-207.",
            "**Nebius**: no new catalyst ('we don't invent one'); $247-250 is the breakout test, support $235-240; KPI is GPU utilization and revenue/FCF per capex dollar.",
            "**SoFi** wants lower rates without recession, support $15.50-16. **Robinhood** wants equities up, BTC up, VIX contained; support $112-116, resistance $120-122.",
            "**Ondas**: revenue can grow spectacularly yet per-share value stays modest if share count rises too fast; support $7.20-7.40, resistance $8-8.20. **Centrus** (LEU): HALEU edge, support $135-140, must reclaim $147-150. **IREN**: less 'BTC beta', more contracted AI revenue; support $40-42, recover $45-46.",
            "Next-session scenarios: bullish (10Y back to 5.25%, Brent under $100); healthy consolidation (10Y 5.25-5.32%, his preference); bond shock above 5.35% hitting PLTR, NBIS, RKLB, ASTS, ONDS, IREN; Brent above $105 on Hormuz.",
            "Cash isn't bearishness: the portfolio has enough beta, and cash is there for a 10-15% high-growth correction without broken fundamentals.",
        ],
        "quote": {"text": "continuam sa cumparam business-uri, nu candles.", "cite": "— Valentin Dragu"},
        "watch": "Valentin owns every name here; levels are his working zones.",
        "names": [
            {"name": "Meta (META)", "blurb": "Held; self-funded AI capex.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Palantir (PLTR)", "blurb": "Held; excellent business, very stretched multiple.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Nebius (NBIS)", "blurb": "Held; $250 breakout test.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "SoFi (SOFI)", "blurb": "Held; credit quality is the test.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Robinhood (HOOD)", "blurb": "Held; monetize engagement.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "Centrus Energy (LEU)", "blurb": "Held; strategically bullish, technically unconfirmed.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
            {"name": "IREN", "blurb": "Held; wants contracted AI revenue over BTC beta.", "stance": "OWNS", "conviction": "Medium", "horizon": None},
        ],
    },
]

TAKEAWAYS = [
    {"icon": "\U0001F3AF", "tag": "Portfolio", "title": "Judge holdings by total return, not yield, while you're still adding from a salary."},
    {"icon": "\U0001F4C9", "tag": "Macro", "title": "Treat a 10Y above 5.35% as the trigger for multiple compression in high-beta names."},
    {"icon": "\U0001F9EE", "tag": "AI infra", "title": "Score Broadcom on value created after financing and credit risk, not on headline AI revenue."},
    {"icon": "\U0001F6F0", "tag": "Space", "title": "Wait out the Oct 9 SPCX lockup before adding after a 7.6% day."},
    {"icon": "\U0001F4B5", "tag": "Sizing", "title": "Keep cash for a 10-15% growth correction instead of buying every green session."},
]

HOT_TAKES = [
    {"take": "atata timp cat vom avea randamente mari la titlurile de stat (si vom avea), actiunile companiilor platitoare de dividende se vor corecta agresiv", "cite": "— Valentin Dragu", "why": "calls a sector-wide correction in dividend stocks"},
    {"take": "Piata tot va creste pe zona de AI, datorita sumelor mari investite pe mai departe.", "cite": "— Valentin Dragu", "why": "even through another hike, maybe in December, and high oil"},
    {"take": "la 20% (aici este target-ul meu atat pe propriul portofoliu cat si pe cele administrate)", "cite": "— Valentin Dragu", "why": "20% annual target, double the S&P average"},
    {"take": "Sincer, aici ma astept sa revenim spre 162-160$ dupa o marcare de profit", "cite": "— Valentin Dragu", "why": "short-term SPCX pullback call"},
    {"take": "Culmea este ca daca vinzi contracte CC si CSP, ai un randamant mai mare anualizat/lunar si ramai si cu expunere pe potentialul de crestere", "cite": "— Valentin Dragu", "why": "option income beats dividends claim"},
]

CLAIMS = [
    {"who": "Valentin Dragu", "claim": "Targets 20% average annual returns on his own and managed portfolios.", "metric": "annual portfolio return", "target": "20%", "by": None, "condition": None, "entity": None},
    {"who": "Valentin Dragu", "claim": "Dividend-paying stocks will correct aggressively while Treasury yields stay high.", "metric": "dividend stock prices", "target": "aggressive correction", "by": None, "condition": "Treasury yields stay around 5%", "entity": None},
    {"who": "Valentin Dragu", "claim": "The AI trade keeps rising even with another rate hike, possibly in December, and high oil.", "metric": "AI stocks", "target": "higher", "by": "2026-12", "condition": "another Fed hike and elevated oil", "entity": None},
    {"who": "Valentin Dragu", "claim": "SPCX pulls back toward $160-162 on profit-taking after the 7.6% day.", "metric": "SPCX share price", "target": "$160-162", "by": "2026-10-09", "condition": None, "entity": "SpaceX (SPCX)"},
    {"who": "Valentin Dragu", "claim": "A 10Y clearly above 5.35% means multiple compression can overtake AI enthusiasm.", "metric": "US 10Y yield", "target": ">5.35%", "by": None, "condition": None, "entity": None},
    {"who": "Valentin Dragu", "claim": "Brent back above $105 on Hormuz would push yields and Fed risk up and growth valuations down.", "metric": "Brent", "target": ">$105", "by": None, "condition": "new deterioration in Hormuz", "entity": "Oil"},
    {"who": "Morgan Stanley (cited by Valentin Dragu)", "claim": "SpaceX is 'cheap and getting cheaper' relative to growth; Overweight with a $300 target.", "metric": "SPCX price target", "target": "$300", "by": None, "condition": None, "entity": "SpaceX (SPCX)"},
    {"who": "Stifel (cited by Valentin Dragu)", "claim": "AMD price target raised to $700.", "metric": "AMD price target", "target": "$700", "by": None, "condition": None, "entity": "AMD"},
    {"who": "BNP Paribas (cited by Valentin Dragu)", "claim": "AMD price target raised to $960 on Helios.", "metric": "AMD price target", "target": "$960", "by": None, "condition": None, "entity": "AMD"},
    {"who": "Baird (cited by Valentin Dragu)", "claim": "Tesla Buy with a $475 target.", "metric": "TSLA price target", "target": "$475", "by": None, "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "JPMorgan (cited by Valentin Dragu)", "claim": "Tesla Hold with a $415 target.", "metric": "TSLA price target", "target": "$415", "by": None, "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "BNP Paribas (cited by Valentin Dragu)", "claim": "Tesla Sell with a $268 target; AI spending could push 2026 capex near $25B and pressure FCF.", "metric": "TSLA price target / capex", "target": "$268 / ~$25B", "by": "2026", "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Valentin Dragu", "claim": "Anthropic is expected to become the largest customer of Broadcom's chip-design business.", "metric": "largest chip-design customer", "target": "Anthropic", "by": "2027", "condition": None, "entity": "Broadcom (AVGO)"},
    {"who": "Valentin Dragu", "claim": "Lockup expiry on up to ~328.4M SpaceX Class A shares.", "metric": "lockup expiry", "target": "~328.4M shares", "by": "2026-10-09", "condition": None, "entity": "SpaceX (SPCX)"},
    {"who": "Valentin Dragu", "claim": "Starship Flight 15 is SpaceX's next major catalyst.", "metric": "launch", "target": "Starship Flight 15", "by": None, "condition": None, "entity": "SpaceX (SPCX)"},
    {"who": "Valentin Dragu", "claim": "Tesla Q3 earnings: automotive gross margin, ASP, FCF and capex.", "metric": "earnings", "target": None, "by": "2026-10-21", "condition": None, "entity": "Tesla (TSLA)"},
    {"who": "Valentin Dragu", "claim": "Minutes of the Sept 15-16 FOMC are the week's key event.", "metric": "FOMC minutes", "target": None, "by": "2026-10-07", "condition": None, "entity": None},
    {"who": "Valentin Dragu", "claim": "August US trade deficit expected around $102B vs $88.6B prior.", "metric": "US trade deficit", "target": "~$102B", "by": "2026-10-06", "condition": None, "entity": None},
]

RELATIONS = [
    {"from": "Broadcom (AVGO)", "rel": "supplies", "to": "Anthropic", "note": "can finance up to $42B of Anthropic infrastructure; largest chip-design customer expected in 2027"},
    {"from": "Bank of America (BAC)", "rel": "partners_with", "to": "Anthropic", "note": "arranging ~$60B financing with Citi and Morgan Stanley"},
    {"from": "Citi (C)", "rel": "partners_with", "to": "Anthropic", "note": "part of the ~$60B financing package"},
    {"from": "Morgan Stanley (MS)", "rel": "partners_with", "to": "Anthropic", "note": "part of the ~$60B financing package"},
    {"from": "Morgan Stanley (MS)", "rel": "endorses", "to": "SpaceX (SPCX)", "note": "Overweight, $300 target"},
    {"from": "Stifel", "rel": "endorses", "to": "AMD", "note": "target $700"},
    {"from": "BNP Paribas", "rel": "endorses", "to": "AMD", "note": "target $960 on Helios"},
    {"from": "Baird", "rel": "endorses", "to": "Tesla (TSLA)", "note": "Buy, $475"},
    {"from": "BNP Paribas", "rel": "criticizes", "to": "Tesla (TSLA)", "note": "Sell, $268 on capex pressure"},
    {"from": "TSMC (TSM)", "rel": "partners_with", "to": "Tesla (TSLA)", "note": "Musk suggested TSMC could join the Terafab project"},
    {"from": "Synspective", "rel": "customer_of", "to": "Rocket Lab (RKLB)", "note": "Electron launch contract"},
]

OTHER_NEWS = [
    {"icon": "\U0001F4DA", "tag": "Sources", "title": "Sources referenced: Reuters (euro at a 17-month low), the SEC-filing lockup calendar, and analyst notes from Morgan Stanley, Stifel, BNP Paribas, Baird and JPMorgan."},
]

GLOSSARY = [
    {"term": "Covered call (CC)", "def": "Selling a call option on shares you own to collect premium, capping upside above the strike."},
    {"term": "Cash-secured put (CSP)", "def": "Selling a put while holding cash to buy the shares if assigned, collecting premium meanwhile."},
    {"term": "Vendor financing", "def": "A supplier funding its customer's purchases, so revenue comes with credit risk on the supplier's books."},
    {"term": "Multiple compression", "def": "Valuation multiples (P/E etc.) shrinking, usually as rates rise, even if earnings hold."},
    {"term": "Term premium", "def": "The extra yield investors demand to hold long bonds instead of rolling short ones."},
    {"term": "HALEU", "def": "High-assay low-enriched uranium, fuel for advanced reactors; Centrus's structural edge."},
    {"term": "Lockup expiry", "def": "The date insiders and early holders may first sell shares after a listing."},
]
